### ISSUE TITLE
Did you ever get hterm to work for firefox?

### ISSUE THREAD

**Issue by terryschen** [butlerx/wetty#1]
Hi,

I saw this conversation (http://bit.ly/1r1qeg5) in chromium-hterm and I am curious did you ever manage to get it working for Firefox reliably?

Thanks
Terry

**Comment by krishnasrinivas** [comment]
I did get it to work on FF ... check out nuttyapp's hterm (https://github.com/krishnasrinivas/nuttyapp/blob/master/client/scripts/extern/hterm/hterm.js) It has a lot of kludges though.

**Comment by terryschen** [comment]
Hi,

Thanks for the quick reply. I will look into that link. Is that hterm.js the same one you are using for wetty? 

Terry

**Comment by krishnasrinivas** [comment]
No wetty's hterm.js doesn't have the fixes for FF

**Comment by terryschen** [comment]
Okay, thanks for letting me know!

**Comment by HerringtonDarkholme** [comment]
hterm has supported FF since 2014 Oct, according to hterm's doc. I have tried wetty in firefox and it works like a charm
