### ISSUE TITLE
Login timed out after 60 seconds

### ISSUE THREAD

**Issue by rkkrishnaa** [butlerx/wetty#100]
Hello,

I have accessed the wetty web terminal from my browser. I kept my session idle for one minute. My session has timed out and I need to refresh the page to establish the connection again. I have checked my debugger console. There is no polling request sent to the server. I have explored the application and socket io lib. I cant find any way to change the config to extend the socket time out. Is there any way to increase the time out and keep the session alive for 5mins before login to the web terminal.

Is there any way to increase the time out in web terminal after login to the application. I am having this problem when more than 50 users accessing the web terminal concurrently. I have seen the application log. It states that log out action happens at one minute interval for each login.

To alleviate the above problem, I have deployed the application behind apache which maintains the session alive between apache and user session. 

Can I achieve this without deploying the web application behind apache server.

Best Regards,
Radhakrishnan Rk

**Comment by Abhijeet94** [comment]
The timeout can be changed by modifying LOGIN_TIMEOUT in /etc/login.defs
Reference: [link](https://unix.stackexchange.com/questions/340333/how-can-i-get-bin-login-to-not-timeout)

**Comment by Aakashshinde** [comment]
Can multiple users use it simultaneously?
