### ISSUE TITLE
jailing users

### ISSUE THREAD

**Issue by 7c** [butlerx/wetty#102]
Hi,

is there a way to jail a user in same other software which i will write to operate? So if user john logs in, i want that this users automatically starts the software node ./manage.js and when this user presses CTRL+c it should close the terminal.

This way i plan to make management consoles per user. 

I am aware of doing such things on linux by setting .bashrc etc but i am afraid of forgetting something so user can "break out of the jail". Any recommendations please?

**Comment by strugee** [comment]
You should set the user's login shell. Then you just have to worry about breakout problems in `manage.js`.

**Comment by rydens** [comment]
Not to take away from this project at all, (it's great!), but the ideas used in this one actually inspired [gotty](https://github.com/yudai/gotty), which can do exactly what you need, I think.

**Comment by butlerx** [comment]
you can use the `--command` flag to specify the command to run once logged in
