### ISSUE TITLE
Passing a command to start in wetty

### ISSUE THREAD

**Issue by erqiyang** [butlerx/wetty#103]
I was actually looking for a decent web terminal in telnet, but couldn't find one. I found wetty, and I think it's pretty good, so have been using it. The thing is, I still needed telnet. So my work around was to ssh into a host that telnets out to some other host.

I put the entire wetty in an iframe. Now, when users click on different links, I would like different wetty terminal to open with telnet session to respective host.

Is there a way to do this? I figured something like http://server/wetty/ssh/user is able to allow wetty to login as different user, but can i some how pass in a dynamically generated command so it will launch the command after logging in?

**Comment by Zibri** [comment]
No need for that.. just check app.js

Comment out these lines:

```
//        term = pty.spawn('ssh', [sshuser + sshhost, '-p', sshport, '-o', 'PreferredAuthentications=' + sshauth], {
//            name: 'xterm-256color',
//            cols: 80,
//            rows: 30
//        });

```
you can enter any command.. like:
(for a local shell)

```
        term = pty.spawn('sh', ['-i'], {
            name: 'xterm-256color',
            cols: 80,
            rows: 30
        });

```

**Comment by butlerx** [comment]
using the `--command` flag you can specify the command to run
