### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by dltssp** [butlerx/wetty#104]
trying to install wetty as it seems pretty straight forward. however, when I run sudo install npm I get an error. I saw a previous issue where you stated you have to run npm install node-gyp first (that was successul) then 'npm install pty.js' gives me the following issue.

It happens on my Fedora 25 machine and RHEL 7.2.

[student01@ip-10-0-0-150 wetty]$ sudo npm install pty.js

> pty.js@0.3.1 install /home/student01/wetty/node_modules/pty.js
> node-gyp rebuild

make: Entering directory `/home/student01/wetty/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: g++: Command not found
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 127
make: Leaving directory `/home/student01/wetty/node_modules/pty.js/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 3.10.0-327.10.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/student01/wetty/node_modules/pty.js
gyp ERR! node -v v6.12.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "pty.js"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/student01/wetty/npm-debug.log

**Comment by kotamahesh** [comment]
even am facing the same issue.is this know issue ?? please let me know for suggestions or alternative solutions ,

**Comment by koushikmln** [comment]
you could try npm install -g node-gyp

**Comment by lozbrown** [comment]
My NPM install fails too, very similar to the above 
I dont understand how root get permission denied on anything, its root


```
loz@gravity:~$ sudo -H npm install -g wetty
npm WARN deprecated connect@2.14.1: connect 2.x series is deprecated
npm WARN deprecated static-favicon@1.0.0: use serve-favicon module
/usr/local/bin/wetty -> /usr/local/lib/node_modules/wetty/bin/wetty.js

> pty.js@0.3.1 install /usr/local/lib/node_modules/wetty/node_modules/pty.js
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/wetty/node_modules/pty.js/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/wetty/node_modules/pty.js/.node-gyp'
gyp ERR! System Linux 4.15.0-39-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/wetty/node_modules/pty.js
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-26T20_18_27_171Z-debug.log
```

None of the following commands have helped:
```
sudo chown -R $USER:$GROUP ~/.npm
sudo chmod -R 0766 /usr/local/lib/node_modules/wetty
sudo chmod -R 0766 /home/loz/.node-gyp
sudo chmod -R 0766 ~/.npm
sudo apt-get install nodejs npm node-gyp nodejs-dev
```

**Comment by butlerx** [comment]
you shouldn't need to run npm install as root what do you get it if you run as the local user also, unfortunately, I don't have perms to update the npm packages.

**Comment by butlerx** [comment]
npm package has been deprecated in favor of `wetty.js`

**Comment by butlerx** [comment]
aswell the above issue was caused by pty.js which has been dropped in favour of node-pty fixing node compatibility issues

**Comment by JamesNewton** [comment]
> npm package has been deprecated in favor of wetty.js

Shouldn't that be mentioned in the readme?
