### ISSUE TITLE
Cannot set username with address bar

### ISSUE THREAD

**Issue by akastrin** [butlerx/wetty#106]
I installed Wetty Docker image and try to set the user with the URL `http://localhost/wetty/ssh/<username>` but the Wetty still responds with the prompt to enter username. However, when I try with regular version and run the Wetty using the command `node app.js -p 3000` the login through  address bar works.

Any idea what I'm doing wrong?

**Comment by koushikmln** [comment]
It has been fixed now. The docker image was running as root which was causing the feature to not work. You can make a pull request and use the feature now.
