### ISSUE TITLE
Does Wetty support ssh to other hosts? 

### ISSUE THREAD

**Issue by kunxia** [butlerx/wetty#107]
Is there any way we can ssh to other hosts without login to the localhost (where wetty runs on)?

**Comment by 4669842** [comment]
https://github.com/krishnasrinivas/wetty/blob/a24c55b76d998c1a29c1f753111563f0087385f5/app.js#L44

**Comment by kunxia** [comment]
Thanks but this variable only changes pre-defined host, is there an option to allow ssh to any host on the wetty frontend?

**Comment by 2sheds** [comment]
- You can always set up multiple instances of wetty (with nginx, docker or otherwise) - even create new ones programmatically
- As an ad-hoc alternative I just log into a default host and establish a new ssh connection wherever.

**Comment by butlerx** [comment]
you can specify the default host with the `--sshhost` flag running multip containers is probably the best approach
