### ISSUE TITLE
German umlauts and some Alt Gr problems

### ISSUE THREAD

**Issue by itn3rd77** [butlerx/wetty#11]
I am having problems with german umlauts (äöüÄÖÜ) in wetty and I am not sure if it's a problem upstream or related to wetty. I managed to get german umlauts displayed correct if I set the keyboard character endoding to raw in the JavaScript console: `term.keyboard.characterEncoding='raw'``

The second problem is related to Alt Gr key. I am unable to print a '@' sign. If I press `AltGr+Q` I am getting the follwing characters in the wetty console `^[`. I can copy & paste an '@' sign from an external editor as well as in wetty itself. So I doubt it an encoding problem or something.

Obviously  I am a german user, with a german keyboard layout :-)

Any ideas?

**Comment by krishnasrinivas** [comment]
I am not knowledgeable on international-keyboards. Can you check if this works as you expect:
https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo
This uses the same hterm(terminal emulator) used by wetty.

Also can you see if this helps:
https://code.google.com/p/chromium/issues/detail?id=211925

**Comment by itn3rd77** [comment]
Hi,

thanks for your reply. I have checked https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo and  german umlauts (äöüÄÖÜ)  work out of the box. The Alt Gr problem is the same as with wetty.

To sad. I think you can close the issue.

**Comment by krishnasrinivas** [comment]
Ah, ok then, so when it is fixed in hterm it should be fixed in wetty too.
