### ISSUE TITLE
This looks interesting (With Content)

### ISSUE THREAD

**Issue by PythonLinks** [butlerx/wetty#110]
I want to let my users connect to a docker container  shell in a web browser. 
The first thing they would do when they login is to change the password.
It would be helpful if you could document how to do that in the README file. 

Hope that helps. 
Chris

**Comment by toxic0berliner** [comment]
Leaving out the fact that accessing the shell in a container is a very bad idea...
Your request is out of scope for wetty, you're looking for some login scripts in whatever distro you chose for your container, plus whatever you want to persist changes upon container restart.
wetty is not there to manage your password and it's rules, it's here to give you ssh into your box. pwd management is donc by ssh-daemon and your underlying distro.

**Comment by butlerx** [comment]
using wetty in docker should only be done as a proxy to another server.
