### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by RupankarGhosh** [butlerx/wetty#112]
It starts well on android with chromium browser.But I cannot input anything in browser terminal because the keyboard doesn't showed up.

Can I use the android default keyboard in browser here?I am not planning to buy an external keyboard port for this app.

**Comment by hl2055** [comment]
I'm also looking into this. One possible way is to simulate a toggle-style keyboard.

**Comment by josefernandez91** [comment]
I join the order that has support in android, in the browsers the keyboard does not appear to be able to write. Would you have an implementation date with this change?
Excellent work tool

**Comment by kajer** [comment]
The version of hterm_all.js  is old.
between these two lines:
this.screen_.setAttribute('role', 'textbox');
this.screen_.setAttribute('tabindex', '-1');

add this:

this.screen_.setAttribute('contenteditable', '');

**Comment by josefernandez91** [comment]
Here is the solution, in the comments they passed a file that proves it and works perfect
https://github.com/krishnasrinivas/wetty/pull/49

**Comment by butlerx** [comment]
https://github.com/xtermjs/xterm.js/issues/1101  following xterm for supported sollution

**Comment by butlerx** [comment]
close in favour of #18
