### ISSUE TITLE
pty.js problem

### ISSUE THREAD

**Issue by DocterNope** [butlerx/wetty#119]
After trying to build, following the instructions exactly it fails.

root@Blue-Analyph:/mnt/c/Users/[removed]/Documents/winner/wetty# npm install

> pty.js@0.3.1 install /mnt/c/Users/[removed]/Documents/winner/wetty/node_modules/pty.js
> node-gyp rebuild

make: Entering directory '/mnt/c/Users/[removed]/Documents/winner/wetty/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../../nan/nan.h:190:0,
                 from ../src/unix/pty.cc:20:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:88:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
               ^
In file included from ../src/unix/pty.cc:20:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:817:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../../nan/nan.h:47:0,
                 from ../src/unix/pty.cc:20:
/home/[removed]/.node-gyp/10.1.0/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/[removed]/.node-gyp/10.1.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/unix/pty.cc:20:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:831:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../../nan/nan.h:47:0,
                 from ../src/unix/pty.cc:20:
/home/[removed]/.node-gyp/10.1.0/include/node/node.h:165:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/[removed]/.node-gyp/10.1.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/unix/pty.cc:20:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:845:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../../nan/nan.h:47:0,
                 from ../src/unix/pty.cc:20:
/home/[removed]/.node-gyp/10.1.0/include/node/node.h:158:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/[removed]/.node-gyp/10.1.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/unix/pty.cc:20:0:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../../nan/nan.h:1463:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../../nan/nan.h:47:0,
                 from ../src/unix/pty.cc:20:
/home/[removed]/.node-gyp/10.1.0/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/[removed]/.node-gyp/10.1.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyFork(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/unix/pty.cc:164:45: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   String::Utf8Value file(info[0]->ToString());
                                             ^
In file included from /home/[removed]/.node-gyp/10.1.0/include/node/v8.h:26:0,
                 from /home/[removed]/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../../nan/nan.h:47,
                 from ../src/unix/pty.cc:20:
/home/[removed]/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/[removed]/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/unix/pty.cc:175:71: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value arg(argv_->Get(Nan::New<Integer>(i))->ToString());
                                                                       ^
In file included from /home/[removed]/.node-gyp/10.1.0/include/node/v8.h:26:0,
                 from /home/[removed]/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../../nan/nan.h:47,
                 from ../src/unix/pty.cc:20:
/home/[removed]/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/[removed]/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/unix/pty.cc:186:71: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value pair(env_->Get(Nan::New<Integer>(i))->ToString());
                                                                       ^
In file included from /home/[removed]/.node-gyp/10.1.0/include/node/v8.h:26:0,
                 from /home/[removed]/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../../nan/nan.h:47,
                 from ../src/unix/pty.cc:20:
/home/[removed]/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/[removed]/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/unix/pty.cc:191:45: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   String::Utf8Value cwd_(info[3]->ToString());
                                             ^
In file included from /home/[removed]/.node-gyp/10.1.0/include/node/v8.h:26:0,
                 from /home/[removed]/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../../nan/nan.h:47,
                 from ../src/unix/pty.cc:20:
/home/[removed]/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/[removed]/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyGetProc(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/unix/pty.cc:371:45: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   String::Utf8Value tty_(info[1]->ToString());
                                             ^
In file included from /home/[removed]/.node-gyp/10.1.0/include/node/v8.h:26:0,
                 from /home/[removed]/.node-gyp/10.1.0/include/node/node.h:63,
                 from ../../nan/nan.h:47,
                 from ../src/unix/pty.cc:20:
/home/[removed]/.node-gyp/10.1.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/[removed]/.node-gyp/10.1.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyFork(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/unix/pty.cc:222:34: warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
       if (strlen(cwd)) chdir(cwd);
                                  ^
pty.target.mk:95: recipe for target 'Release/obj.target/pty/src/unix/pty.o' failed
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
make: Leaving directory '/mnt/c/Users/[removed]/Documents/winner/wetty/node_modules/pty.js/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Linux 4.4.0-43-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/c/Users/[removed]/Documents/winner/wetty/node_modules/pty.js
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/[removed]/.npm/_logs/2018-05-24T02_42_23_981Z-debug.log

**Comment by mdheller** [comment]
Another error along the same lines...

~/Public/socioprophet-master/wetty /// node app.js -p 3000                                                                                                 (05/28 22:49:58)
internal/modules/cjs/loader.js:573
    throw err;
    ^
Error: Cannot find module '../build/Release/pty.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/michaelheller/Public/socioprophet-master/wetty/node_modules/pty.js/lib/pty.js:9:11)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)

I found this thread: https://discuss.atom.io/t/solved-cannot-find-module-build-release-pty-node/46224/14

But, I haven't tried rolling back to python 2.7... anyone experienced this before that can advise if that's necessary or if there is a workaround for 3.6?

**Comment by mdheller** [comment]
Here is my npm list output:

wetty@0.2.0 /Users/michaelheller/Public/socioprophet-master/wetty
├─┬ express@3.5.1
│ ├── buffer-crc32@0.2.1
│ ├─┬ commander@1.3.2
│ │ └── keypress@0.1.0
│ ├─┬ connect@2.14.1
│ │ ├── basic-auth-connect@1.0.0
│ │ ├── bytes@0.2.1
│ │ ├─┬ compression@1.0.0
│ │ │ ├── bytes@0.2.1 deduped
│ │ │ ├── compressible@1.0.0
│ │ │ └── negotiator@0.3.0
│ │ ├─┬ connect-timeout@1.0.0
│ │ │ └── debug@0.8.1 deduped
│ │ ├─┬ cookie-parser@1.0.1
│ │ │ ├── cookie@0.1.0
│ │ │ └── cookie-signature@1.0.3 deduped
│ │ ├── cookie-signature@1.0.3 deduped
│ │ ├─┬ csurf@1.0.0
│ │ │ └── uid2@0.0.3
│ │ ├── debug@0.8.1 deduped
│ │ ├── errorhandler@1.0.0
│ │ ├─┬ express-session@1.0.2
│ │ │ ├── buffer-crc32@0.2.1 deduped
│ │ │ ├── cookie@0.1.0
│ │ │ ├── cookie-signature@1.0.3 deduped
│ │ │ ├── debug@0.7.4
│ │ │ ├── uid2@0.0.3 deduped
│ │ │ └── utils-merge@1.0.0
│ │ ├── fresh@0.2.2 deduped
│ │ ├─┬ method-override@1.0.0
│ │ │ └── methods@0.1.0 deduped
│ │ ├─┬ morgan@1.0.0
│ │ │ └── bytes@0.2.1 deduped
│ │ ├─┬ multiparty@2.2.0
│ │ │ ├─┬ readable-stream@1.1.14
│ │ │ │ ├── core-util-is@1.0.2
│ │ │ │ ├── inherits@2.0.3 deduped
│ │ │ │ ├── isarray@0.0.1 deduped
│ │ │ │ └── string_decoder@0.10.31
│ │ │ └─┬ stream-counter@0.2.0
│ │ │   └── readable-stream@1.1.14 deduped
│ │ ├── pause@0.0.1
│ │ ├── qs@0.6.6
│ │ ├─┬ raw-body@1.1.3
│ │ │ └── bytes@0.2.1 deduped
│ │ ├── response-time@1.0.0
│ │ ├─┬ serve-index@1.0.1
│ │ │ ├── batch@0.5.0
│ │ │ └── negotiator@0.4.2
│ │ ├─┬ serve-static@1.0.2
│ │ │ └── send@0.2.0 deduped
│ │ ├── static-favicon@1.0.0
│ │ └── vhost@1.0.0
│ ├── cookie@0.1.1
│ ├── cookie-signature@1.0.3
│ ├── debug@0.8.1
│ ├── fresh@0.2.2
│ ├── merge-descriptors@0.0.2
│ ├── methods@0.1.0
│ ├── mkdirp@0.3.5
│ ├── range-parser@1.0.0
│ └─┬ send@0.2.0
│   ├── debug@0.8.1 deduped
│   ├── fresh@0.2.2 deduped
│   ├── mime@1.2.11
│   └── range-parser@1.0.0 deduped
├─┬ grunt@0.4.5
│ ├── async@0.1.22
│ ├── coffee-script@1.3.3
│ ├── colors@0.6.2
│ ├── dateformat@1.0.2-1.2.3
│ ├── eventemitter2@0.4.14
│ ├── exit@0.1.2
│ ├─┬ findup-sync@0.1.3
│ │ ├─┬ glob@3.2.11
│ │ │ ├── inherits@2.0.3 deduped
│ │ │ └─┬ minimatch@0.3.0
│ │ │   ├── lru-cache@2.7.3 deduped
│ │ │   └── sigmund@1.0.1 deduped
│ │ └── lodash@2.4.2
│ ├── getobject@0.1.0
│ ├─┬ glob@3.1.21
│ │ ├── graceful-fs@1.2.3
│ │ ├── inherits@1.0.2
│ │ └── minimatch@0.2.14 deduped
│ ├─┬ grunt-legacy-log@0.1.3
│ │ ├── colors@0.6.2 deduped
│ │ ├─┬ grunt-legacy-log-utils@0.1.1
│ │ │ ├── colors@0.6.2 deduped
│ │ │ ├── lodash@2.4.2
│ │ │ └── underscore.string@2.3.3
│ │ ├── hooker@0.2.3 deduped
│ │ ├── lodash@2.4.2
│ │ └── underscore.string@2.3.3
│ ├─┬ grunt-legacy-util@0.2.0
│ │ ├── async@0.1.22 deduped
│ │ ├── exit@0.1.2 deduped
│ │ ├── getobject@0.1.0 deduped
│ │ ├── hooker@0.2.3 deduped
│ │ ├── lodash@0.9.2 deduped
│ │ ├── underscore.string@2.2.1 deduped
│ │ └── which@1.0.9 deduped
│ ├── hooker@0.2.3
│ ├── iconv-lite@0.2.11
│ ├─┬ js-yaml@2.0.5
│ │ ├─┬ argparse@0.1.16
│ │ │ ├── underscore@1.7.0 deduped
│ │ │ └── underscore.string@2.4.0
│ │ └── esprima@1.0.4
│ ├── lodash@0.9.2
│ ├─┬ minimatch@0.2.14
│ │ ├── lru-cache@2.7.3
│ │ └── sigmund@1.0.1
│ ├─┬ nopt@1.0.10
│ │ └── abbrev@1.1.1
│ ├── rimraf@2.2.8
│ ├── underscore.string@2.2.1
│ └── which@1.0.9
├─┬ grunt-contrib-clean@0.6.0
│ └── rimraf@2.2.8 deduped
├─┬ grunt-git@0.3.7
│ └─┬ flopmang@0.0.1
│   ├── underscore@1.7.0
│   └── underscore.string@2.4.0
├── grunt-mkdir@0.1.3
├─┬ grunt-shell@1.3.1
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.1.1
│ │ ├─┬ strip-ansi@3.0.1
│ │ │ └── ansi-regex@2.1.1 deduped
│ │ └── supports-color@2.0.0
│ ├─┬ npm-run-path@1.0.0
│ │ └── path-key@1.0.0
│ └── object-assign@4.1.0
├─┬ load-grunt-tasks@3.5.2
│ ├── arrify@1.0.1
│ ├─┬ multimatch@2.1.0
│ │ ├── array-differ@1.0.0
│ │ ├─┬ array-union@1.0.2
│ │ │ └── array-uniq@1.0.3
│ │ ├── arrify@1.0.1 deduped
│ │ └─┬ minimatch@3.0.4
│ │   └── brace-expansion@1.1.11 deduped
│ ├─┬ pkg-up@1.0.0
│ │ └─┬ find-up@1.1.2
│ │   ├─┬ path-exists@2.1.0
│ │   │ └── pinkie-promise@2.0.1 deduped
│ │   └─┬ pinkie-promise@2.0.1
│ │     └── pinkie@2.0.4
│ └─┬ resolve-pkg@0.1.0
│   └── resolve-from@2.0.0
├─┬ node-gyp@3.6.2
│ ├─┬ fstream@1.0.11
│ │ ├── graceful-fs@4.1.11
│ │ ├── inherits@2.0.3
│ │ ├─┬ mkdirp@0.5.1
│ │ │ └── minimist@0.0.8
│ │ └── rimraf@2.2.8 deduped
│ ├─┬ glob@7.1.2
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.6
│ │ │ ├── once@1.4.0 deduped
│ │ │ └── wrappy@1.0.2
│ │ ├── inherits@2.0.3 deduped
│ │ ├── minimatch@3.0.4 deduped
│ │ ├─┬ once@1.4.0
│ │ │ └── wrappy@1.0.2 deduped
│ │ └── path-is-absolute@1.0.1
│ ├── graceful-fs@4.1.11
│ ├─┬ minimatch@3.0.4
│ │ └─┬ brace-expansion@1.1.11
│ │   ├── balanced-match@1.0.0
│ │   └── concat-map@0.0.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ nopt@3.0.6
│ │ └── abbrev@1.1.1 deduped
│ ├─┬ npmlog@4.1.2
│ │ ├─┬ are-we-there-yet@1.1.5
│ │ │ ├── delegates@1.0.0
│ │ │ └─┬ readable-stream@2.3.6
│ │ │   ├── core-util-is@1.0.2 deduped
│ │ │   ├── inherits@2.0.3 deduped
│ │ │   ├── isarray@1.0.0
│ │ │   ├── process-nextick-args@2.0.0
│ │ │   ├── safe-buffer@5.1.2 deduped
│ │ │   ├─┬ string_decoder@1.1.1
│ │ │   │ └── safe-buffer@5.1.2 deduped
│ │ │   └── util-deprecate@1.0.2
│ │ ├── console-control-strings@1.1.0
│ │ ├─┬ gauge@2.7.4
│ │ │ ├── aproba@1.2.0
│ │ │ ├── console-control-strings@1.1.0 deduped
│ │ │ ├── has-unicode@2.0.1
│ │ │ ├── object-assign@4.1.0 deduped
│ │ │ ├── signal-exit@3.0.2
│ │ │ ├─┬ string-width@1.0.2
│ │ │ │ ├── code-point-at@1.1.0
│ │ │ │ ├─┬ is-fullwidth-code-point@1.0.0
│ │ │ │ │ └── number-is-nan@1.0.1
│ │ │ │ └── strip-ansi@3.0.1 deduped
│ │ │ ├── strip-ansi@3.0.1 deduped
│ │ │ └─┬ wide-align@1.1.3
│ │ │   └── string-width@1.0.2 deduped
│ │ └── set-blocking@2.0.0
│ ├─┬ osenv@0.1.5
│ │ ├── os-homedir@1.0.2
│ │ └── os-tmpdir@1.0.2
│ ├─┬ request@2.87.0
│ │ ├── aws-sign2@0.7.0
│ │ ├── aws4@1.7.0
│ │ ├── caseless@0.12.0
│ │ ├─┬ combined-stream@1.0.6
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.1
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@2.3.2
│ │ │ ├── asynckit@0.4.0
│ │ │ ├── combined-stream@1.0.6 deduped
│ │ │ └── mime-types@2.1.18 deduped
│ │ ├─┬ har-validator@5.0.3
│ │ │ ├─┬ ajv@5.5.2
│ │ │ │ ├── co@4.6.0
│ │ │ │ ├── fast-deep-equal@1.1.0
│ │ │ │ ├── fast-json-stable-stringify@2.0.0
│ │ │ │ └── json-schema-traverse@0.3.1
│ │ │ └── har-schema@2.0.0
│ │ ├─┬ http-signature@1.2.0
│ │ │ ├── assert-plus@1.0.0
│ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ ├── assert-plus@1.0.0 deduped
│ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ ├── json-schema@0.2.3
│ │ │ │ └─┬ verror@1.10.0
│ │ │ │   ├── assert-plus@1.0.0 deduped
│ │ │ │   ├── core-util-is@1.0.2 deduped
│ │ │ │   └── extsprintf@1.3.0 deduped
│ │ │ └─┬ sshpk@1.14.1
│ │ │   ├── asn1@0.2.3
│ │ │   ├── assert-plus@1.0.0 deduped
│ │ │   ├─┬ bcrypt-pbkdf@1.0.1
│ │ │   │ └── tweetnacl@0.14.5 deduped
│ │ │   ├─┬ dashdash@1.14.1
│ │ │   │ └── assert-plus@1.0.0 deduped
│ │ │   ├─┬ ecc-jsbn@0.1.1
│ │ │   │ └── jsbn@0.1.1 deduped
│ │ │   ├─┬ getpass@0.1.7
│ │ │   │ └── assert-plus@1.0.0 deduped
│ │ │   ├── jsbn@0.1.1
│ │ │   └── tweetnacl@0.14.5
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.1.18
│ │ │ └── mime-db@1.33.0
│ │ ├── oauth-sign@0.8.2
│ │ ├── performance-now@2.1.0
│ │ ├── qs@6.5.2
│ │ ├── safe-buffer@5.1.2
│ │ ├─┬ tough-cookie@2.3.4
│ │ │ └── punycode@1.4.1
│ │ ├─┬ tunnel-agent@0.6.0
│ │ │ └── safe-buffer@5.1.2 deduped
│ │ └── uuid@3.2.1
│ ├── rimraf@2.2.8 deduped
│ ├── semver@5.3.0
│ ├─┬ tar@2.2.1
│ │ ├─┬ block-stream@0.0.9
│ │ │ └── inherits@2.0.3 deduped
│ │ ├── fstream@1.0.11 deduped
│ │ └── inherits@2.0.3 deduped
│ └── which@1.0.9 deduped
├─┬ optimist@0.6.1
│ ├── minimist@0.0.10
│ └── wordwrap@0.0.3
├─┬ pty@0.0.0
│ └── pty.js@0.3.1 deduped
├─┬ pty.js@0.3.1
│ ├── extend@1.2.1
│ ├── nan@2.3.5
│ └── node-gyp@3.6.2 deduped
├─┬ rebuild@0.1.2
│ └─┬ optimist@0.3.7
│   └── wordwrap@0.0.3 deduped
├─┬ runner@1.0.4
│ └── optimist@0.6.1 deduped
├─┬ script@0.1.4
│ ├─┬ http-browserify@0.1.2
│ │ └── concat-stream@0.0.8
│ ├── merge@1.0.0
│ ├─┬ optimist@0.3.4
│ │ └── wordwrap@0.0.3 deduped
│ ├── process@0.5.0
│ └─┬ required@0.0.8
│   └─┬ detective@0.3.0-dz0 (git://github.com/shtylman/node-detective.git#06d5cb4534818860b5a7f8d0a321dc7ae86d8e74)
│     ├─┬ escodegen@0.0.15
│     │ ├── esprima@1.0.4 deduped
│     │ └── source-map@0.7.3
│     └── esprima@1.0.2
├─┬ socket.io@1.7.4
│ ├─┬ debug@2.3.3
│ │ └── ms@0.7.2
│ ├─┬ engine.io@1.8.5
│ │ ├─┬ accepts@1.3.3
│ │ │ ├── mime-types@2.1.18 deduped
│ │ │ └── negotiator@0.6.1
│ │ ├── base64id@1.0.0
│ │ ├── cookie@0.3.1
│ │ ├─┬ debug@2.3.3
│ │ │ └── ms@0.7.2 deduped
│ │ ├─┬ engine.io-parser@1.3.2
│ │ │ ├── after@0.8.2
│ │ │ ├── arraybuffer.slice@0.0.6
│ │ │ ├── base64-arraybuffer@0.1.5
│ │ │ ├── blob@0.0.4
│ │ │ ├── has-binary@0.1.7 deduped
│ │ │ └── wtf-8@1.0.0
│ │ └─┬ ws@1.1.5
│ │   ├── options@0.0.6
│ │   └── ultron@1.0.2
│ ├─┬ has-binary@0.1.7
│ │ └── isarray@0.0.1
│ ├── object-assign@4.1.0 deduped
│ ├─┬ socket.io-adapter@0.5.0
│ │ ├─┬ debug@2.3.3
│ │ │ └── ms@0.7.2 deduped
│ │ └── socket.io-parser@2.3.1 deduped
│ ├─┬ socket.io-client@1.7.4
│ │ ├── backo2@1.0.2
│ │ ├── component-bind@1.0.0
│ │ ├── component-emitter@1.2.1
│ │ ├─┬ debug@2.3.3
│ │ │ └── ms@0.7.2 deduped
│ │ ├─┬ engine.io-client@1.8.5
│ │ │ ├── component-emitter@1.2.1
│ │ │ ├── component-inherit@0.0.3
│ │ │ ├─┬ debug@2.3.3
│ │ │ │ └── ms@0.7.2 deduped
│ │ │ ├── engine.io-parser@1.3.2 deduped
│ │ │ ├── has-cors@1.1.0
│ │ │ ├── indexof@0.0.1 deduped
│ │ │ ├─┬ parsejson@0.0.3
│ │ │ │ └── better-assert@1.0.2 deduped
│ │ │ ├─┬ parseqs@0.0.5
│ │ │ │ └── better-assert@1.0.2 deduped
│ │ │ ├── parseuri@0.0.5 deduped
│ │ │ ├── ws@1.1.5 deduped
│ │ │ ├── xmlhttprequest-ssl@1.5.3
│ │ │ └── yeast@0.1.2
│ │ ├── has-binary@0.1.7 deduped
│ │ ├── indexof@0.0.1
│ │ ├── object-component@0.0.3
│ │ ├─┬ parseuri@0.0.5
│ │ │ └─┬ better-assert@1.0.2
│ │ │   └── callsite@1.0.0
│ │ ├── socket.io-parser@2.3.1 deduped
│ │ └── to-array@0.1.4
│ └─┬ socket.io-parser@2.3.1
│   ├── component-emitter@1.1.2
│   ├─┬ debug@2.2.0
│   │ └── ms@0.7.1
│   ├── isarray@0.0.1 deduped
│   └── json3@3.3.2
└── tty@1.0.1

thanks!

**Comment by codeharmonist** [comment]
wetty depends on pty.js which depends on a deprecated version of nan.
I have worked around the problem using nvm and installing node 8.11.2.

**Comment by vijmeister** [comment]
I am trying with nvm-windows and node 8.11.2 but I am not having any luck with python 3.6

**Comment by mdheller** [comment]
This hasn't moved along much @krishnasrinivas can we set up some time to walk through this and push a solution to the community? I can ask a few geeks to join us on the call / webex / skype or whatever it takes; but, I'd like to try to work with you to solve this issue. I love this project and it's really a great piece of software for the global geek community. I'd like to see this project succeed and I'd like to help make sure it's a reliable app. Please let me know how we can work together to come to a worthwhile and documentable solution to these issues. I am willing to put in the time with you, and I am willing to ask other geeks to help if necessary. What is the best next step to working through this?

**Comment by Apollon77** [comment]
It seems to me that pty.js is no longer really maintained  ... but node-pty seems to be an actively maninatned fork ... maybe just switch to node-pty?!

**Comment by mdheller** [comment]
I will push the changes to my fork

**Comment by vissieGP** [comment]
Thx for this. I'm really having issues installing node-pty. Can someone point me in the right directions pls?

Vissie

**Comment by vissieGP** [comment]
OK, if anyone wants to know how to, I eventually figured this out.....
update wetty source to use node-pty as per issue 119#124.
clone https://github.com/Microsoft/node-pty into wetty/node_modules
sudo npm install

That worked for me.

Vissie

**Comment by butlerx** [comment]
wetty has been upgraded

**Comment by Apollon77** [comment]
@butlerx Is there an error? When I install wetty.js@0.5.1 then I still have pty.js (node 10 incompatible) as dep. Did I missed something?
