### ISSUE TITLE
Wetty crashes silently when one of multiple browser windows is closed

### ISSUE THREAD

**Issue by thoschaefer** [butlerx/wetty#12]
Hi,

I am running wetty inside of a docker container. When I open multiple browser windows and close one of them, then wetty will hang. The node processs is still running but none of the terminal windows is responding anymore.

Steps to reproduce:

Open wetty on first computer, log in, do a "watch date".
Open wetty with another chrome browser on another computer. Close the tab without loging in. Or log in and then press STRG+D.

The watch date in the first window will stop after a few seconds. No new connections are possible anymore until the docker container is restarted,

Hope you can reproduce and fix this. Because Wetty seems like a really cool solution.

Kind regards,

Thorsten

**Comment by krishnasrinivas** [comment]
Will check it soon.

**Comment by krishnasrinivas** [comment]
I suspect it might be fixed with this PR https://github.com/krishnasrinivas/wetty/pull/13
Can you confirm?
