### ISSUE TITLE
bin/ssh wrapper doesn't pass through sshport or PreferredAuthentications

### ISSUE THREAD

**Issue by Codelica** [butlerx/wetty#127]
The bin/ssh wrapper here:

https://github.com/krishnasrinivas/wetty/blob/master/bin/ssh

Does nothing with the ssh options like sshport and PreferredAuthentications which are passed in here:

https://github.com/krishnasrinivas/wetty/blob/master/wetty.mjs#L49

**Comment by butlerx** [comment]
Closed by #132
