### ISSUE TITLE
gyp and npm errors ?

### ISSUE THREAD

**Issue by PS6** [butlerx/wetty#133]
I like wetty, and wanted to create  a script (on centos 7.x)
after epel install than nodejs and npm install
then running
npm install -g wetty
I get  
npm WARN deprecated connect@2.14.1: connect 2.x series is deprecated
npm WARN deprecated static-favicon@1.0.0: use serve-favicon module
/usr/bin/wetty -> /usr/lib/node_modules/wetty/bin/wetty.js
> pty.js@0.3.1 install /usr/lib/node_modules/wetty/node_modules/pty.js
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.14.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/wetty/node_modules/pty.js/.node-gyp"
make: Entering directory `/usr/lib/node_modules/wetty/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: g++: Command not found
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:276:23)
make: Leaving directory `/usr/lib/node_modules/wetty/node_modules/pty.js/build'
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 3.10.0-862.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/wetty/node_modules/pty.js
gyp ERR! node -v v6.14.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
/usr/lib
npm ERR! Linux 3.10.0-862.el7.x86_64
+-- (empty)

npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "-g" "wetty"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1

**Comment by ahaya1985** [comment]
you can try 2 step below
1. npm install -g node-gyp
2. apt-get install nodejs-legacy
then try to run npm install pty.js -g

**Comment by butlerx** [comment]
pty.js is no longer used in favor of node-pty issue should no longer continue
