### ISSUE TITLE
Unable to copy in OS X

### ISSUE THREAD

**Issue by ghost** [butlerx/wetty#14]
I am unable to copy text from wetty under OS X. I can paste just fine and I see the scissors pop up when I hit COMMAND-C

**Comment by krishnasrinivas** [comment]
It works for me. Can you debug at hterm.js: hterm.Terminal.prototype.onCopy_() by putting console.log statements and see if the function gets called when you do cmd-C?

**Comment by ghost** [comment]
Yep it gets called but the selected data doesn't get into the clipboard.

**Comment by ghost** [comment]
D'oh. I followed a recipe to create the container and it was reseting the checkout back before you made a change to that onCopy_ function(the setdefault) I removed the reset and now it works swimmingly. Thanks for your help
