### ISSUE TITLE
Exit the ssh session cleanly on browser close

### ISSUE THREAD

**Issue by koushikmln** [butlerx/wetty#141]
Can we add functionality to cleanly exit the ssh session when the browser is closed?

**Comment by 2sheds** [comment]
If you mean the zombies, take a look at #136 and #137

**Comment by koushikmln** [comment]
The active ssh session does not close when we directly close the browser. I want to implement a max concurrent connections functionality per user. The sessions which are closed directly stay alive and the connections are maxing out. Looking for ideas for fixes for the issue.
