### ISSUE TITLE
SSL key & cert are not loaded

### ISSUE THREAD

**Issue by 2sheds** [butlerx/wetty#144]
I'm trying to start WeTTY container in HTTPS mode but files provided with `--sslkey` & `--sslcert` options are not loaded. During debugging I see that the key file is read and added to respective property of `ssl` object but the next `readFile` for cert comes up empty. I can make it succed by moving the next `.then` inside the parenthesis but `ssl` is still resolved empty despite holding both `key` and `cert` properties in the previous step.

**Comment by butlerx** [comment]
can you confirm if the current master fixes this issue?

**Comment by 2sheds** [comment]
Checked, current master worked fine
