### ISSUE TITLE
Several issues with Systemd install

### ISSUE THREAD

**Issue by lozbrown** [butlerx/wetty#147]
There seems to be a few issues with the systemd install instructions

1. Ubuntu comes with something called cmdtest but that gets automatically installed as yarn, if you run the commands in the readme with that yarn they will just fail, its necesary to follow the iinstructions here to get the correct yarn:
 https://yarnpkg.com/lang/en/docs/install/#debian-stable

2. after doing that and installing the following directtory does not exist
~/.config/yarn/global/node_modules/wetty.js/bin/
but the following does
~/.config/yarn/global/node_modules/wetty/bin
but contains only wetty.conf and wetty.js, no systemd service

Are these becuase the packages installed are out of date? 
Could you include install from github instructions

**Comment by butlerx** [comment]
could I get some more info? how are you installing the package and whats the version number?

**Comment by lozbrown** [comment]
Hi

I think I originally installed it via yarn and it installled 0.2.0 but i have now installed from source and can find the files mentioned

**Comment by butlerx** [comment]
it looks like you installed wetty from npm while the npm package name is wetty.js
