### ISSUE TITLE
autologin not working

### ISSUE THREAD

**Issue by ClaytonXia** [butlerx/wetty#148]
Hi,

i installed wetty on ubuntu16.04 and have sshpass installed to support autologin, but when i start as  `wetty -p 3000`, the autologin feature in README doesn't work, it treats the sshpass query param as the login username .
in browser i typed 'http://127.0.0.1:3000/wetty/ssh/xiakai?sshpass=python3', the server log says `Fri Dec 07 2018 17:13:13 GMT+0800 (CST) PID=27259 STARTED on behalf of user=xiakai?sshpass=python3@`.

thanks

**Comment by koushikmln** [comment]
Could you try cloning the repo and then run it using the `npm start` command? I'm not sure if the npm repo is updated. Additionally, you would also need sshpass installed on the system.

**Comment by ClaytonXia** [comment]
@koushikmln 
Hi, thanks a lot for your advice. It works perfect. Thank you
