### ISSUE TITLE
Specify default path in URL

### ISSUE THREAD

**Issue by abubakar-bilal** [butlerx/wetty#152]
Hey @koushikmln  @krishnasrinivas 

I finally made it to run this awesome web terminal. Just a quick question to ask as per my need. I need to pass a default path in url so that when terminal starts in browser it should be on that path. Let's say something like this

`http://abc.com/ssh/abubakar?sshpass=password&path=/var/www/abc`

So it should be on this path when terminal starts. Thanks in advance.

**Comment by butlerx** [comment]
Interesting feature request. Should be possible, will need to verify some different env but :+1:

**Comment by abubakar-bilal** [comment]
@butlerx Thank you for quick response. Can I expect this in few days? Because I need to use this in my application.

**Comment by butlerx** [comment]
Currently I'm afk for a few days. But if someone else wants to try their hand they are more then welcome. My initial thoughts would be to pass `cd` with the path variable through to the ssh and login command.
Both commands need to be tested also possibly some thought abiut ensuring a path string is sent rather then another command

**Comment by abubakar-bilal** [comment]
@koushikmln Are you available to work on this feature and make a PR? I would be really grateful to you.

**Comment by abubakar-bilal** [comment]
@butlerx @koushikmln  I was just checking issues in this repo and I found this PR https://github.com/krishnasrinivas/wetty/pull/37 which is to enable optional command. I just need to ask how to use that because https://github.com/krishnasrinivas/wetty master branch doesn't have any app.js where I can add optional command parameter.

Please guide me on this.

**Comment by koushikmln** [comment]
The PR has to be rebased to master. It was on the older version. That is a little unstable compared to the current one. I will try and add the feature or rebase the optional command code to the current master this week or so.

**Comment by abubakar-bilal** [comment]
Actually I was using web-terminal previously and now I'm trying to replace that with wetty. Which is awesome in functionality and features. So in web-terminal I placed this code in index.html which was working for me to by default cd to a path
```
<script type="text/javascript">
      document.onreadystatechange = function(){
        if(document.readyState === 'complete'){
          console.log( "ready!" );
          window.setTimeout(function(){
            alert(window.location.href.match(/\&path=(.*)/)[1]);
            window.exec("cd "+window.location.href.match(/\&path=(.*)/)[1], function(stdout){console.log(stdout)});
          }, 500);
        }
      }
    </script>```

So now I need to replace this line `window.exec("cd "+window.location.href.match(/\&path=(.*)/)[1], function(stdout){console.log(stdout)});` with wetty line of code to run a cd command when terminal gets loaded.

Please guide if it's possible in wetty current latest code.

**Comment by abubakar-bilal** [comment]
hey @koushikmln any luck to find sometime to rebase optional path parameter into master branch. So that I can pass path parameter in url to set a default path on initiazalization.

**Comment by koushikmln** [comment]
@abubakar-bilal do you need the path to be dynamic or is it good enough if you set it as application config?

**Comment by abubakar-bilal** [comment]
@koushikmln It needs to be dynamic. Sent in url.

**Comment by abubakar-bilal** [comment]
@butlerx Thanks so much. It really worked for me and helped me alot. 👍
