### ISSUE TITLE
Session based access to a user

### ISSUE THREAD

**Issue by abubakar-bilal** [butlerx/wetty#154]
I want something like we don't want to have password in url because that's not secure at all. I want something like I pass a hashed session key and with that key I can directly access terminal. And that key is expired let's say after 2 hours and then we'll pass another key. 

I hope you understand my intention. if you can any other better solution for that. I can go for that too. Eagerly watiting for your response.

CC: @koushikmln @butlerx @krishnasrinivas

**Comment by butlerx** [comment]
You are not required to pass the password through the url a user should be prompted to type login and password on page load.
currently, there are no plans to do a timed session in wetty. a better approach may be to set users shell to expire after `x` minutes on the machine itself.
