### ISSUE TITLE
Making wetty as globally accessible

### ISSUE THREAD

**Issue by plato79** [butlerx/wetty#156]
I think there's something wrong in my system because after I install wetty globally with yarn or npm, when I try to run it, it gives these errors:
```
/usr/local/bin/wetty: /COPYRIGHT: Permission denied
/usr/local/bin/wetty: 3: Syntax error: "(" unexpected
```

When I run it from the directory where wetty is with `node index.js` there is no problem..

What could be the problem?

**Comment by butlerx** [comment]
can i get a bit more info?

* what command did you use to install it globally?
* Was it installed as root?
* what version of node are you using?

**Comment by plato79** [comment]
I used both `yarn -g add wetty.js` and `npm i -g wetty.js`. The result is the same.

Well, first I installed as root, though I also tried with local user ( making the owner of the node_modules and /usr/local/bin directory to my user ). The result is the same with both ways.

I'm using v11.6.0 of node.

**Comment by butlerx** [comment]
confirmed i was able to replicate locally

**Comment by butlerx** [comment]
issue appears to be two fold one its missing its `#!` and then the relative import seems to not work correctly

**Comment by butlerx** [comment]
second issue is related to the issues outlined in #157

**Comment by butlerx** [comment]
ok seems to be a webpack issue fix in coming

**Comment by butlerx** [comment]
the issue should be fixed in v1.1.3

**Comment by plato79** [comment]
Hmm.. weird.. Now, it's working as you said.. I could also access it with `http://x.x.x.x:3000/wetty`..

But now there is another problem came up.. Before I was using nginx with forwarding to access wetty.

Here is my configuration:
```
  server {
    listen 443 ssl;
    server_name tty.mydomain.com; 
    include ssl-params.conf;
    location / {
      proxy_pass http://127.0.0.1:3000/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 43200000;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header X-NginX-Proxy true;
    }

  }
```

Before this was working without problem like this:

`https://tty.mydomain.com/`

Now, it gives this error:

```
{"message":"127.0.0.1 - - [13/Jan/2019:15:16:16 +0000] \"GET / HTTP/1.1\" 404 139 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\"\n","level":"info"}
```

Chrome only shows "GET /" as output.


If I change the nginx configuration like this:

`      proxy_pass http://127.0.0.1:3000/wetty;`

Then there is another problem:
```
{"message":"127.0.0.1 - - [13/Jan/2019:15:26:20 +0000] \"GET /wetty HTTP/1.1\" 304 - \"https://tty.mydomain.com/\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\"\n","level":"info"}
{"message":"127.0.0.1 - - [13/Jan/2019:15:26:20 +0000] \"GET /wettywetty/public/index.css HTTP/1.1\" 404 166 \"https://tty.mydomain.com/\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\"\n","level":"info"}
{"message":"127.0.0.1 - - [13/Jan/2019:15:26:20 +0000] \"GET /wettywetty/public/index.js HTTP/1.1\" 404 165 \"https://tty.mydomain.com/\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\"\n","level":"info"}
```

Chrome only displays a reconnect button this way. I could see the problem here.. It forwards to /wetty than requests wetty/public/index.css etc.. but it should be {host}/public/index.css..

The problem is before it was forwarding to /wetty automatically I think. Now I need to add /wetty to the link like this: `https://tty.mydomain.com/wetty` with the first configuration. What's changed?

**Comment by butlerx** [comment]
Ah yes, as of https://github.com/krishnasrinivas/wetty/commit/00355a4591fc932aafc61c3ef4c0ee9f8a35bdaa to allow users specifying the path useing `--base` the duplicate paths where removed. can you try runnign with the the arguements `--base /`

**Comment by plato79** [comment]
Hmm.. At first I thought it would work but now I see another problem..

When I use `-b /` as parameter, this time wetty tries to find the files where it's executed from.. For example if I run it when I'm in `/usr/local/etc` directory, it searches files from that directory like this:

```
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module '/usr/local/etc/dist/buffer.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]
```

This is the output on the web page. To get this screen shot I had to use an ad blocker to  remove the overlay and error scripts.

BTW, I'm executing it like this:

`test@freebsd:/usr/local/etc$ wetty -b /`

Here is the output from command line:

```
{"message":"http on port 3000","level":"info"}
{"message":"Sun Jan 13 2019 23:05:29 GMT+0300 (GMT+03:00) Connection accepted.","level":"info"}
{"message":"PID=36640 STARTED on behalf of @localhost","level":"info"}
{"message":"Exit with code: 255 PID=36640 ENDED","level":"info"}
{"message":"127.0.0.1 - - [13/Jan/2019:20:05:34 +0000] \"GET / HTTP/1.1\" 304 - \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\"\n","level":"info"}
{"message":"127.0.0.1 - - [13/Jan/2019:20:05:34 +0000] \"GET /public/index.css HTTP/1.1\" 304 - \"https://my.domain.com/\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\"\n","level":"info"}
{"message":"127.0.0.1 - - [13/Jan/2019:20:05:34 +0000] \"GET /public/index.js HTTP/1.1\" 304 - \"https://my.domain.com/\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\"\n","level":"info"}
{"message":"Sun Jan 13 2019 23:05:34 GMT+0300 (GMT+03:00) Connection accepted.","level":"info"}
{"message":"PID=36643 STARTED on behalf of @localhost","level":"info"}
{"message":"Exit with code: 255 PID=36643 ENDED","level":"info"}
```

**Comment by butlerx** [comment]
yep you caught another issue there mind trying v1.1.4

**Comment by plato79** [comment]
Finally it's working as intended.. I think we could close this now.. I'll try to work on FreeBSD service now.
