### ISSUE TITLE
SSHPORT env variable not working in docker

### ISSUE THREAD

**Issue by hot22shot** [butlerx/wetty#158]
Hello,

I'm trying to use the SSHPORT environment variable to log on my server as it is not using the 22 port.
I can use SSHHOST to specify the host IP adress but the SSHPORT does not seem to work.

```
Tue Jan 15 2019 09:55:04 GMT+0000 (UTC) PID=49 STARTED on behalf of remote=192.168.1.46
Tue Jan 15 2019 09:55:06 GMT+0000 (UTC) Connection accepted.
{ args: 
   [ '/app/bin/ssh',
     '192.168.1.46',
     '-t',
     '-p',
     22,
     '-o',
     'PreferredAuthentications=password,keyboard-interactive',
     '' ],
  ssh: '192.168.1.46' }
Tue Jan 15 2019 09:55:06 GMT+0000 (UTC) PID=57 STARTED on behalf of remote=192.168.1.46
```
I have set up 2 environment variables :
SSHPORT=1978
SSHHOST=192.168.1.46

Could use some help !

Regards

**Comment by hot22shot** [comment]
Don't know as I'm using this docker : https://hub.docker.com/r/krishnasrinivas/wetty/
I'm using the docker environment variables as documented here :

> In the docker version all flags can be accessed as environment variables such as SSHHOST or SSHPORT.

**Comment by butlerx** [comment]
Ah yes that container is not up to date. sorry will look into getting it updated

**Comment by hot22shot** [comment]
Thank you !

**Comment by digitalkram** [comment]
same here. workaround until issue is fixed in the image:
```
docker cp term:/app/cli.mjs .
sed -i 's/SSHPOST/SSHPORT/g' cli.mjs
docker cp cli.mjs term:/app/cli.mjs
rm -f cli.mjs
```

**Comment by butlerx** [comment]
Until I've got a responce from the owner of the docker you can also. Use butlerx/wetty on docker

**Comment by butlerx** [comment]
`butlerx/wetty` is now the official docker image

**Comment by hot22shot** [comment]
Thanks. 

I migrated my docker image from `krishnasrinivas/wetty` to `butlerx/wetty` and it works (including `SSHPORT`).
