### ISSUE TITLE
Forward and set environment variable

### ISSUE THREAD

**Issue by Magicking** [butlerx/wetty#159]
It would be nice to have the possibility to enrich the environment with information like Remote IP / Headers / Port / URI args ...
One way could be with variable environments with the spawned process.

**Comment by butlerx** [comment]
setting the env_variables is a good idea. would be interested to get input on variables to set. 

- Source IP
- Server uri and port
- wetty version
- SSL?

**Comment by jap1968** [comment]
I am very interested in this feature, too.
