### ISSUE TITLE
Getting wetty to work on an Electron shell

### ISSUE THREAD

**Issue by SantoshSrinivas79** [butlerx/wetty#16]
@krishnasrinivas , I am trying to use wetty to work from an electron shell. `hterm` is dependent on chrome. are there any alternatives that I could use to make it browser independent?

**Comment by krishnasrinivas** [comment]
you can use https://github.com/rabchev/wetty till those changes are merged in. I have not yet taken those changes in as copy/paste does not work there yet.

**Comment by SantoshSrinivas79** [comment]
Thank you. Works like magic! :-)
