### ISSUE TITLE
Unmaintained dependency: pty.js

### ISSUE THREAD

**Issue by LaKing** [butlerx/wetty#165]
npm install wetty fails due to pty.js

Could we switch the dependency of pty.js to an alternative, a maintained one?

How about [https://github.com/Microsoft/node-pty](https://github.com/Microsoft/node-pty) for example?

**Comment by LaKing** [comment]
I just noticed, that node-pty is already in the dependencies for the wetty package.json on the git repo.

So it seems that the wetty npm is behind?

**Comment by butlerx** [comment]
this it mixed in recent npm packages
