### ISSUE TITLE
Adding wetty to an express application

### ISSUE THREAD

**Issue by LaKing** [butlerx/wetty#166]
In previous versions of wetty, it was relative easy to add wetty to an existing express application. 
With this new version built with typescript and webpack this seems to be much harder.

I wonder if it would be possible to implement a way to simply require wetty in an express application, or use it as middleware. The index.js file seems to hint that this should be possible, but I cant find any documentation and could not yet figure out how ..

```javascript 
/**
 * Check if being run by cli or require
 */
if (require.main === module) { ... } // run by cli

// no else or any other code?
```

**Comment by butlerx** [comment]
currently wetty doesn't support being used in express but does support being called from node. to support being a middleware, wettys html render will need to be exported as a middleware. then the express server would need to be wrapped in socket.io and the following handler added https://github.com/butlerx/wetty/blob/master/src/server/wetty.ts#L46 would need to be
