### ISSUE TITLE
Wetty slowdown

### ISSUE THREAD

**Issue by LaKing** [butlerx/wetty#167]
With the new typescipt-webpack config, my wetty instance running a midnight commander is reacting really slow.
The terminal opens mc fine, no error messages, but then navigating between files and folders is significantly slower than on previous versions of wetty. 

Unfortunately, I have no tools or know-how for debugging this issue, but if there is anything I can do, please let me know ... 

... this seems to be the show-stopper for now :(

**Comment by sonofwatt** [comment]
I'm running the latest version of WeTTY and it's often VERY slow for me. I'm connected via LAN, and for example, a simple 'smartctl -h' command takes 5+ seconds to display the output. 
There are times when WeTTy is more responsive, but most of the time it's slow. 
This is running in Docker via OMV, on an HP server, with 3% CPU and 6% RAM usage.
