### ISSUE TITLE
How is index.html that contains <div id="terminal"></div> created?

### ISSUE THREAD

**Issue by lrich** [butlerx/wetty#169]
Is the index.html file that contains the 'div id=terminal' auto-created? 
I can't seem to find the location of the index.html, or determine if it is auto-created in the javascript, as I'd like to customize the page.

Thanks!

**Comment by butlerx** [comment]
It's created in js here https://github.com/krishnasrinivas/wetty/blob/master/src/server/server.ts

**Comment by lrich** [comment]
Very much appreciated!!!

Thanks!

**Comment by lrich** [comment]
One this is installed, and the index.js [that was server.ts] is in apps/wetty/dist...could I just do my html editing there? Or would the changes have to be done in server.ts.

Thanks again, just getting used to this.

**Comment by butlerx** [comment]
Of your making changes to the html you should codify the server.ts then retranspile
