### ISSUE TITLE
I had issues with the nginx proxy method you suggested..

### ISSUE THREAD

**Issue by ingobaab** [butlerx/wetty#17]
I had to modify the proxy configuration for nginx as follows:
(otherwise the js-files are not loaded..) just for info :)
Thank you for this GREAT software! :-) and keep up the good 
work!!

Kind regards,
-Ingo

location ^~ /wetty {
    proxy_pass http://127.0.0.1:3000/wetty/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 43200000;

```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $http_host;
proxy_set_header X-NginX-Proxy true;
```

}

**Comment by butlerx** [comment]
:+1: pr welcome if this is still required
