### ISSUE TITLE
Ability to modify the main text colour

### ISSUE THREAD

**Issue by dsgnr** [butlerx/wetty#170]
Hey! I've had a look through the compiled code to see if there was a way to modify the white text to a sligh offwhite as it's quite strong against the black background.

Are you able to offer any way of doing this? I've installed using yarn. Thanks!

**Comment by 2sheds** [comment]
1. Set a different color in your terminal with ANSI color codes
2. Customize a theme in settings:
![wetty](https://user-images.githubusercontent.com/16163/55070942-a1fc8a00-5087-11e9-9b21-0507204115a9.png)

**Comment by mikr13** [comment]
@dsgnr It is done, please close this issue!

**Comment by codebyoul** [comment]
Hello,

For more themes, you can check out my fork: https://github.com/oulfr/wetty.git.

By default, the Dracula theme is applied. If you need to change it, you can find all supported themes in:

📂 wetty/src/client/wetty/term/themes.ts

Here’s an example of the terminal configuration with professional defaults:

```
// Terminal configuration with professional defaults
export const TERMINAL_OPTIONS: ITerminalOptions = {
  allowProposedApi: true,
  allowTransparency: false,
  cursorBlink: false,
  cursorStyle: "block",
  fontFamily: '"Fira Code VF", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  fontSize: 17,
  fontWeight: 400,
  fontWeightBold: 500,
  lineHeight: 1.06,
  letterSpacing: 0,
  theme: dracula,  // Default theme; you can replace this with any supported theme
  scrollback: 5000,
  minimumContrastRatio: 4.5,  // Ensures WCAG AA compliance
  wordSeparator: " ()[]{}',\"`",
};

```
