### ISSUE TITLE
Https is not working

### ISSUE THREAD

**Issue by abubakar-bilal** [butlerx/wetty#172]
Hi @koushikmln 

If you remember, we had discussion about configuration and auto login thing. Now I tried to run it with https and I ran this command

/usr/bin/node bin --port 4200 --host 127.0.0.1 --sshauth publickey,password --sslkey ssl.key --sslcert ssl.pem

But process still starts as http. I debugged it and I found that inside createServer method sslopts parameter is nil. Therefore it doesn't start with https.

Can you please guide me on this. Thanks alot. It's bit urgent for me so your kind and quick reply would help me.

**Comment by abubakar-bilal** [comment]
FYI I've pulled your master branch from your repo https://github.com/koushikmln/wetty

**Comment by koushikmln** [comment]
@abubakar-bilal could you pull the latest branch from the krishnasrinivas/wetty link? I'm not sure if the latest changes are there in my branch. Also, you could try using nginx/apache and try configuring SSL for now. I have to test the SSL implementation in wetty and I'm not sure if I can find enough time this week.

**Comment by abubakar-bilal** [comment]
Sure, Thank you so much. But when I merge krishnasrinivas/wetty master into your code. It removes much code.

**Comment by abubakar-bilal** [comment]
And it doesn't work fine when I clone krishnasrinivas/wetty master branch.

**Comment by abubakar-bilal** [comment]
hey @koushikmln 

Hope you are doing good. Just wanted to follow up if you get sometime for this issue. It's not working over https. It would be a great help if you could spare sometime for this.

**Comment by koushikmln** [comment]
what version of code are you using? I use wetty with nginx as proxy with HTTPS and it works fine. Could you try that? I believe there is a template also in the code for nginx.

**Comment by abubakar-bilal** [comment]
I'm not using with nginx proxy. I'm using it as node application running it like this and it's not working. Okay. I'll try it with nginx proxy

/usr/bin/node bin --port 4200 --host 127.0.0.1 --sshauth publickey,password --sslkey ssl.key --sslcert ssl.pem

**Comment by abubakar-bilal** [comment]
@koushikmln I tried with nginx proxy. And it worked fine. Thanks alot.
