### ISSUE TITLE
How do I change the font face used by default in wetty?

### ISSUE THREAD

**Issue by nhjeffh** [butlerx/wetty#177]
I would like change the font used by wetty to another font (terminus)
How is the default font chosen/changed?

**Comment by 2sheds** [comment]
Since 5cc2e68ca you can modify settings to choose any of installed system fonts easily. This wouldn't work for CDN webfonts though.
![wetty](https://user-images.githubusercontent.com/16163/55069781-1da90780-5085-11e9-980a-c51568e8fad1.png)

**Comment by 2sheds** [comment]
https://github.com/xtermjs/xterm.js/issues/1164 refers to measures that need to be taken in order for external webfonts to be handled properly.

**Comment by ghost** [comment]
> Since [5cc2e68](https://github.com/butlerx/wetty/commit/5cc2e68ca9ec43f11114b29fdb497eea29b3f6b4) you can modify settings to choose any of installed system fonts easily. This wouldn't work for CDN webfonts though.
> ![wetty](https://user-images.githubusercontent.com/16163/55069781-1da90780-5085-11e9-980a-c51568e8fad1.png)

Is there a way I can provide a custom font from the server side without the user having to do anything?

I am providing my command line application through the use of wetty and it's doing great, but I still would like to set a different default font, as not all my users are tech savy enough to change it.

**Comment by jap1968** [comment]
I have the exact same problem, but just with "fontSize". I would like wetty to start with a bigger font size (24) so the users do not have to change any configuration value. That is why I opened issue #216
