### ISSUE TITLE
How to run wetty by passing sshkey and access without user authentication?

### ISSUE THREAD

**Issue by aisuresh** [butlerx/wetty#178]
I am running wetty on ubuntu server. Able to access through browser. But everytime asking user username/password to connect.

npm start
npm start -sshkey /root/.ssh/id_rsa

For both commands asking username password.

Can you help how I can run wetty by passing sshkey and access from browser without authentication?

**Comment by 2sheds** [comment]
Your syntax is incorrect. `npm` takes `--sshkey` as its own argument and doesn't pass it along. Add two dashes like so:
```
npm start -- --sshkey /root/.ssh/id_rsa
```
Alternatively, you could pass your params directly: 
```
node . --sshkey /root/.ssh/id_rsa
```

**Comment by mikr13** [comment]
Fixed in:
[Pull request here: 207](https://github.com/butlerx/wetty/pull/207)
