### ISSUE TITLE
Limit cd command functionality

### ISSUE THREAD

**Issue by abubakar-bilal** [butlerx/wetty#179]
@butlerx @koushikmln 

Hello guys, I just need to limit cd functionality for a session. For example, I don't want `cd ..` functionality for a user. I just want to limit user to remain in his project's directory for security purpose. 

Can you please assist me in this regard? It would be really appreciated.

**Comment by butlerx** [comment]
you should look to this in the permissions of the user on the linux machine rather then in wetty, wetty has no control of what the users can run other then specifying the shell

**Comment by abubakar-bilal** [comment]
ahhh, okay. Thanks alot.
