### ISSUE TITLE
Software keyboard on mobile devices

### ISSUE THREAD

**Issue by Maxxie** [butlerx/wetty#18]
Probably this is not a priority, anyway on mobile devices (at least Firefox OS and iOS) the keyboard isn't shown when focusing the app, which makes it unusable. Is there anything that can be done?

**Comment by krishnasrinivas** [comment]
It will be nice to have it working on mobile. Let's keep this open :-)

**Comment by norgeous** [comment]
+1

**Comment by aaronvegh** [comment]
+1, 2 years later.

**Comment by butlerx** [comment]
https://github.com/xtermjs/xterm.js/issues/1101 upstream related

**Comment by advaith1** [comment]
#49 was merged so this should probably be closed

**Comment by Salamandar** [comment]
There's also a weird issue where old text (from the last line) keeps showing on a on when typing…
