### ISSUE TITLE
Startup deamon

### ISSUE THREAD

**Issue by riddertommie** [butlerx/wetty#180]
I followed the install doc and install wetty. i can start it with '$ node index.js' but i cant make it start as a service (systemd).

The cp ~/.config/yarn/global/node_modules/wetty.js/bin/wetty.service is not there and if i copy the file from /opt/wetty/bin it wont work because op the WorkingDirectory=$HOME/.config/yarn/global/node_modules/wetty.js/'' not existing.

Do i do something wrong? 

any tips?

**Comment by antonyjim** [comment]
I have been able to run wetty as a service as seen here:
```
aj@web_server:/var/www$ sudo systemctl status wetty
[sudo] password for aj: 
● wetty.service - Wetty Web Terminal
   Loaded: loaded (/etc/systemd/system/wetty.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-04-06 11:15:07 EDT; 1 day 9h ago
 Main PID: 765 (node)
    Tasks: 12 (limit: 4915)
   CGroup: /system.slice/wetty.service
           └─765 /usr/bin/node /home/aj/lib/node_modules/wetty/bin/wetty.js -p 8011 --host 127.0.0.1
```

And service file:

```
# systemd unit file
#
# place in /etc/systemd/system
# systemctl enable wetty.service
# systemctl start wetty.service
[Unit]
Description=Wetty Web Terminal
After=network.target
[Service]
WorkingDirectory=$HOME/.config/yarn/global/node_modules/wetty.js/
ExecStart=/usr/bin/node /home/aj/lib/node_modules/wetty/bin/wetty.js -p 8011 --host 127.0.0.1
[Install]
WantedBy=multi-user.target
```

It would appear that you did not install wetty globally, but rather in a local directory. Did you install with `npm i -g wetty`? If you did, then I would uninstall and reinstall the package.

If you installed locally then you will need to change `WorkingDirectory` and `ExecStart` to the actual location of the app. For example, if I have wetty installed in `/var/www/wetty`, I would set `WorkingDirectory=/var/www/wetty/` and `ExecStart=/usr/bin/node /var/www/wetty/index.js -p ${whateverPort} --host ${whateverHost}`.

**Comment by antonyjim** [comment]
Forgot to mention, the above (unfortunately) assumes that you have already relocated your global npm install folder to your home directory. If you did in fact install globally, then find out what the current install directory is with ‘npm root -g’. If you do not see you home directory printed, the either:

1. Replace ‘$HOME’ in ‘wetty.service’ with the current global install location. 

2. Follow [this guide](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md) and try to set the service up again.
