### ISSUE TITLE
Installation failed with husky

### ISSUE THREAD

**Issue by johnbritto1** [butlerx/wetty#183]
git clone https://github.com/krishnasrinivas/wetty.git
cd wetty/
 npm install

> husky@1.3.1 install /root/wetty/node_modules/husky
> node husky install

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/root/wetty/node_modules/husky/husky'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! husky@1.3.1 install: `node husky install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the husky@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-15T13_29_50_603Z-debug.log

**Comment by ghost** [comment]
Had the same issue. The error message before stated:
npm WARN deprecated typescript-estree@5.3.0: This package was moved to @typescript-eslint/typescript-estree, please install the latest version from there instead

Installing:
npm install --save-dev typescript-eslint-parser

and than
./node_modules/.bin/eslint --init

fixed it

**Comment by butlerx** [comment]
all packages have been upgraded and wetty is installing successfully
