### ISSUE TITLE
autologin failed

### ISSUE THREAD

**Issue by pheman** [butlerx/wetty#184]
Autologin doesn't work for me, and my server is like:
centos7.5,
I installed wetty following the README.
sshpass installed

When I typed the url:
http://172.18.10.xx:3000/wetty/ssh/app?sshpass=123456
I found that the web terminal turned to an invalid user: app?sshpass=123456,
![image](https://user-images.githubusercontent.com/14324098/56560383-db68dc80-65d6-11e9-9eeb-d0b7b5fb6c4c.png)

**Comment by koushikmln** [comment]
The autologin is broken on master. Will have to fix it. I will try and make a PR soon.

**Comment by koushikmln** [comment]
you can use my fork koushikmln/wetty in case you need it on priority.

**Comment by jpixy** [comment]
Please help to fix this bug asap . Thank you !
