### ISSUE TITLE
Color Themes

### ISSUE THREAD

**Issue by slohmaier** [butlerx/wetty#191]
I am visually impaired and I can't read blue, red und green colors from vim for example in wetty. Is there a way to specify a color scheme like in most terminal emulators?

I found an issue about foreground and background color. I need to change the default terminals colors. Most terminal emulators have this feature.

**Comment by butlerx** [comment]
currently, there's no support for themes but I really like the idea.

**Comment by plato79** [comment]
Setting terminal emulation on profile script could solve that issue, I think. It's stored in TERM variable. If the programs read from that value and set the colors according to that, there'd be no problem.

**Comment by slohmaier** [comment]
I'm new to wetty. Wetty is based on xterm.js right?
xterm.js has some possibilities for theming:
https://github.com/xtermjs/xterm.js/issues/1719
I'm not very experienced in JS-development. I guess I'll try it.

**Comment by Christian7573** [comment]
Looks like you can make your own color theme using the options pane. Check xterm's [ITerminalOptions](https://github.com/xtermjs/xterm.js/blob/master/typings/xterm.d.ts#L31) and [ITheme](https://github.com/xtermjs/xterm.js/blob/master/typings/xterm.d.ts#L266) to see what options are available.

**Comment by codebyoul** [comment]
Hello,

For more themes, you can check out my fork: https://github.com/oulfr/wetty.git.

By default, the Dracula theme is applied. If you need to change it, you can find all supported themes in:

📂 wetty/src/client/wetty/term/themes.ts

Here’s an example of the terminal configuration with professional defaults:

```
// Terminal configuration with professional defaults
export const TERMINAL_OPTIONS: ITerminalOptions = {
  allowProposedApi: true,
  allowTransparency: false,
  cursorBlink: false,
  cursorStyle: "block",
  fontFamily: '"Fira Code VF", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  fontSize: 17,
  fontWeight: 400,
  fontWeightBold: 500,
  lineHeight: 1.06,
  letterSpacing: 0,
  theme: dracula,  // Default theme; you can replace this with any supported theme
  scrollback: 5000,
  minimumContrastRatio: 4.5,  // Ensures WCAG AA compliance
  wordSeparator: " ()[]{}',\"`",
};

```
