### ISSUE TITLE
Is it possible to embed wetty?

### ISSUE THREAD

**Issue by stratus-ss** [butlerx/wetty#192]
I am writing an impress.js presentation and normally I embed foreign content similar to this:

```
            <div id="kaspersky" class="wrapper step" data-x="-25000" data-y="0">
                <object style="position: relative; right: 4em" type="text/html" data="https://cybermap.kaspersky.com/" width="1280px" height="768px">
                </object>
            </div>
```

I tried using a similar technique with wetty but all of the web browsers fail to render the terminal. I can see from both the logs of wetty and the browsers dev console that the connection is being established.

Is there some sort of cross site scripting blocking this or other facility that its possible to disable/override?

The idea is that when the div element is displayed, the terminal is there without having to switch tabs or something similar.

Thanks for the hard work

**Comment by butlerx** [comment]
currently, no as wetty does enforce xss protection through helmet.

we are open to pr to add a flag to relax xss protections on an opt-in by the user.

**Comment by butlerx** [comment]
it is now possible to embed wetty by disabling xss protections by passing the flag `--bypasshelmet`
