### ISSUE TITLE
connect to host localhost port 22: address not available

### ISSUE THREAD

**Issue by tommy-k** [butlerx/wetty#194]
Hello,

I've used this docker image before, and recently setting it up it has stopped me from logging in giving me this interesting error w/ port 22.
![Annotation 2019-06-11 230244](https://user-images.githubusercontent.com/19766457/59321181-0ef2e980-8c9f-11e9-8ae5-f989e1544475.png)

I'm using the following docker command to start this:
`docker run --name wettydemo -p 3000:3000 -dit krishnasrinivas/wetty`
I can't see why this is happening.

**Comment by butlerx** [comment]
when sshing with the docker container you can't connect to localhost s the docker container doesn't run a openssh server

**Comment by tommy-k** [comment]
> when sshing with the docker container you can't connect to localhost s the docker container doesn't run a openssh server

I don't even know that I'm necessarily doing an ssh to the docker container.  after I run this command to startup the container, once live I try to login with the default `term/term` user & pass, but that's what happens.  should I be accomplishing this another way?

thanks for the response!

**Comment by butlerx** [comment]
When running in docker the default term is for the ssh sidecar container. 
to specify the host to ssh too you can pass the env `SSHHOST=IP_OF_HOST`
