### ISSUE TITLE
Multiple users to access wetty terminal

### ISSUE THREAD

**Issue by abubakar-bilal** [butlerx/wetty#196]
I have multiple users on my system with different set of permissions. I want them to access wetty terminal with respect to their usernames so that they have their set of permissions.

Let's say I've 10 users on a system. How can I achieve that?

CC: @koushikmln @butlerx @krishnasrinivas

**Comment by abubakar-bilal** [comment]
@koushikmln  @butlerx any insight on this would be really helpful.

**Comment by fbartels** [comment]
Hi @abubakar-bilal,

wetty is just a terminal application. Each of your ten users will have their own session when logging in with their own credentials.

**Comment by abubakar-bilal** [comment]
@fbartels Actually terminal application is running as a `abc` user on my server and we use something like this 

https://domain.com/wetty/ssh/abc

I cannot use the url like https://domain.com/wetty/ssh/def for `def` user. I want to use terminal for all my users on that server. Do I need to run terminal application for each user with that particular user?

**Comment by butlerx** [comment]
what do you get when you go to `domain.com/wetty/ssh/def`?
