### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by Slind14** [butlerx/wetty#20]
Hey, 
is there any chance of windows support, maybe with the pty.js fork or the open pullreq?
https://github.com/JamesMGreene/node-partty
https://github.com/chjj/pty.js/pull/111

**Comment by krishnasrinivas** [comment]
Does windows ptys support *nix terminal emulation? I have no idea. Maybe you can explore and see if a PR is possible.

**Comment by Slind14** [comment]
pty.js is an inactive project. Not even pull reqs are being considered for months. There is an open pull req which adds windows support (https://github.com/chjj/pty.js/pull/111) and there is a "maintained" fork, too: https://github.com/JamesMGreene/node-partty
But I already stated that, so I'm not entirely sure what you mean. :(
If you mean if it is wrapping the windows terminal with the nix layout, I would say no.

**Comment by krishnasrinivas** [comment]
Sorry, by "window ptys" I meant "windows virtual terminals", not pty.js.
Basically linux has virtual terminals (/dev/pts/0,1,2,4) and terminal emulators (xterm/konsole etc) to talk to the virtual terminals, the protocol being defined by the environmental variable TERM (which can be vt100, vt102, xterm, etc)
I don't know how wetty's terminal emulator will behave when it talks to a windows terminal. Maybe you can try it out. And send a pull-request if it works :-)

**Comment by Slind14** [comment]
I couldn't get it to work, sorry. :(
https://github.com/JamesMGreene/node-partty/issues/2

**Comment by BenoitDuffez** [comment]
Did you try `screen /dev/whatever 115200`? It worked out of the box for me with a ttyUSB created by an FTDI device
