### ISSUE TITLE
Cursor moves around

### ISSUE THREAD

**Issue by plato79** [butlerx/wetty#20]
I don't know if it's just me because while this is not a big issue it's annoying and should be detected by someone else before..

After successfully connecting via SSH, for example if I list directory contents with "ls -al" I find the cursor blinking at the beginning of the prompt, or if I hit enter, the blinking cursor stays up. With other programs it also moves around to wherever it wants. The weird thing is the red cursor is always where I need it.. 

I used "krishnasrinivas" repository before and didn't see this problem. Actually I'm not sure if there ever was a blinking cursor with that repository or not. :)

**Comment by butlerx** [comment]
second cursor has been removed
