### ISSUE TITLE
API Example Does Not Work

### ISSUE THREAD

**Issue by wazy** [butlerx/wetty#202]
Running the API example in a simple express route:
```
wetty
  .on('exit', ({ code, msg }) => {
    console.log(`Exit with code: ${code} ${msg}`);
  })
  .on('spawn', msg => console.log(msg));
wetty.start(/* server settings, see Options */).then(() => {
  console.log('server running');
  /* code you want to execute */
}).catch(err => console.log(err));
```

Throws the following exception:
```
TypeError: Cannot read property 'key' of undefined
    at /var/www/html/node_modules/wetty.js/dist/index.js:1:4054
    at Object.start (/var/www/html/node_modules/wetty.js/dist/index.js:1:4230)
    at /var/www/html/test.js:13:7
```

This is how wetty and express were installed:
```
yarn add global express
yarn add global wetty
```

The problematic area in wetty.js/dist/index.js:
`return async function(e){if(m()(e.key)||m()(e.cert))return{};`

Things work as expected sans the TLS key/cert when wetty.js/dist/index.js is edited to just return:
`return async function(e){return{};`

I believe the issue may be coming from here but could very well be mistaken:
https://github.com/butlerx/wetty/blob/8191de94b7fa430fac80993d428c4a0f50b7a0f5/src/server/ssl.ts#L7

**Comment by butlerx** [comment]
this should be fixed in version 1.1.7
