### ISSUE TITLE
Starting Wetty from API with Custom Port is Confusing

### ISSUE THREAD

**Issue by wazy** [butlerx/wetty#203]
The API docs indicate that serverPort can be set in the start call of wetty:
https://github.com/butlerx/wetty/blob/8191de94b7fa430fac80993d428c4a0f50b7a0f5/docs/API.md

The only way I could get it to start with a custom server port was to do the following:
```
var serverPort = 10000
wetty.start(ssh, { base:"/wetty/", port: serverPort, host:"0.0.0.0" })
```

This doesn't seem to correlate with the docs as I had to reverse engineer this from the index.js generated in the node_modules to get it to work.

Did I miss something obvious?

**Comment by wazy** [comment]
Also wanted to bring up that `ssh.key` isn't documented in the API.md but does work as well.

**Comment by butlerx** [comment]
thanks for pointing this out. I had neglected the docs for a few api changes. The Api docs have been used with the changes required.
