### ISSUE TITLE
tab autocompletion?

### ISSUE THREAD

**Issue by mgckind** [butlerx/wetty#21]
Hi, nice work!! It's been very useful...

one minor thing, it seems that "tab" autocompletion is not supported or at least I couldn't make it to wotk.

Any suggestions?

**Comment by krishnasrinivas** [comment]
Tab completion should work. what server are you running wetty on? Linux/mac? what command do you use to start the wetty? what is the browser you use?

**Comment by mgckind** [comment]
Thanks for the quick reply,

I'm using the docker image through boot2docker in a mac and Google Chrome.
Every time I press tab it goes back to the browser's navigation bar,  Maybe
I'm missing something very basic

Thanks again

**Comment by krishnasrinivas** [comment]
Does pressing tab take you to address bar only in wetty terminal? or during
general browsing of pages too?
Also can you try with Firefox? (you'll need to use latest version of nutty
for it to work with FF)

**Comment by mgckind** [comment]
During general browsing,  but it does work with term.js through terminado
though.  I'll try Firefox

Thanks

**Comment by the-destro** [comment]
ah ha! I am having this issue as well. If I look at the console when trying to tab complete I get this error:
hterm.js:1161 Uncaught TypeError: Cannot set property shiftKey of [object Object] which has only a getter

**Comment by mgckind** [comment]
It never worked for me, it happened only in a Mac, not a in a Linux box

**Comment by the-destro** [comment]
I seem to have it fixed. One of my docker images had an old version.

**Comment by krishnasrinivas** [comment]
@mgckind It looks like the problem got fixed for @the-destro  by updating the version. Can you check with latest this latest docker image -> krishnasrinivas/wetty

**Comment by mgckind** [comment]
Yes, it was the version in dockerhub. I've updated it and works fine. Thanks!

**Comment by krishnasrinivas** [comment]
Hey krishnasrinivas/wett,

Discover high quality jobs and connect with recruiters on LinkedIn.

- Krishna

Accept invite: https://www.linkedin.com/e/v2?e=0-iky2pxog-c9&t=ssuw&ek=invite_guest&li=14&m=invite_guest&ts=india_a&sharedKey=i6K5FWfC&invitationId=6107539864545222656

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iky2pxog-c9&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQF2NzwJyxX3WwAAAVMJXU7Qwy7uEEeUQF70FpQ1LsJ3mmWulyUDvMNi08Jkja3FZpAWDf7ZkK9LevzTeB01Pcjys_Opc3LgpXwvm0Q-3Pml96w8kZbvCiRjyv8iRBiOnpjPeHRI3-5-_mNrryHT-NAKhaOapr86Pwn3lvjjbJ0Z2Y8WojyuAmDdKGh5Yug0WpjN&eid=0-iky2pxog-c9

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iky2pxog-c9&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
