### ISSUE TITLE
README.md is broken

### ISSUE THREAD

**Issue by mikr13** [butlerx/wetty#212]
I guess this is not working as expected
![image](https://user-images.githubusercontent.com/34394719/67656312-6f967080-f979-11e9-895a-584099f9c22c.png)
See the All contributor link is not showing as expected, but on click of the link, its showing perfectly
![image](https://user-images.githubusercontent.com/34394719/67656355-95bc1080-f979-11e9-8fd6-18aa78919a35.png)
I think this is not a intended behaviour.

**Comment by plato79** [comment]
It'd be good if the new options about configurations are updated in the README so all users could have an idea how to configure them.

**Comment by butlerx** [comment]
this has been fixed
