### ISSUE TITLE
Add screenshots or demo in the README

### ISSUE THREAD

**Issue by rgarrigue** [butlerx/wetty#213]
Hi

I wanted a 2 sec overlook of you wetty, but there's no screenshots or demo available. Mind adding one ? The best would be a gif demonstrating a couple of things .

Best regards,

**Comment by antonyjim** [comment]
Here are a few samples I put together:

![Wetty Sample Gif](https://anthonyjund.com/wp-content/uploads/2019/10/low_res_commands.gif)
![Neofetch_Big](https://anthonyjund.com/wp-content/uploads/2019/10/wetty_debian_neofetch.png)
![Neofetch_Small](https://anthonyjund.com/wp-content/uploads/2019/10/wetty_debian_neofetch_small.png)

What do you think @butlerx?

**Comment by butlerx** [comment]
looks good feel free to put together a pr. please place the images in the docs folder.
