### ISSUE TITLE
How to change font size

### ISSUE THREAD

**Issue by jap1968** [butlerx/wetty#216]
I am looking for an easy way (I mean something like an environment var or a configuration file) to change the font size.

The only related topic that I've found so far is issue #177, but that information seems incomplete to me, because I don't know what files should be changed.

**Comment by plato79** [comment]
We could change the font size now and it's perfect, but maybe there should be check to see if the font size is 1,2 or 3(?) the font stays the last size. Because it's changing in real time, if you change from 14 to 18 for example it tries to switch to 1 first I think.
