### ISSUE TITLE
Some editors display garbled text

### ISSUE THREAD

**Issue by plato79** [butlerx/wetty#22]
Hi,

I don't think I had this error before. But I couldn't find the cause yet. 

When I enter this command: 
`sudo nano /usr/local/etc/nginx/nginx.conf`

The output is like this:

http://imgur.com/oQ5EUpz

And when I use PgDn, PgUp it becomes more corrupt by the second. Some text just stuck at the left while screen is scrolling..

I also saw the same thing happen with "ee". With "ne" there's no problem. So it's about scrolling techniques ( libraries ) used by some programs.

I didn't see anything like this before, and also I didn't update recently.

I'm sure that it worked correctly before. At first I thought a tool caused this problem but I opened a new console page and the same happened again after executing the nano or ee.

Does something in chrome affect the console? One thing I didn't try yet is restarting the browser. I'll also test it to see if it's the cause.

**Comment by butlerx** [comment]
sorry for slow response im looking into this but have had issues replicating could you give me some info about your browser?

**Comment by plato79** [comment]
I'm using chrome v58.0.3029.81

**Comment by nosemeocurrenada** [comment]
Yeah I sometimes get the same with nano, it gets fixed by closing and reopening the file.
Using chrome v60.0.3112.113 (64bits)

**Comment by butlerx** [comment]
ive been able to replicate it with weechat and will be looking in to it

**Comment by mirtouf** [comment]
Confirmed also with Firefox 55.

**Comment by butlerx** [comment]
was able to reproduce with nano. 
I believe it was an issue with how I was passing data to the socket. 
i believe it to be patched now

**Comment by mirtouf** [comment]
Sorry, these commits introduced the possibility to start wetty

```
node app.js -p 3000
/var/www/wetty/cli.js:77
async function loadSSL({ sslkey, sslcert }) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by butlerx** [comment]
sorry i used to running everything in docker i may just revert that

**Comment by mirtouf** [comment]
By the way the original intent of the commit is a success, no more garbled text in firefox 55 & 56.

**Comment by butlerx** [comment]
thanks, ill be reverting the async code to a promise

**Comment by plato79** [comment]
Latest commit fixed the error. I'll try to check if #21 exists now.
