### ISSUE TITLE
ioctl(2) failed.

### ISSUE THREAD

**Issue by alexmwu** [butlerx/wetty#22]
Hi, I can't get the terminal to work properly. I keep getting this error: `Error: Error: ioctl(2) failed.`
Any ideas? Thanks!

**Comment by krishnasrinivas** [comment]
What server are you running wetty on (linux/mac)? what is the node version? what is the command used to start wetty?

**Comment by alexmwu** [comment]
tried on OSX 10.10.2 and Amazon AMI with the same command:
`sudo node app.js -p 3000`
Running v0.12.2 and v0.10.36, respectively.
The ec2 instance just shows a blank black terminal with the red cursor, but OSX also gives an error: `exevp(3) failed.: No such file or directory`

**Comment by LaKing** [comment]
Same here with fedora 22, ...

When starting as root, I only get the red cursor, and this error message, ...

**Comment by krishnasrinivas** [comment]
Let me check with a fedora 22

**Comment by krishnasrinivas** [comment]
@LaKing you get this error only as root? what about as a regular user? when you execute it as root it tries to execute /bin/login - can you see if /bin/login exists?

@alexmwu are you executing as root or a regular user? if you are root /bin/login should exist, if you are a regular user 'ssh' needs to be in path.

**Comment by LaKing** [comment]
As regular user on a normal system, I can run wetty fine.
I updated my fedora system, and now it seems I can run it as root with a normal root login.

On a fedora that has not been updated in the last two weeks, it produces this problem with normal root login. It also produces these results with error messages when running via sudo, even with the latest updates.

All systems run node v 0.10.36 - so, as far as I see this is not related to node, but the underlying OS.

**Comment by krishnasrinivas** [comment]
@LaKing ah, ok.
@alexmwu i see that you are using sudo. Can you check if /bin/login exists on mac?

**Comment by alexmwu** [comment]
On OSX, running as a regular user gives a `Connection refused` error on wetty.

There is no /bin/login on mac. There is, however, /usr/bin/login. Also, above, what do you mean by 'ssh' needs to be in the path? Do you mean sshd?

**Comment by krishnasrinivas** [comment]
In that case in app.js just replace /bin/login with /usr/bin/login
'Connection refused' indicates ssh is in the path, but sshd server is not running on your mac.

**Comment by alexmwu** [comment]
Hey, thanks a lot. This works now. I still need to run with sudo, however. Otherwise, I still get a `Connection refused error`. Both ssh and sshd are in the path. Any ideas on that?

**Comment by krishnasrinivas** [comment]
you can google for "how to start ssh server on mac" - that should fix your "connection refused" problem

**Comment by kotamahesh** [comment]
how to set ssh path and can we provide default root login without user credientials ???like user name and password .using ssh keys
