### ISSUE TITLE
Wrong working directory in wetty.service/

### ISSUE THREAD

**Issue by ghost** [butlerx/wetty#220]
In order to run wetty as service, shouldn't the working directory (https://github.com/butlerx/wetty/blob/master/bin/wetty.service)
 be:
WorkingDirectory=$HOME/.config/yarn/global/node_modules/wetty/ 
instead of 
WorkingDirectory=$HOME/.config/yarn/global/node_modules/wetty.js/
?

**Comment by butlerx** [comment]
Yes this was from merging forks back up stream. Feel free to make a pr

**Comment by lozbrown** [comment]
@butlerx @torstenboe i think this was resolved in the pull request that i made earlier this week 
#269

Can we close this?
