### ISSUE TITLE
Small change suggestion for download script

### ISSUE THREAD

**Issue by kb1ooo** [butlerx/wetty#221]
In the File Downloading FAQ, I would suggest a change to the example script so that it uses octal codes for the escape sequences, since if you cat the example file as written, it will initiate a download (in fact, the `$ cat wetty-download.sh` as shown to be executed in the FAQ will do that, at least it does for me).   I would suggest something like the following instead (note that `/bin/sh` is important otherwise you need the `-e` flag if you are using echo for bash.  Actually it would probably be better to use printf for portability).  Another comment is that this strategy (and the original) work in general for `/bin/sh` because base64 doesn't have backslashes:
```
#!/bin/sh

# Implementation with octal codes so that if you
# cat this file to the terminal it won't start a download

echo "\033[5i"$(cat /dev/stdin | base64)"\033[4i"
```

**Comment by tpmullan** [comment]
I added this to my bashrc:

```
funtion wetty-download() {
        echo "\033[5i"$(cat /dev/stdin | base64 -w 0)"\033[4i"
}
```

That way you can run it with:
`cat test.txt | wetty-download`

**Comment by butlerx** [comment]
docs have been updated
