### ISSUE TITLE
is WeTTY the right tool for my remote managment scenario, when SSH is block on my machine

### ISSUE THREAD

**Issue by PackElend** [butlerx/wetty#228]
Hello,
it took me some time to find apps to enable me to share a shell in a browser.

Me and friend managing some simple VPSs that shall be managed from a central management server to simplify workflow.
There are cases that we still need a shell and allowing us to share this session would be extremely helpful.
In addition, when I'm at work, SSH is blocked so it quite challenging to manage them.

So is WeTTY the tool to get around this?

The architecture is close to this one:
image
![image](https://user-images.githubusercontent.com/3542031/73609485-75ca6780-45ce-11ea-91b8-572e37fdaf7f.png)

thank you for answering my humble question which answer might be obvious but due to my endless searching I cannot see the woods for the trees.

Stefan

**Comment by darkpixel** [comment]
> when I'm at work, SSH is blocked so it quite challenging to manage them

Not really an answer to your question, but that statement is concerning.
If your employer blocked it, attempting to subvert their restrictions probably isn't the best idea.  Also, in some places whatever you do on company time is automatically 'owned' by the company.

**Comment by PackElend** [comment]
> If your employer blocked it, attempting to subvert their restrictions probably isn't the best idea.

It is blocked for security reason of the companies network what is acceptable. Accessing my stuff that way does not expose any risk to the company, so that does not count 

>  Also, in some places whatever you do on company time is automatically 'owned' by the company.

I don't work on them during office but if something is making trouble shell access is mandatory. The same when you bank or whoever informs you that something is wrong, you don't wait until coming back home.

**Comment by darkpixel** [comment]
No offense intended.  I just didn't want you to fall into the trap that a few of my co-workers ran into.

**Comment by PackElend** [comment]
What trap they ran into?

**Comment by butlerx** [comment]
WeTTy's primary use for my self is for using on machines or networks where ssh is blocked for some reason or another.
WeTTy doesn't currently allow for session sharing, I would recommend the use of tmux or screen for this rather than implementing it in WeTTy as they already do a fantastic job of session sharing. 

I currently run WeTTy on one box in my network and then remotly access other boxes from that admin box using tradiotinal tool ala a jump host. 
So i think yes WeTTy would work for you.

**Comment by PackElend** [comment]
> tmux 

I'm reading up tmate.io currenlty too.

> I currently run WeTTy on one box in my network and then remotly access other boxes from that admin box using tradiotinal tool ala a jump host.
> So i think yes WeTTy would work for you.

that would alright for the beginning as it allows to access them via ssh at any time from anywhere.
Could you explain in detail your setup as it looks like that tmate server container needs to run with `--cap-add=SYS_ADMIN` what is for [security reasons](https://tmate.io/), but still don't like it: 
- https://www.redhat.com/en/blog/container-tidbits-adding-capabilities-container
- https://serverfault.com/questions/889139/disadvantage-of-giving-sys-admin-to-docker-container/892461?_sm_au_=iVVfvkqVLqkfR8T6tfMpNK72VpWWt)

Unfortunately [docker-stack does not support ](https://docs.docker.com/compose/compose-file/#cap_add-cap_drop) `cap-add` what could me allow to bring up and down using portainer. 
So I wonder how can activate WeTTY on demand without shell access?
Any safe possibility using docker?
