### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by rtwk** [butlerx/wetty#23]
I am trying to run wetty on a AWS EC2 instance. If a start the app.js with root I can access (using nginx as reverse proxy) to from public but when I try to do so using http://domainname:3000/wetty/ssh/<username> it returns Permission denied (publickey). The user is a valid SSH user and it can access the remote server from my local machine though.

**Comment by krishnasrinivas** [comment]
can you paste the command you use to start wetty?

**Comment by rtwk** [comment]
Sure. I tried both 

forever start app.js -p 3000
and 
forever start app.js -p 3000 --sshhost public_ip --sshuser myuser --sshport 22

**Comment by krishnasrinivas** [comment]
Ah, looks like ssh servers (localhost of wetty and public_ip) is configured to accept ssh connections only with pvt key auth and not user/pass.
You can either:
1) configure /etc/ssh/sshd_config with "PasswordAuthentication yes"
or
2) start app.js with option "--sshauth publickey,password" and setup pvt/pub keys for passwordless login.

**Comment by rtwk** [comment]
If I go for option 2, are to be set for the wetty or the server (public_ip)?
And is there a way to supply login/passwd automatically if I go for option 1?

**Comment by krishnasrinivas** [comment]
For wetty. Check app.js source to get an idea of how ssh connections
happens.

**Comment by rtwk** [comment]
I have created keys with ssh-keygen and placed authorized_keys within the home directory of the user whom I want to log in. It does not spit 'Permission denied (publickey)' anymore but still asks for login and password.

**Comment by krishnasrinivas** [comment]
That is because public key auth fails as it is not setup. note that you have to setup pub/pvt key auth between the machine running app.js and public_ip if dont want it to ask for username/password

**Comment by krishnasrinivas** [comment]
Hey krishnasrinivas/wett,

Discover high quality jobs and connect with recruiters on LinkedIn.

- Krishna

Accept invite: https://www.linkedin.com/e/v2?e=0-iky2pyrl-ta&t=ssuw&ek=invite_guest&li=14&m=invite_guest&ts=india_a&sharedKey=ZAPMLVJz&invitationId=6107539864394227712

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iky2pyrl-ta&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQF_0lfU8yzKbAAAAVMJXVV2EDPCjsNqAy61AljucfWA9zWLCn4VXWp-dpnhcos-Ehlgpj70E5VfOqm5qmRy_webvQHc3uK9KnWFJG7lPRTT2mvS3ibTv9ziCvsffysUp8zt28QRGEKQ0mel1vJy3RWGbLBAhRaeBJR_D5y1Wg46tSX8_w6mFLAqXm8X5G4afEyE&eid=0-iky2pyrl-ta

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iky2pyrl-ta&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
