### ISSUE TITLE
Paste

### ISSUE THREAD

**Issue by LaKing** [butlerx/wetty#24]
Hi there. Great work!

Is there a way to paste from a clipboard, directly to the terminal?

Copy seems to work with ctrl-C, but ctrl-V?

Thank you, ..

**Comment by krishnasrinivas** [comment]
copy is ctrl-C
paste is shift-ctrl-V

**Comment by LaKing** [comment]
Oh, I see that works! Great!

I think this could be mentioned on the readme  ... .)

I'm just curious, why exactly it got this key combination?

**Comment by krishnasrinivas** [comment]
Yes this should be mentioned in the readme .... at the top :) If possible send a PR

Why this key combination for paste - if I remember it right - for ctrl-C I made the hterm code to ignore the key and leave it to the browser default action which was to copy. The browser did the 'copy' fine for ctrl-C. But for ctrl-V punting the request for default browser action did not work, I am not sure why, but ctrl-shift-V combination worked. It should be explored why ctrl-V does not work as a default browser action for paste.

**Comment by LaKing** [comment]
I found a preference switch in the code. Line 6856 of hterm_all.js.

``` javascript
  'ctrl-v-paste': false,
```

With this switch on the default false, Ctrl-shift-V pastes in a Chrome, but not on Firefox.
If it is set to true, ctrl-V pastes on both. ...

Chrome is on Version 43.0.2357.125 (64-bit) 
Firefox is 38.0.5.
Fedora 22.

**Comment by krishnasrinivas** [comment]
Great find! but emacs has ctrl-v bindings for pg-dn So emacs users will find it frustrating.
What do you think is better? ignore emacs users? or shift-ctrl-V?

**Comment by LaKing** [comment]
Just tested with Firefox 39.0 and Chrome Version 43.0.2357.132 (64-bit) .. Ctrl-V works on both.
With the preference on false Ctrl-shift-V does not work on that Firefox either.

If you ask me, there are probably more users finding the lack of Ctrl-V more frustrating. 
People use that more intuitive. The bigger problem is that there is no paste on a recent firefox by default with the current preference, ...

My vote is clearly Ctrl-V for paste by default, and leave the option for older-browser users and emacs users to override. ... .)

**Comment by krishnasrinivas** [comment]
pushed the fix, thanks for your inputs!
