### ISSUE TITLE
Unable to install on CentOS 7.6

### ISSUE THREAD

**Issue by swampfox0866** [butlerx/wetty#240]
I have an up-to-date install of CentOS 7.6 and I'm getting an error when trying to install wetty:

```
[root@localhost ~]#yarn global add wetty
yarn global v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error file-type@12.4.2: The engine "node" is incompatible with this module. Expected version ">=8". Got "6.17.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
[root@localhost ~]#

```
Installed packages with YUM:
- nodejs.x86_64 (v6.17.1-1)    # prerequisites say node >= 6.9
- npm.86_64(3.10.10-1)

Installed YARN with NPM:
- yarn (1.22.4)

I've been running an older version of wetty (installed with npm) for a couple years now on a CentOS 7.5 system with no problems. Trying to install the latest release using yarn doesn't work.

Any help would be greatly appreciated.  Trying to get a remote solution for our phone centers setup due to the coronavirus pandemic.  BTW, hope everyone is safe.

**Comment by MatthiasSchinzel** [comment]
A little bit late, but update node

```
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs
node -v
```

**Comment by butlerx** [comment]
yes as @MatthiasSchinzel said your version of node doesn't meet the minimum install version which is now 14

**Comment by butlerx** [comment]
your original issue does stem from a dependency rather then wetty itself, but weve updated the min version isnce
