### ISSUE TITLE
Access WeTTY terminal via native CLI

### ISSUE THREAD

**Issue by RA80533** [butlerx/wetty#243]
I am essentially searching for a way to do almost the inverse of what WeTTY delivers. I might not even know exactly what I am asking for because I assumed *someone* would have already established a method to achieve what I am trying to do.

WeTTY exposes a shell through a web interface. I wish to interface with that web interface through a native shell thereby emulating what would be an entirely native connection to the underlying SSH server.

Is anyone familiar with a utility that would be capable of such behavior?

**Comment by kb1ooo** [comment]
Can you explain more what you mean?

**Comment by RA80533** [comment]
WeTTY allows users to connect to a terminal that may otherwise be unexposed. For example, an organization may allow connections to go through port 80 or 443 but disallow SSH connections external to its network (typically done through port 22). Users would then interface with WeTTY-enabled shell sessions through their browser via the standard HTTP or HTTPS ports (if configured with conventional standards).

I wish to interface with the WeTTY-enabled terminal through a native CLI, similar to what would normally be possible if SSH were directly accessible in the first place.

**Comment by RA80533** [comment]
At the moment, I managed to sort of find what I was looking for in the form of a WebSocket-capable `netcat` utility.

**Comment by dezeroku** [comment]
It seems that you are basically interested in connecting via SSH in networks where port 22 is blocked / ssh traffic is not allowed. You may be interested about exposing ssh server through https/http port (443/80 vs 22). If proxy checks whether packages sent to these ports are correct http, read about tunneling ssh over http.

**Comment by RA80533** [comment]
You have the right idea, @d0ku; unfortunately, there are limitations in place which prevent me from being able to modify any network-related configurations on the machine running WeTTY.

**Comment by butlerx** [comment]
@RA80533 it sounds like you'd like ssh over WebSocket client. 
An interesting idea but I think outside the scope of this project. 
Currently, Wetty is a js client to a WebSocket server to proxy to a remote machine so if you'd like to create a client reusing the sever feel free to open a pr but I think it may deserve its own project
