### ISSUE TITLE
Fail to build docker-compose 

### ISSUE THREAD

**Issue by HadesArchitect** [butlerx/wetty#244]
**Describe the bug**
`docker-compose up -d` fails to execute with error `ERROR: Service 'wetty' failed to build: The command '/bin/sh -c apk add -U openssh-client sshpass &&     mkdir ~/.ssh &&     ssh-keyscan -H wetty-ssh >> ~/.ssh/known_hosts' returned a non-zero code: 1`

```
Step 15/16 : RUN apk add -U openssh-client sshpass &&     mkdir ~/.ssh &&     ssh-keyscan -H wetty-ssh >> ~/.ssh/known_hosts
 ---> Running in d11b9240c2e8
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/6) Installing openssh-keygen (8.1_p1-r0)
(2/6) Installing ncurses-terminfo-base (6.1_p20200118-r3)
(3/6) Installing ncurses-libs (6.1_p20200118-r3)
(4/6) Installing libedit (20191211.3.1-r0)
(5/6) Installing openssh-client (8.1_p1-r0)
(6/6) Installing sshpass (1.06-r0)
Executing busybox-1.31.1-r8.trigger
OK: 12 MiB in 22 packages
getaddrinfo wetty-ssh: Name does not resolve
getaddrinfo wetty-ssh: Name does not resolve
getaddrinfo wetty-ssh: Name does not resolve
ERROR: Service 'wetty' failed to build: The command '/bin/sh -c apk add -U openssh-client sshpass &&     mkdir ~/.ssh &&     ssh-keyscan -H wetty-ssh >> ~/.ssh/known_hosts' returned a non-zero code: 1
```

**To Reproduce**
1. Clone the project
2. `docker-compose up -d`

**Expected behavior**
Expected to have wetty running in a docker container

**Screenshots**
![image](https://user-images.githubusercontent.com/1742301/80355502-79d9ee80-8878-11ea-969a-1c71303e2fa5.png)

**Desktop (please complete the following information):**
 - OS: High Sierra 10.13.6
 - Version: latest master 
 - Docker: 19.03.8

**Comment by ndusek** [comment]
I am running into this exact same issue, but using the plain `docker build` instead of `docker-compose up -d`.

**Comment by butlerx** [comment]
This Should be fixed in the latest release to master
