### ISSUE TITLE
New tag/release

### ISSUE THREAD

**Issue by kmlucy** [butlerx/wetty#251]
Can you create a new version tag/release? The most recent is v1.3.0 which doesn't include the host checking flag. I have an open PR for a Docker image for WeTTy, but it can't be merged until there is a new release. 

https://github.com/svenihoney/docker-wetty-alpine/pull/9

**Comment by kmlucy** [comment]
@butlerx Is this something you are willing to do?

**Comment by butlerx** [comment]
ill get something tagged soon I'm very busy of late but plan to put some time in the wetty soon

**Comment by butlerx** [comment]
latest version tagged in npm
