### ISSUE TITLE
Ssh username can not set in url parameter /ssh/:user

### ISSUE THREAD

**Issue by sergeir82** [butlerx/wetty#256]
**Describe the bug**
Local username used on connection to server instead username from url parameter.

**To Reproduce**
What I done:
- clone butlerx/wetty to my mac
- run yarn && yarn run build
- execute **node ./index.js**
- go in Chrome to **http://localhost:3000/wetty/ssh/admin?host=192.168.89.1**
- I see password prompt with my local username:
`sergeir82@192.168.89.1's password:`
But expected:
`admin@192.168.89.1's password:`

**Expected behavior**
**admin@192.168.89.1's password:**

**Desktop:**
 - OS: macOs Catalina 10.15
 - Browser chrome
 - node 14.4

**Additional context**
I can fix this https://github.com/butlerx/wetty/compare/master...sergeir82:fix-user-name?expand=1#diff-80a1b716a96ce7e3a4106a18652d460d

**Comment by butlerx** [comment]
your change has been merged
