### ISSUE TITLE
TAB key doesn't work?

### ISSUE THREAD

**Issue by thefallentree** [butlerx/wetty#26]
Hi, can you make tab key work? ?? currently it will jumps to location bar....

**Comment by thefallentree** [comment]
![image](https://cloud.githubusercontent.com/assets/1256464/9055062/c47473a0-3ab9-11e5-8e5e-6fc124db149b.png)

**Comment by krishnasrinivas** [comment]
Can you check if this is your issue https://github.com/krishnasrinivas/wetty/issues/21

**Comment by krishnasrinivas** [comment]
No response, closing.
