### ISSUE TITLE
Upgrading Helmet to the next major version

### ISSUE THREAD

**Issue by EvanHahn** [butlerx/wetty#261]
I'm the maintainer of Helmet. I plan to release the next major version this Sunday, 2020-08-22.

Is there anything I can do to help get this project upgraded to `helmet@4`?

If you'd like to try out the release candidate now, you can install it with `npm install helmet@next`. If you'd rather discuss things outside of this issue, feel free to [reach out to me](https://evanhahn.com/contact) another way.

Hope I can be helpful!

**Comment by butlerx** [comment]
Will test as part of #265

**Comment by butlerx** [comment]
helmet 4 breaks WebSocket usage out of the box. To allow for WebSocket a more explicit helmet config has been added. 
With this, I've also deprecated the bypass helmet flag. in favour of a allow iframe flag which I believe is more in the spirit of the original intention of this flag

**Comment by butlerx** [comment]
helmet is now the latest version
