### ISSUE TITLE
Passing in username or username + password in url doesn't seem to work

### ISSUE THREAD

**Issue by daynok** [butlerx/wetty#263]
I'm using current content from master.

Passing in username in url doesn't seem to work.  Also passing in password ie /ssh/<username>?pass=<password> does not work.

**To Reproduce**
1. Navigate to wetty url passing in /ssh/<username> 
ex: http://172.24.2.101:3000/wetty/ssh/dshaw
2. Username is not passed in

**Expected behavior**
I'm expecting my username to be passed in, it's not

-OS: Centos 7

![wetty-login-not-passed](https://user-images.githubusercontent.com/15020640/91476563-02ca5c00-e852-11ea-8946-23d24815bd3d.PNG)

**Comment by butlerx** [comment]
Ive only been able to replicate the pass word issue locally.
any logs would be good

**Comment by butlerx** [comment]
Actually issue with passing password though http param is not having sshpass installed locally.

**Comment by daynok** [comment]
Let me get logs and post, I have sshpass installed locally.  
Thanks for the response!

**Comment by daynok** [comment]
@butlerx  Let me know if there is anything else I can do to try to help debug.  

Thanks in advance!

Under each test case
- Username is never passed 
- Password is never passed
- Wetty always presents the same login screen (need to provider username and password)
![wetty-login-not-passed](https://user-images.githubusercontent.com/15020640/91607603-ffee6a80-e928-11ea-8598-a4cf4a596aee.PNG)

I don't see anything in journalctl, posted logs output from running wetty in a screen as root.

Basic info:
Wetty started via: node index.js -p 3000 --host 172.24.2.101
Wetty started from: /usr/local/share/.config/yarn/global/node_modules/wetty
SShpass version: 1.06
![sshpass-installed](https://user-images.githubusercontent.com/15020640/91606689-5d81b780-e927-11ea-81ef-64e697e8b0d8.PNG)


On branch master
[root@devdocker wetty]# git log
commit 758e9a486d9ec097da4a68b5407ee6d65d4a268c
Author: butlerx <butlerx@notthe.cloud>
Date:   Thu Aug 27 09:54:55 2020 +0100

    update lock file

Case 1: Pass in username only
http://172.24.2.101:3000/wetty/ssh/dshaw

`[root@devdocker wetty]# node index.js -p 3000 --host 172.24.2.101
{"port":3000,"base":"/wetty/","title":"WeTTy - The Web Terminal Emulator","level":"info","message":"Starting server","label":"Wetty","timestamp":"2020-08-19T10:23:29.947Z"}
{"port":3000,"connection":"http","level":"info","message":"Server started","label":"Wetty","timestamp":"2020-08-19T10:23:29.964Z"}
{"meta":{"req":{"url":"/wetty/ssh/dshaw","headers":{"host":"172.24.2.101:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","dnt":"1","connection":"keep-alive","upgrade-insecure-requests":"1"},"method":"GET","httpVersion":"1.1","originalUrl":"/wetty/ssh/dshaw","query":{}},"res":{"statusCode":200},"responseTime":8},"level":"info","message":"HTTP GET /wetty/ssh/dshaw","label":"Wetty","timestamp":"2020-08-19T10:24:12.407Z"}
{"meta":{"req":{"url":"/wetty/public/index.css","headers":{"host":"172.24.2.101:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0","accept":"text/css,*/*;q=0.1","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","dnt":"1","connection":"keep-alive","referer":"http://172.24.2.101:3000/wetty/ssh/dshaw"},"method":"GET","httpVersion":"1.1","originalUrl":"/wetty/public/index.css","query":{}},"res":{"statusCode":200},"responseTime":17},"level":"info","message":"HTTP GET /wetty/public/index.css","label":"Wetty","timestamp":"2020-08-19T10:24:12.495Z"}
{"meta":{"req":{"url":"/wetty/public/index.js","headers":{"host":"172.24.2.101:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","dnt":"1","connection":"keep-alive","referer":"http://172.24.2.101:3000/wetty/ssh/dshaw"},"method":"GET","httpVersion":"1.1","originalUrl":"/wetty/public/index.js","query":{}},"res":{"statusCode":200},"responseTime":68},"level":"info","message":"HTTP GET /wetty/public/index.js","label":"Wetty","timestamp":"2020-08-19T10:24:12.656Z"}
{"message":"Connection accepted.","level":"info","label":"Wetty","timestamp":"2020-08-19T10:24:12.766Z"}
{"pid":22062,"address":"localhost","level":"info","message":"Process Started on behalf of user","label":"Wetty","timestamp":"2020-08-19T10:24:12.774Z"}
{"meta":{"req":{"url":"/favicon.ico","headers":{"host":"172.24.2.101:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0","accept":"image/webp,*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","dnt":"1","connection":"keep-alive","cookie":"io=kFXZzM4yZrzMB8gzAAAA"},"method":"GET","httpVersion":"1.1","originalUrl":"/favicon.ico","query":{}},"res":{"statusCode":200},"responseTime":6},"level":"info","message":"HTTP GET /favicon.ico","label":"Wetty","timestamp":"2020-08-19T10:24:12.795Z"}`

Case 2: Pass in username and password using get arg 'pass'
http://172.24.2.101:3000/wetty/ssh/dshaw?pass=dshaw

`{"code":0,"pid":22067,"level":"info","message":"Process exited","label":"Wetty","timestamp":"2020-08-19T10:27:25.598Z"}
{"meta":{"req":{"url":"/wetty/ssh/dshaw?pass=dshaw","headers":{"host":"172.24.2.101:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","dnt":"1","connection":"keep-alive","cookie":"io=rLqMZwfDB3Uz4ACMAAAC","upgrade-insecure-requests":"1","if-none-match":"W/\"326-NEPQ7SnapzbJhgNZr41V6mm+uUU\""},"method":"GET","httpVersion":"1.1","originalUrl":"/wetty/ssh/dshaw?pass=dshaw","query":{"pass":"dshaw"}},"res":{"statusCode":304},"responseTime":1},"level":"info","message":"HTTP GET /wetty/ssh/dshaw?pass=dshaw","label":"Wetty","timestamp":"2020-08-19T10:27:25.601Z"}
{"code":0,"pid":22067,"level":"info","message":"Process exited","label":"Wetty","timestamp":"2020-08-19T10:27:25.603Z"}
{"meta":{"req":{"url":"/wetty/public/index.css","headers":{"host":"172.24.2.101:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0","accept":"text/css,*/*;q=0.1","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","dnt":"1","connection":"keep-alive","referer":"http://172.24.2.101:3000/wetty/ssh/dshaw?pass=dshaw","cookie":"io=rLqMZwfDB3Uz4ACMAAAC","if-modified-since":"Thu, 27 Aug 2020 15:35:58 GMT","if-none-match":"W/\"1088-174308fb677\""},"method":"GET","httpVersion":"1.1","originalUrl":"/wetty/public/index.css","query":{}},"res":{"statusCode":304},"responseTime":1},"level":"info","message":"HTTP GET /wetty/public/index.css","label":"Wetty","timestamp":"2020-08-19T10:27:25.659Z"}
{"meta":{"req":{"url":"/wetty/public/index.js","headers":{"host":"172.24.2.101:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","dnt":"1","connection":"keep-alive","referer":"http://172.24.2.101:3000/wetty/ssh/dshaw?pass=dshaw","cookie":"io=rLqMZwfDB3Uz4ACMAAAC","if-modified-since":"Thu, 27 Aug 2020 15:35:58 GMT","if-none-match":"W/\"72d3f-174308fb677\""},"method":"GET","httpVersion":"1.1","originalUrl":"/wetty/public/index.js","query":{}},"res":{"statusCode":304},"responseTime":1},"level":"info","message":"HTTP GET /wetty/public/index.js","label":"Wetty","timestamp":"2020-08-19T10:27:25.698Z"}
{"message":"Connection accepted.","level":"info","label":"Wetty","timestamp":"2020-08-19T10:27:25.808Z"}
{"pid":22069,"address":"localhost","level":"info","message":"Process Started on behalf of user","label":"Wetty","timestamp":"2020-08-19T10:27:25.812Z"}`

Case 3: Pass in username and password using get arg 'sshpass'
http://172.24.2.101:3000/wetty/ssh/dshaw?sshpass=dshaw

`{"meta":{"req":{"url":"/wetty/ssh/dshaw?sshpass=dshaw","headers":{"host":"172.24.2.101:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","dnt":"1","connection":"keep-alive","cookie":"io=kFXZzM4yZrzMB8gzAAAA","upgrade-insecure-requests":"1"},"method":"GET","httpVersion":"1.1","originalUrl":"/wetty/ssh/dshaw?sshpass=dshaw","query":{"sshpass":"dshaw"}},"res":{"statusCode":200},"responseTime":1},"level":"info","message":"HTTP GET /wetty/ssh/dshaw?sshpass=dshaw","label":"Wetty","timestamp":"2020-08-19T10:25:52.424Z"}
{"meta":{"req":{"url":"/wetty/public/index.css","headers":{"host":"172.24.2.101:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0","accept":"text/css,*/*;q=0.1","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","dnt":"1","connection":"keep-alive","referer":"http://172.24.2.101:3000/wetty/ssh/dshaw?sshpass=dshaw","cookie":"io=kFXZzM4yZrzMB8gzAAAA","if-modified-since":"Thu, 27 Aug 2020 15:35:58 GMT","if-none-match":"W/\"1088-174308fb677\""},"method":"GET","httpVersion":"1.1","originalUrl":"/wetty/public/index.css","query":{}},"res":{"statusCode":304},"responseTime":2},"level":"info","message":"HTTP GET /wetty/public/index.css","label":"Wetty","timestamp":"2020-08-19T10:25:52.491Z"}
{"meta":{"req":{"url":"/wetty/public/index.js","headers":{"host":"172.24.2.101:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","dnt":"1","connection":"keep-alive","referer":"http://172.24.2.101:3000/wetty/ssh/dshaw?sshpass=dshaw","cookie":"io=kFXZzM4yZrzMB8gzAAAA","if-modified-since":"Thu, 27 Aug 2020 15:35:58 GMT","if-none-match":"W/\"72d3f-174308fb677\""},"method":"GET","httpVersion":"1.1","originalUrl":"/wetty/public/index.js","query":{}},"res":{"statusCode":304},"responseTime":1},"level":"info","message":"HTTP GET /wetty/public/index.js","label":"Wetty","timestamp":"2020-08-19T10:25:52.532Z"}
{"message":"Connection accepted.","level":"info","label":"Wetty","timestamp":"2020-08-19T10:25:52.640Z"}
{"pid":22065,"address":"localhost","level":"info","message":"Process Started on behalf of user","label":"Wetty","timestamp":"2020-08-19T10:25:52.644Z"}`

**Comment by ebartz** [comment]
I do have the same issue.
