### ISSUE TITLE
v2.0.1 web server path isssues prevetning assets from loading - resolved via symlink to build dir

### ISSUE THREAD

**Issue by userdocs** [butlerx/wetty#279]
**Describe the bug**

When running wetty 2.0.1 with any settings there is a path issue preventing assets from loading.

The problem specifically appears to be that when wetty is installed globally and run using

```
~$ wetty
```

The web server is looking for the assets in the relevant users home directory (which does not exist).

```
~/build/
```

Tested with:

As root - `curl -sL https://deb.nodesource.com/setup_14.x`

As a local user - `https://github.com/nvm-sh/nvm`

**To Reproduce**

Install wetty globally.

Run wetty 2.0.1 like this:

```
wetty --host 0.0.0.0 -port 3000
```

Visit the url `http://IP:3000/wetty` and you will see this.

![1](https://user-images.githubusercontent.com/16525024/95323396-ffd17b00-0895-11eb-8477-cd100ec2a3aa.jpg)

**Expected behaviour**

That assets are correctly loaded and path is correctly determined.

**Method to resolve**

Create a symlink to the wetty build directory

As root and using nodejs and yarn installed via apt-get

```
ln -s /usr/local/share/.config/yarn/global/node_modules/wetty/build /root/build
```

As a local user using `nvm`

```
ln -s ~/.nvm/versions/node/v14.13.0/lib/node_modules/wetty/build ~/build
```

Now run wetty again

```
wetty --host 0.0.0.0 -port 3000
```

And you will get this outcome:

![2](https://user-images.githubusercontent.com/16525024/95323573-4c1cbb00-0896-11eb-8099-eeec98345514.jpg)

**Comment by userdocs** [comment]
fixed code block issue preventing images loading.

**Comment by Bazimek** [comment]
Does not work for me :(

**Comment by userdocs** [comment]
What doesn't work for you?

**Comment by Bazimek** [comment]
As root and using nodejs and yarn installed via apt-get

ln -s /usr/local/share/.config/yarn/global/node_modules/wetty/build /root/build
As a local user using nvm

ln -s ~/.nvm/versions/node/v14.13.0/lib/node_modules/wetty/build ~/build

**Comment by Bazimek** [comment]
Still got the text box with the recoonect button. Before this version it was working great.

**Comment by userdocs** [comment]
It depends how you installed wetty. My examples are specific to what i used.

You need to know where the build folder is located and that changes depending the node/npm you have.

For examples, with nvm + yarn it is here `ln -s ~/.config/yarn/global/node_modules/wetty/build ~/build`

**Comment by Bazimek** [comment]
Oh god that is too much for me .. I used sudo yarn global add wetty and i upgrade the node with
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by butlerx** [comment]
the issue is stemming from how express handles the paths to assets. it is looking in `$PWD/build`. This is incorrect and should be from the Package root.

**Comment by butlerx** [comment]
this would only happen with global installs, running from the repo would not have the issue

**Comment by Bazimek** [comment]
> this would only happen with global installs, running from the repo would not have the issue

How can I run it from repo please?

**Comment by Bazimek** [comment]
Oh yarn build and then node main.js --host 0.0.0.0 --port 3000 .. right?

**Comment by Bazimek** [comment]
I try node main.js --host 0.0.0.0 --port 3000 --title 'some tittle', but that does not working (text box with reconnect)
Then i try npm start --host 0.0.0.0 --port 3000 --title 'some tittle', that works (via http), but the parameters does not work

**Comment by butlerx** [comment]
v2.0.2 should have the fix

**Comment by Bazimek** [comment]
Thank you very much. Love it! Can I ask here? Why i can use wetty when I used the yarn global add wetty? I can use wetty only when I use it with sudo .. sudo yarn global add wetty

**Comment by userdocs** [comment]
2.0.2 has resolved the issue for me.

I can now successfully download wetty 2.0.2 from npm, install it globally and then run it using `$ wetty ...`

Thank you.

**Comment by butlerx** [comment]
Thanks for reporting and verifying the fix
