### ISSUE TITLE
Broken layout

### ISSUE THREAD

**Issue by johnroyer** [butlerx/wetty#28]
When open htop for a while, the screen become a mass : 

![2017-12-08 10 31 54](https://user-images.githubusercontent.com/114491/33748421-6a70c8f2-dc03-11e7-89c4-f57eabdf53d0.png)

After I type `Ctrl+L` to reset the screen, it goes well again : 

![2017-12-08 10 34 35](https://user-images.githubusercontent.com/114491/33748450-94658b20-dc03-11e7-8784-ff89f70221c7.png)

----

More information:

- wetty version `v0.4.2`
- layout broken on : 
  - htop
  - layout also broken while using `speedometer` monitor
- It goes well on:
  - `dstat` monitor
  - `mytop` monitor
  - `vim` editor

----

Is this problem cause by font family ? Thanks.

**Comment by butlerx** [comment]
Sorry slow response can you test with v0.5

**Comment by johnroyer** [comment]
`v0.5.0` fixed this issue. Thanks.

But it come with another problem. I will open a new issue.
