### ISSUE TITLE
Can't login as `root'

### ISSUE THREAD

**Issue by johnchristopher** [butlerx/wetty#28]
I am running wetty in a vagrant box (debian-7.8.xxx) from puppetlab and I can't login using root. Entering the root username triggers the `Login incorrect' message.

Is `root' hardcoded to be refused ? I can login fine using ssh.

**Comment by krishnasrinivas** [comment]
your ssh server might be configured not to allow root login. you can verify by trying to login using the ssh command "ssh -l root <serverip>" can you check?

**Comment by johnchristopher** [comment]
I can login as root from other clients.

**Comment by krishnasrinivas** [comment]
not sure what's going on, can you put console.log() statements here https://github.com/krishnasrinivas/wetty/blob/master/app.js and check?

**Comment by tinkernels** [comment]
http://serverfault.com/a/345247
hope this help.

**Comment by krishnasrinivas** [comment]
i will close this as there is not enough information to fix this.

**Comment by piemjean** [comment]
I just had the same problem and solved it by launching wetty with an unprivileged user.
Hope this can help someone.

**Comment by Alevam-Inc** [comment]
> I just had the same problem and solved it by launching wetty with an unprivileged user. Hope this can help someone.

How do I do this?
