### ISSUE TITLE
unsure whether it need this folder on running container

### ISSUE THREAD

**Issue by ravinayag** [butlerx/wetty#286]
**Describe the bug**

**To Reproduce**
1. Git clone the repo
2. docker-compose up -d 
or docker build -f ./containers/wetty/Dockerfile .

3. See error 1 & 2
```
Step 12/17 : COPY --from=builder /usr/src/app/dist /usr/src/app/dist
COPY failed: stat /docker/overlay2/319a7847ba4cea16f13fe5e7a82dd022a5421ebdcbafaa2154113d6353f26ad9/merged/usr/src/app/dist: no such file or directory

Step 14/17 : COPY index.js /usr/src/app
ERROR: Service 'wetty' failed to build: COPY failed: stat /docker/tmp/docker-builder894929225/index.js: no such file or directory
```

**Expected behavior**
the build should run without error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 16 VM

**Smartphone (please complete the following information):**

**Additional context**

**Comment by butlerx** [comment]
yep thats the old path this is fixed on master now
