### ISSUE TITLE
Omitting system-wide ssh configuration

### ISSUE THREAD

**Issue by janoskk** [butlerx/wetty#287]
We're using wetty from a snap package and we have to ignore/omit the system-wide ssh configuration as it may contain any configuration "features" for another version of ssh. Therefore I'd like to introduce a new parameter called `--ssh-no-conf` to ignore them. In this case I would add the `-F /dev/null` parameters to the ssh command line that resulting no configuration. 

@butlerx What is your opinion? Do you have any better idea?

**Comment by butlerx** [comment]
Im not a big fan of the flag name, but i cant think of a better one.
Please also add the setting to the config.json file at `ssh.noConf`.

I think we should also surface the ability to specify the path to the system wide conf, would you mind adding this at the same time ?

**Comment by janoskk** [comment]
Oh yes. Maybe it'd be better to add only `--ssh-config configfile` and document it properly.

What about that:
```
  .option('ssh-config', {
    description: 'Specifies an alternative ssh configuration file. For further details see "-F" option in ssh(1)',
    type: 'string',
  })
```

Long a bit, but needed... Anything to add?

**Comment by butlerx** [comment]
just to also add it to ensure its added here https://github.com/butlerx/wetty/blob/main/src/shared/interfaces.ts#L1
