### ISSUE TITLE
Docker : update wetty

### ISSUE THREAD

**Issue by toxic0berliner** [butlerx/wetty#288]
Hello,

I just started a docker container using what I believe is the latest image :  

wettyoss/wetty:latest@sha256:7a5d427040b6bc4e695ab36edd17998e4f7a72e410370273b4bbcab829df4741

But it seems it's running quite an old version. This is the `/usr/src/app/package.json`
```
{
  "name": "wetty",
  "version": "1.4.1",
  "description": "WeTTY = Web + TTY. Terminal access in browser over http/https",
  "homepage": "https://github.com/butlerx/wetty",
  "repository": {
    "type": "git",
    "url": "git://github.com/butlerx/wetty.git"
  },
[...]
```
Any chance we could get an updated build ?

Thanks in advance.

**Comment by butlerx** [comment]
Ive manually pushed new containers, I will need to review why automated builds arnt working

**Comment by toxic0berliner** [comment]
Works lika a charm, thanks a lot !
Congrats on the very quick push ! And good luck making the automated builds work again ! It took me a while to decide wich docker image to use since lots of people have posted wetty images, glad I chose this one, the official one ;)
```
/usr/src/app # head -5 package.json 
{
  "name": "wetty",
  "version": "2.0.2",
  "description": "WeTTY = Web + TTY. Terminal access in browser over http/https",
  "homepage": "https://github.com/butlerx/wetty",

```
