### ISSUE TITLE
Chrome 76.0.3809.136 lodash.js Syntax error

### ISSUE THREAD

**Issue by toxic0berliner** [butlerx/wetty#289]
**Describe the bug**
wetty 2.0.2 cannot start in chrome OS (chromebook) running Chrome Version 76.0.3809.136 (Build officiel) (64 bits)

**To Reproduce**
1. Go to http://...../wetty
2. Open The developper tool
3. See the error : Uncaught SyntaxError: Unexpected token ?
4. See error in lodash.js at line 3 column 99 : ;return t=t**?**?Pe

**Expected behavior**
should load wetty properly.

**Desktop (please complete the following information):**
 - OS: Chrome OS 
 - Browser Chrome Version 76.0.3809.136 (Build officiel) (64 bits)

I guess that would probably be something that I need to raise at lodash and not here, and I also don't have pretty high hopes of getting a fix since chrome 76 even thought not too old (2019-07-30) is reported as discontinued...
But I know people are reactive and helpful here, so maybe I'll get directions to fix it or where to post the issue ;)

Thanks in advance for your kind help!

**Comment by butlerx** [comment]
could you post a screenshot of the console errors.

Version 2 of wetty dropped a large amount of backwards compatibility so as to take advantage of web_modules in the browser. Ill need to do some reading on browser support but one route if this is the cause is using weety 1.4.1 as that is a compiled with webpack. It'd be slower but supports older browsers

**Comment by toxic0berliner** [comment]
Hmm, did not see your answer last year, sorry.
Trying it now, I think it'll be a bit too much involved for me, as I see no release and only a tach for version 1.4.1 so my understanding is that I should build it myself. I also can't see a tag on the docker hub for 1.4.1 so it'll be more involved than just updating my compse file anyway. 
Will give it a try when my lazyness leaves me someday, or if you hint me towards a hidden v1.4.1 tag on docker ;)

Will report if I get 1.4.1 working with tmy ancient chromebook. Thx for tha answer.
