### ISSUE TITLE
Error: ioctl(2) failed

### ISSUE THREAD

**Issue by johnroyer** [butlerx/wetty#30]
I add wetty bootstrap script into crontab:

```cron
@reboot   nohup node /home/johnroyer/sites/wetty/app.js -p 3000 >> /home/johnroyer/sites/wetty/run.log 2>&1
```

After reboot, I will see error message on the web page:
```
/usr/bin/env: ../bin/ssh: No such file or directory
```

And `run.log` will see another message: 
```
Error: Error: ioctl(2) failed.
```

But if I manually invoke this command, everything goes well.

Is it possible a config error ?

----

wetty version: `v0.5.0`

**Comment by butlerx** [comment]
it seems to be an error calling the shell prompt that is used as a wrapper to ssh. I was actually just looking at removing that, coincidentally.
ill have a look now

**Comment by johnroyer** [comment]
Let me know if you need someone to test. Thanks.

**Comment by butlerx** [comment]
thanks.
 ive just tagged v.0.5.1 which pay patch the issue for the minute but ive had no luck replicating it so replacing the shell script will be best

**Comment by johnroyer** [comment]
I update to `v0.5.1` and rewrite my script: 

```
nohup /usr/bin/node /home/johnroyer/sites/wetty/bin/index.js -p 3000 >> /home/johnroyer/sites/wetty/run.log 2>&1
```

It works fine using a root account, but It still have the same problem while using general account.

**Comment by butlerx** [comment]
alright thanks for the feedback

**Comment by t3chn0m4g3** [comment]
@butlerx I am experiencing the same problem as @johnroyer. However, I was able to fix it by running `index.js`from the base folder which leads to my problem that the browser presents me with a password dialog but the entered password is not accepted.

I would like to assist further if necessary, is there a debug switch I can enable? The console log does not show any errors, just normal start and end of session.

**Comment by butlerx** [comment]
this should no longer be an issue with v1.0.0, feedback appriciated

**Comment by johnroyer** [comment]
Error above: `Error: Error: ioctl(2) failed.`  is no longer shown on v1.0.3

**Comment by butlerx** [comment]
Perfect
