### ISSUE TITLE
doesn't compile with pty.js Version 0.2.7-1

### ISSUE THREAD

**Issue by schmimat** [butlerx/wetty#30]
Hi,

the verion 0.2.7-1 of pty.js doesn't compile with my aktuall Arch Linux Version, gcc Version 5.2.0?

With the version 0.3.0 of pty.js the installation workes and wetty is runnning.

Thanks for the greate work.

mfG Matthias

**Comment by krishnasrinivas** [comment]
@schmimat good to know that wetty is running fine. closing this issue.

**Comment by schmimat** [comment]
Hi,
sorry for reopen, but to compile in the file package.json the version of pty.js had to be set to 0.3.0.
Can you change it in the file? 
"pty.js": "^0.2.7-1", --> "pty.js": "^0.3.0-1" or so

Best regards Matthias

**Comment by henrikkorsgaard** [comment]
@schmimat :+1:  What Matthias said -- took me a while to track down the issue before changing the pty.js version in package.json
