### ISSUE TITLE
Static files have index.html content when served behind Nginx

### ISSUE THREAD

**Issue by vbaidak** [butlerx/wetty#301]
**Describe the bug**
Static files, such as **terminal.css**, **wetty.js** returned with **index.html** content

**To Reproduce**
Pre-conditions: 
* nginx/1.19.2 configured as reverse proxy according to the documentation
* wetty version 2.x.x

1. Go to http://<host>:<port>/wetty

**Expected behavior**
**Wetty** successfully opened

**Screenshots**
**Wetty** opened with reconnect button and no styles. Multiple errors in browser console
![image](https://user-images.githubusercontent.com/10495282/100740250-13561980-33e1-11eb-8694-8a837befb0af.png)
![image](https://user-images.githubusercontent.com/10495282/100739980-a3e02a00-33e0-11eb-97f7-4e49ac6df88f.png)

**Additional context**
**Wetty**  v. 1.4.1 works fine

**Comment by bonellia** [comment]
I encountered the same issue following atoz guide:
![image](https://user-images.githubusercontent.com/16254153/134540814-2d4a1cc8-ffcb-4ab7-90d5-24a68702b5b0.png)

**Comment by bonellia** [comment]
I resolved it by manually running this:
```
cp -r home/<username>/.config/yarn/global/node_modules/wetty/build/* /var/www/<domain-name>/html/wetty/
```
Only favicon is missing but I'll resolve it later.

**Comment by butlerx** [comment]
If this is happening it is likely the nginx proxy is miss configured, you shouldnt need to copy any files.
When you connect without the proxy what whats the url and do the static resources resolve?
