### ISSUE TITLE
Support pkg node packager

### ISSUE THREAD

**Issue by cotardp** [butlerx/wetty#304]
Hello,

For an offline system, wetty has to be packaged as a standalone binary and do not rely on any node binary.
I choose pkg to package wetty.
However, wetty is not compatilble and the following error occurs when trying to package it for linux64:

```
$ npm install
[...]
$ npm run-script build
[...]
$ pkg . --target node14-linux-x64
> pkg@4.4.9
> Error! import.meta may appear only with 'sourceType: "module"' (5:53)
  /tmp/wetty/build/server/login.js
```

The same error occurs with "build/server/socketServer/shared/path.js":
```
> Error! import.meta may appear only with 'sourceType: "module"' (5:31)
  /tmp/wetty/build/server/socketServer/shared/path.js
```

Using:
- debian 10
- node v14.15.1
- wetty v2.0.2

**Comment by butlerx** [comment]
It appears pkg needs to be told when the package is of type module. WeTTy specifies this in its `package.json` I'm unfamiliar with pkg and how to specify it for it.
