### ISSUE TITLE
/bin/login functionality seems to have gone

### ISSUE THREAD

**Issue by phlax** [butlerx/wetty#306]
### description

I was hoping to use `wetty` with just `/bin/login` in the container - ssh does not suit my requirements

a brief scan of the source seems to suggest this functionality has been removed.

the docs still mention it in various places (and i see a lot of refs to `app.js`) but starting the container as root doesnt afaict start a `/bin/login` session

**Comment by phlax** [comment]
after a bit of further investigation  - this seems to be not entirely correct.

running with the docker-compose setup it did not work,  but after rebuilding the  image it does seem to work.

hacking login.ts and spawn.ts it seems like in the docker-compose setup  it uses the first

not sure if this is an issue other than the docs not being very clear, feel free to close

**Comment by butlerx** [comment]
With docker it is explicitly configured with  flags to be an ssh client rather then use `/bin/login`. This is because you would other wise end up with a shell I'm a temp docker container which the majority of users would not be looking for.
I can look to adding a section in the docs mentioning this and how to remove these flags

**Comment by phlax** [comment]
>  I can look to adding a section in the docs mentioning this and how to remove these flags

cool, that would be great

> This is because you would other wise end up with a shell I'm a temp docker container

For my use case (screenshotting a console in integration tests) that is exactly what i want

More precisely i want not a `login` but just directly `sh`

I hacked it to do this an it works nicely.

im wondering if making the `tty` command customisable would be more generally useful.

i can open a ticket if you think it would be helpful
