### ISSUE TITLE
Wetty docker container issue

### ISSUE THREAD

**Issue by rsjay1976** [butlerx/wetty#308]
Issue Description
After using docker compose to start the wetty and ssh containers accessing  with http://<hostname>:3000/wetty and providing term/term as user name/pwd is resulting in 

sh: -p not found

The docker compse logs show automatic disconnection message

wetty-ssh_1  | Accepted password for term from 172.22.0.3 port 54440 ssh2
wetty-ssh_1  | Received disconnect from 172.22.0.3 port 54440:11: disconnected by user
wetty-ssh_1  | Disconnected from user term 172.22.0.3 port 54440
wetty_1      | {"code":127,"pid":133,"level":"info","message":"Process exited","label":"Wetty","timestamp":"2020-12-27T09:59:06.572Z"}

Screenshot
![image](https://user-images.githubusercontent.com/15307510/103168509-c5a2c480-4859-11eb-9352-14f5f9a0c044.png)

**Comment by nakkaya** [comment]
Noticed same issue on non docker environment as well. I have an `ansible` script to setup `emacs` and `wetty` on an Ubuntu box. When `ansible` updated `wetty` I got the same error as OP with `2.0.3`, downgrading to `2.0.2` fixes it.

**Comment by butlerx** [comment]
Ive pushed a fix to master that should address the issue. if you can verify the fix ill be able to release it with version `2.0.4`

**Comment by Salamandar** [comment]
Hi, the issue is also visible with the Yunohost package, and the latest commit did not solve the issue.

**Comment by Salamandar** [comment]
@butlerx this issue nis the most important right now as it is fully blocking :D 
EDIT ah just saw your message in #326, i'll try 2.1
