### ISSUE TITLE
docker-compose with extra ssh options doesn't work.

### ISSUE THREAD

**Issue by johnbritto1** [butlerx/wetty#309]
Hello,

I have build the image from container/wetty/dockerfile
and alerted docker-compose to have command as:
command: yarn start --sshhost 172.19.0.1 --sshport 2222 --sshuser dockuser --title Test-Console --base /console/ --sshauth publickey --sshkey ~/.ssh/id_rsa_wetty

The image gets deployed. but connecting to localhost:3000/console shows  ssh-client login: 

This is what the docker image process shows.

root | 525 | 15473 | 0 | 15:18 | pts/1 | 00:00:00 | login -h localhost
root | 15473 | 15446 | 0 | Jan01 | ? | 00:00:04 | node . yarn start --sshhost 172.19.0.1 --sshport 2222 --sshuser dockuser --sshauth publickey --sshkey /root/.ssh/id_rsa_wetty --title Test-Console --base /console/

I am concern over the process "login -h localhost" This was suppose to be the custom ssh commands.

Any idea.

Thanks,

**Comment by johnbritto1** [comment]
Hello, correction, so i made a mistake. 

the docker-compose command should be: yarn start --ssh-host 172.19.0.1 --ssh-port 2222 --ssh-user dockuser --title Test-Console --base /console/ --ssh-auth publickey --ssh-key ~/.ssh/id_rsa_wetty

But even after this, accessing the console, it ask for username and then the connection drops and reconnect button shown. 
Not sure why the console shows port 22.  As I am suing publickey, this should not ask for username.

![Capture](https://user-images.githubusercontent.com/5947168/103641091-30997d00-4f77-11eb-94d7-47150effb06e.JPG)

any idea.

**Comment by butlerx** [comment]
This is a weird one, it appears that ssh is ignoring the `-p` flag passed to it from wetty and just using the default port 22. 
inspecting the pid i can see that the correct args are being passed. And running the command manually does produce the expected outcome

**Comment by butlerx** [comment]
```
$  ps -fp 1832320
UID          PID    PPID  C STIME TTY          TIME CMD
butlerx  1832320 1832225  0 10:35 pts/24   00:00:00 ssh butlerx@localhost -t   -p 2222 -o PreferredAuthentications=password -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
$  ssh butlerx@localhost -t   -p 2222 -o PreferredAuthentications=password -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
ssh: connect to host localhost port 2222: Connection refused```

**Comment by butlerx** [comment]
This issue looks to be  the same as #308 going to close and continue in that issue
