### ISSUE TITLE
wetty install success，run "node app.js -p 3000" throw error

### ISSUE THREAD

**Issue by zhanenkui** [butlerx/wetty#314]
ubuntu: 18.04  
node :  v14.15.4  
npm  :  v6.14.10

> git clone https://github.com/krishnasrinivas/wetty
> cd wetty
> npm install

installation complete.  
start wetty:

> node app.js -p 3000

```shell
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/home/zek/wetty/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I found some information, tried many times, but still did not solve the problem, anyone know?

**Comment by butlerx** [comment]
the issue is your trying to run a file that doesnt exist. 
you should run `node . -p 3000` or `npm run` as well you do not appear to be building the package if you are installing from source you need to run `npm build`

**Comment by zhanenkui** [comment]
Thank you for your prompt reply,I've made new progress.  
I'm a newcomer and I'm a stranger to this

I see a lot about the general flow of `wetty` installation as follows  
**example:**[https://www.unixmen.com/install-wetty-on-ubuntu-linux-15-04-and-centos-7/](https://www.unixmen.com/install-wetty-on-ubuntu-linux-15-04-and-centos-7/)

1.Before installing 'wetty', install the associated `node.js` environment.  
2.Clone the source code of the project and install it using 'npm install'

> git clone https://github.com/krishnasrinivas/wetty
> cd wetty
> npm install

3.Then run `node app.js -p 3000` to start the `wetty` service  

According to the general process, the effect I get is not the same, so I have some questions.  
Are there any other build operations after `npm isntall`?

**Comment by butlerx** [comment]
That guide is quite out of date i suggest you follow https://github.com/butlerx/wetty/blob/main/docs/atoz.md for setting up wetty

**Comment by zhanenkui** [comment]
Thank you for your advice  
I have configured 'wetty' according to this document and so far everything looks fine
