### ISSUE TITLE
Can't login as another user when logged into Yunohost LDAP

### ISSUE THREAD

**Issue by Salamandar** [butlerx/wetty#319]
I think this is the culprit : 75785c463ceaf49d0ec63de60c1d594f3db61601

As an administrator, I'm logged into my LDAP as my own user, but I usually want to log in to ssh as `admin` with the `/wetty/ssh/admin` sub-url. I can't do that anymore.

Is it possible to add a setting to enable/disable this security enforcement ?

**Comment by Salamandar** [comment]
Yeah, @butlerx are you still maintaining this software?

**Comment by butlerx** [comment]
yes just busy,
So to be clear your use-case is you want to be able to ssh as the admin when authed externally? 
I assume you don't want any and every user to be able to impersonate another.
It could be possible to add a allow list of users that can ssh as others ala a sudours

**Comment by Salamandar** [comment]
Yes, that's the use case.

> I assume you don't want any and every user to be able to impersonate another.

Yes i do actually.
The admin user of Yunohost can't log into the web interface, and standard users can't sudo, so the only way of login as admin into wetty is to log out or use private browsing.

Anyways, there will be no impersonating because wetty will ask for the admin password anyways...
