### ISSUE TITLE
Release 1.0.0: syntax error on startup with nodejs 6.13.0

### ISSUE THREAD

**Issue by mirtouf** [butlerx/wetty#32]
Hi,

I just tried the fresh new release and starting the app is impossible with nodejs 6.13.0:
````
/usr/bin/node index.js

/var/www/wetty/lib/index.mjs:74
    );
    ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at runInThisContext (vm.js:97:10)
````
Can it be related with the nodejs version ?

**Comment by butlerx** [comment]
yes, this would be to do with version let me see if I can find a good minimum version and set it in the package.json

**Comment by butlerx** [comment]
ok ive changes how prettier formats the code and it should be compatible with node 6 at a minium

**Comment by butlerx** [comment]
based off #33 i assume this is closed
