### ISSUE TITLE
Fails to connect when websockets are blocked

### ISSUE THREAD

**Issue by jarrettgilliam** [butlerx/wetty#32]
I'm a new fan of wetty. The only problem is that I work behind a firewall that (evidently) blocks web sockets. Bummer. This was a confusing discovery for me at first because I have been using [tty.js](https://github.com/chjj/tty.js/) (another node.js web terminal that uses web sockets). After looking at the code and a quick Google search I discovered that wetty uses the standard WebSocket API while tty.js uses a 3rd party called [socket.io.js](http://socket.io/) which, if web sockets aren't available, falls back to the following technologies:
- Flash Socket
- AJAX long-polling
- AJAX multipart streaming
- IFrame
- JSONP polling

I guess my question is, have you considered using socket.io.js to make wetty available behind firewalls that block web sockets?

Thanks for your time.

**Comment by krishnasrinivas** [comment]
It's a good idea to use socket.io, is it possible for you to send a pull-request that uses socket.io? else I can make that change.

**Comment by jarrettgilliam** [comment]
I could give it a shot, but I'm not really a node.js developer, or even a javascript developer for that matter.

**Comment by krishnasrinivas** [comment]
You can give it a shot

**Comment by harrysummer** [comment]
@jarrettgilliam Hi, I just implemented a Socket.IO communication of wetty for my personal use. Check it out here if you are interested: https://github.com/harrysummer/wetty

**Comment by jarrettgilliam** [comment]
Will do. Thanks @harrysummer.

**Comment by krishnasrinivas** [comment]
e496251772a54b4e814404725d0f4a592989e82e fixes this
