### ISSUE TITLE
localhost connection closing on login with error bash: line1: -p: command not found

### ISSUE THREAD

**Issue by TakudzwaMakoni** [butlerx/wetty#320]
After starting a session on localhost port 3000, i am prompted to enter my login details, which i know to be correct because when i purposefully enter incorrect details i get permission denied.

When i enter my correct details, the message 

`bash: line 1: -p: command not found`

and the connection subsequently closes.

**To Reproduce**
1. from terminal: `wetty`
2. open webpage 'localhost:3000/wetty'
3. enter username and password on prompt

**Expected behavior**
A successful login to a terminal session.

**Desktop**
 - OS: Arch-linux
 - Browser: firefox

**Comment by peterforeman** [comment]
Same here.

**Desktop**

OS: MacOS 11 Big Sur
Browser: Latest Chrome, latest Safari

**Comment by Claus5607** [comment]
I get the same error message. Execution wetty in Firefox. Wetty program installed on a Raspberry Pi 4 yunohost server
![Bildschirmfoto vom 2021-01-31 15-30-53](https://user-images.githubusercontent.com/78308087/106387325-968fed80-63d9-11eb-9a01-066c542b45f9.png)

**Comment by butlerx** [comment]
this is the same issue as #308. 
please downgrade to v2.0.2 while I work on a solution
