### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by mcondarelli** [butlerx/wetty#322]
I must be missing something really obvious (but not to me, of course).

I am on a fairly recent and up-to-date Linux Mint.

I cloned repo, but:
```
mcon@cinderella:/tmp/wetty$ yarn global add wetty
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'global'
```

What did I do so wrong? .. or, more likely, what did I fail to do?

**Comment by butlerx** [comment]
there appears to be something wrong with your yarn installation.
Can you check what version you have installed https://classic.yarnpkg.com/en/docs/cli/global/
