### ISSUE TITLE
Automatic reconnect creates multiple terminal divs

### ISSUE THREAD

**Issue by acaos** [butlerx/wetty#333]
**Describe the bug**
When wetty disconnects and automatically reconnects, a second terminal `<div>` element is created. This results in the scrollbar appearing very odd.

**To Reproduce**
1. Create a Docker container running wetty.
2. Start a wetty session in the browser (I use Firefox, but this happens in Chrome and Chromium as well).
3. Restart the container. Note that wetty shows the `Reconnect` button briefly.
4. Wetty automatically reconnects.
    - A second `<div class="terminal xterm">` is created.
    - Content from the first session is duplicated and pushed over to the scrollbar area.

**Expected behavior**
- The scrollbar area is not polluted with content from the previous session.
- No second div is created.

**Screenshots**
![image](https://user-images.githubusercontent.com/295044/113742932-b937ce80-96c8-11eb-96d3-3c49ea39b70e.png)
![image](https://user-images.githubusercontent.com/295044/113742965-c0f77300-96c8-11eb-99c4-b4e1b4907ceb.png)

**Desktop:**
- OS: Windows 10 Professional
- Browser: Firefox (latest)
- Version: Wetty 2.0.3

**Additional Information:**
- Using the browser's reload button works correctly. No additional `<div>` is created in this case.

**Comment by acaos** [comment]
This is still an issue for me in the most recent 2.1.1 release of wetty.

**Comment by acaos** [comment]
This is still an issue for me.

**Comment by gdschut** [comment]
I have the same issue :(

**Comment by acaos** [comment]
This is still an issue for me as of 2.1.2.

**Comment by butlerx** [comment]
Sorry for the stale notices that plugins a lot more aggressive then i intended.

I''ll have fix in the next release 2.1.3
