### ISSUE TITLE
Can't start wetty only I get is this error

### ISSUE THREAD

**Issue by Bazimek** [butlerx/wetty#334]
{"error":{"code":"ERR_DLOPEN_FAILED"},"level":"error","message":"uncaughtException: The module '/usr/local/share/.config/yarn/global/node_modules/node-pty/build/Release/pty.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 83. This version of Node.js requires\nNODE_MODULE_VERSION 88. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).\nError: The module '/usr/local/share/.config/yarn/global/node_modules/node-pty/build/Release/pty.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 83. This version of Node.js requires\nNODE_MODULE_VERSION 88. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).\n    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)\n    at Module.load (node:internal/modules/cjs/loader:972:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:813:14)\n    at Module.require (node:internal/modules/cjs/loader:996:19)\n    at require (node:internal/modules/cjs/helpers:92:18)\n    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/node-pty/lib/unixTerminal.js:26:11)\n    at Module._compile (node:internal/modules/cjs/loader:1092:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)\n    at Module.load (node:internal/modules/cjs/loader:972:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:813:14)","stack":"Error: The module '/usr/local/share/.config/yarn/global/node_modules/node-pty/build/Release/pty.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 83.

**Comment by 19UV** [comment]
Have you tried running rebuilding/reinstalling the dependancies? Can you give more information such as the operating system?
