### ISSUE TITLE
Keeping connection open after the command is executed.

### ISSUE THREAD

**Issue by bonellia** [butlerx/wetty#356]
Greetings,
Firstly, thanks for developing and maintaining the this awesome project.

**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, but the session ends "prematurely" for my use case after passing a command using `--command` flag.

**Describe the solution you'd like**

I desperately needed to be able to pass commands after initiating an SSH connection and apparently WeTTy achieves that. However, I realize the session is closed right after the command is executed. I was wondering if I can have the connection open after the execution. I thought about using a workaround like nesting another command and keeping session open with a command like `ls && bash` so it doesn't disconnect. As a matter of fact, I just thought about that and tested it. Apparently I just answered my own question. (Still, I am going to post the issue so that somebody else can benefit from it or I can learn about potential problems spawning another process or something.)

**Describe alternatives you've considered**
Using `<initial command> && bash`

**Additional context**
Running server:  
![image](https://user-images.githubusercontent.com/16254153/134337830-a5c00d7a-02ad-463c-95ba-980b879e48a4.png)  
Command execution:  
![image](https://user-images.githubusercontent.com/16254153/134337886-d8c3c85e-a078-42a5-90a3-3b8b74c64230.png)  
After command runs:  
![image](https://user-images.githubusercontent.com/16254153/134337939-f8cf8377-e465-4073-9378-00799061ba45.png)

Is that a common practice to use such a command to keep the session open? I see the prompt disappearing when I try to ssh a host using a command as follows:  
![image](https://user-images.githubusercontent.com/16254153/134338373-d0c41814-ff4a-4c25-920e-bb808408cef0.png)

I know this is not necessarily a feature request anymore (or a bug) but I could still use some comments on such scenario.
Thanks in advance, Taha.

**Comment by butlerx** [comment]
Yeah, that's not great but I'm unsure how to address this your solution of `&& bash` was how the user of the original function request used it.
