### ISSUE TITLE
Can't install with node 4

### ISSUE THREAD

**Issue by vpo92** [butlerx/wetty#36]
Hi,

Wetty was perfectly working, but I have updated to last node version, and now I can't re-install it.
Is the last version of node supported ? I hope because I really like wetty !

Here is my stack trace.

Thanks !

nodejs@dev:~$ npm install -g wetty
npm WARN deprecated static-favicon@1.0.0: use serve-favicon module
/home/nodejs/.node-v4.2.2-linux-x64/bin/wetty -> /home/nodejs/.node-v4.2.2-linux-x64/lib/node_modules/wetty/bin/wetty.js

> pty.js@0.2.13 install /home/nodejs/.node-v4.2.2-linux-x64/lib/node_modules/wetty/node_modules/pty.js
> node-gyp rebuild

make: Entering directory '/home/nodejs/.node-v4.2.2-linux-x64/lib/node_modules/wetty/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../src/unix/pty.cc:20:0:
../../nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../../nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../../nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../../nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../../nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../../nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../../nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(char_, size_t, int)’:
../../nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../../nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../../nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(const char_, uint32_t)’:
../../nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate_, const char_&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../../nan/nan.h:768:67: note: candidates are:
In file included from ../../nan/nan.h:25:0,
                 from ../src/unix/pty.cc:20:
/home/nodejs/.node-gyp/4.2.2/include/node/node_buffer.h:31:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, v8::Localv8::String, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                        ^
/home/nodejs/.node-gyp/4.2.2/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/nodejs/.node-gyp/4.2.2/include/node/node_buffer.h:43:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, char_, size_t) <near match>
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                        ^
/home/nodejs/.node-gyp/4.2.2/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char_’ to ‘char_’
In file included from ../src/unix/pty.cc:20:0:
../../nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(uint32_t)’:
../../nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocalv8::Object’ to ‘v8::Localv8::Object’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../../nan/nan.h: In function ‘v8::Localv8::Object NanBufferUse(char_, uint32_t)’:
../../nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
pty.target.mk:90: recipe for target 'Release/obj.target/pty/src/unix/pty.o' failed
make: *_\* [Release/obj.target/pty/src/unix/pty.o] Error 1
make: Leaving directory '/home/nodejs/.node-v4.2.2-linux-x64/lib/node_modules/wetty/node_modules/pty.js/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodejs/.node-v4.2.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-39-pve
gyp ERR! command "/home/nodejs/.node-v4.2.2-linux-x64/bin/node" "/home/nodejs/.node-v4.2.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodejs/.node-v4.2.2-linux-x64/lib/node_modules/wetty/node_modules/pty.js
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:pty.js@0.2.13 pty.js@0.2.13 install: `node-gyp rebuild`
npm WARN install:pty.js@0.2.13 Exit status 1

> websocket@1.0.22 install /home/nodejs/.node-v4.2.2-linux-x64/lib/node_modules/wetty/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/nodejs/.node-v4.2.2-linux-x64/lib/node_modules/wetty/node_modules/websocket/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/home/nodejs/.node-v4.2.2-linux-x64/lib/node_modules/wetty/node_modules/websocket/build'
/home/nodejs/.node-v4.2.2-linux-x64/lib
└── (empty)

npm ERR! code 1

**Comment by krishnasrinivas** [comment]
pty.js compilation is failing, I will check it with node-4
Also can you check by doing git clone? instructions are in the README

**Comment by vpo92** [comment]
Thanks for your anwser.
I try with git clone and it works !

**Comment by krishnasrinivas** [comment]
I have updated the npm version too. closing this.
