### ISSUE TITLE
Captial Y WeTTY or WeTTy?

### ISSUE THREAD

**Issue by wh0** [butlerx/wetty#360]
**Describe the bug**
Cosmetic, I see both in various documentation materials. Which is preferred?

**To Reproduce**
n/a

- title in root readme -> capital Y
- the rest of the readme -> lowercase y
- explanation that it comes from TTY -> suggests capital Y
- TTY being derived from "Tele Type" -> suggests lowercase y
- AtoZ docs page -> capital Y
- several other docs pages -> lowercase y

**Expected behavior**
ideally to use one form consistently

**Screenshots**
not provided

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
I'm writing some articles that mention this software, so I thought I'd ask.

**Comment by butlerx** [comment]
Given the name is derived from Web + TTY I guess it should be `Y`

**Comment by wh0** [comment]
Let's call this settled, thanks!
