### ISSUE TITLE
Not able to see login page

### ISSUE THREAD

**Issue by ruochao** [butlerx/wetty#367]
**Describe the bug**
I'm following the instruction and run ```docker run --rm -p 3000:3000 wettyoss/wetty --ssh-host=<YOUR-IP>```, but cannot see the login page, only a black page shown.

There are some error from browser console:
```
Navigated to http://localhost:3000/wetty
wetty.js:1 GET http://localhost:3000/wetty/_snowpack/pkg/lodash.js net::ERR_ABORTED 404 (Not Found)
wetty.js:2 GET http://localhost:3000/wetty/_snowpack/pkg/@fortawesome/fontawesome-svg-core.js net::ERR_ABORTED 404 (Not Found)
wetty.js:3 GET http://localhost:3000/wetty/_snowpack/pkg/@fortawesome/free-solid-svg-icons.js net::ERR_ABORTED 404 (Not Found)
```
Anything wrong or missed?

**Comment by sm0kingm4n** [comment]
same for me since last update.  using **docker image latest**.
**my config**
`--base=/ --host=wetty --port=3000 --ssh-host=wetty.domain --ssh-auth=publickey --ssh-key=/config/ssh_key --ssh-user=user --ssh-port=12345 --title=serverbox_wetty`
**my docker-compose**
`  wetty:
    image: "wettyoss/wetty:latest"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"
    container_name: wetty
    hostname: wetty
    ports:
      - "3000:3000/tcp"
    restart: unless-stopped
    volumes:
      - ${USERDIR}/wetty/config:/config
      - /home/user/.ssh/ssh_key:/config/ssh_key:ro
    command:
      - --base=/
      - --host=wetty
      - --port=3000
      - --ssh-host=wetty.${DOMAINNAME}
      - --ssh-auth=publickey
      - --ssh-key=/config/ssh_key
      - --ssh-user=user
      - --ssh-port=12345
      - --title=serverbox_wetty
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - npm_proxy
     depends_on:
      - npm`
 please fix

**Comment by odoo-sh** [comment]
I think I am getting the same error
![Screenshot 2021-12-09 162822](https://user-images.githubusercontent.com/38935713/145384210-7ad84108-49d9-4ebd-9d1b-9573379da202.png)

Any update pls.

**Comment by frepke** [comment]
Same problem for me :(

Hope you can fix it soon, thanks for your hard work.

**Comment by gdschut** [comment]
Getting the same errors over here, with the same black screen on startup from browser.
I think it was introduced with last update (3 days ago?) Hope you can fix it soon!

**Comment by AlexandreBourrieau** [comment]
Same problem, I do the following : 
    cp -r /home/user/wetty/build/_snowpack /home/user/wetty/build/client/

Edit the files : 
wetty/build/client/wetty.js
wetty/build/client/wetty/download.js
wetty/build/client/wetty/disconnect.js
wetty/build/client/wetty/mobile.js
wetty/build/client/wetty/socket.js
wetty/build/client/wetty/term.js
wetty/build/client/wetty/term/confiruragtion/load.js

and modifry all the "../../_snowpack by "../_snowpack (exept the first one with ./_snowpack...)

**Comment by frepke** [comment]
> Same problem, I do the following : cp -r /home/user/wetty/build/_snowpack /home/user/wetty/build/client/
> 
> Edit the files : wetty/build/client/wetty.js wetty/build/client/wetty/download.js wetty/build/client/wetty/disconnect.js wetty/build/client/wetty/mobile.js wetty/build/client/wetty/socket.js wetty/build/client/wetty/term.js wetty/build/client/wetty/term/confiruragtion/load.js
> 
> and modifry all the "../../_snowpack by "../_snowpack (exept the first one with ./_snowpack...)

Hmmm, in the /home folder I've only got the folder `node`

**Comment by AlexandreBourrieau** [comment]
You have to git clone, then npm install /home/user/wetty then yarn add /home/user/wetty then npm run build that will create the build directory where you will see the files and for executing you have to do node /home/user/weety/build/main.js

**Comment by butlerx** [comment]
Looks like at some point `web_modules` was renamed to `_snowback` in the build. Updating the server to serve this path should fix the issue

**Comment by frepke** [comment]
Working again, thanks @butlerx

**Comment by butlerx** [comment]
Thanks for confirming
