### ISSUE TITLE
Don't work in the docker version

### ISSUE THREAD

**Issue by cxy930123** [butlerx/wetty#370]
**Describe the bug**
I updated `wettyoss/wetty ` last week, then it didn't work. It seems that some resources not found.

![image](https://user-images.githubusercontent.com/7006257/145737260-a872922e-d952-4a7d-8683-0838f6c6c476.png)

The recourse paths:

- `/_snowpack/pkg/lodash.js`
- `/_snowpack/pkg/@fortawesome/fontawesome-svg-core.js`
- `/_snowpack/pkg/@fortawesome/free-solid-svg-icons.js`

I'm not sure its caused by the package or the environment.

**To Reproduce**
1. Start docker container
2. Open it in the browser

**Expected behavior**
Open a web terminal.

**Screenshots**

![image](https://user-images.githubusercontent.com/7006257/145737260-a872922e-d952-4a7d-8683-0838f6c6c476.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 96.0.4664.45

**Smartphone (please complete the following information):**
 - Device: iPad Air 3
 - OS: iOS15.0.1
 - Browser safari
 - Version unknown

**Additional context**

**Comment by butlerx** [comment]
this is the same as #367
