### ISSUE TITLE
Wetty close if sending --command

### ISSUE THREAD

**Issue by AlexandreBourrieau** [butlerx/wetty#374]
Hello,

When I start wetty with --command option, then it close automaticaly ... Any idea to resolve thise issue ?
Thanks !

**Comment by butlerx** [comment]
The Command flag executes the command on login, iirc once the command is finished it would close the ssh session. If you want a shell to remain open you need to ensure you spawn a shell in the command

**Comment by adrhc** [comment]
I tried to start `wetty` these ways:
`wetty --ssh-port 1234 --sshhost 127.0.0.1 --title "xxx" --command "export SSH_SESSION=true; /bin/bash -i"`
`wetty --ssh-port 1234 --sshhost 127.0.0.1 --title "xxx" --command "/bin/bash -i; export SSH_SESSION=true"`
but didn't work though I'm pretty sure my intention is obvious. The browser page doesn't show me the login console but the "reconnect" button only; how should correct the command?
