### ISSUE TITLE
Docker images for other architectures (ARM,...)

### ISSUE THREAD

**Issue by LeszekBlazewski** [butlerx/wetty#375]
**Is your feature request related to a problem? Please describe.**

Hey ! Great app, we are using wetty for multiple hosts connection after wakeup with wake on lan. We are running it on Raspberry PI and currently we are building the image ourselves.

**Describe the solution you'd like**

Because you already use the setup QUEMU step in github actions, would you mind also building the image for other architectures including ARM? This requires just few lines of modification inside your current workflow :)

Would be great to see docker images for other architectures on your docker hub 💯 ❗ 

Thanks for the great terminal 😃

**Comment by butlerx** [comment]
doyou have a link to docs or guides, ive never looked in to docker for arm builds before but happy to support them

**Comment by LeszekBlazewski** [comment]
This is super easy, since you use already the docker pipeline on github actions with QUEMU and BuildX step. I will provide a PR with the update which should work 😄.

Please check this PR: https://github.com/butlerx/wetty/pull/379 where details are included :) 
Let me know what you think!

**Comment by butlerx** [comment]
This should now be resolved. We are publishing multiple arm versions to docker hub and github container registry

Thanks to @LeszekBlazewski for the original change for this and most helpful write up on issues with buildx and yarn
