### ISSUE TITLE
Entry posted to Docker log every minute - why?

### ISSUE THREAD

**Issue by ameinild** [butlerx/wetty#376]
**Describe the bug**
I'm using Wetty in Docker (thanks a lot for updating the Docker images).

However, something strange is happening in the logs. Every minute, this line is posted to the Docker log:

```
{"meta":{"req":{"url":"/","headers":{"host":"10.10.2.2:8400","user-agent":"Go-http-client/1.1","connection":"close"},"method":"GET","httpVersion":"1.1","originalUrl":"/","query":{}},"res":{"statusCode":200},"responseTime":1},"level":"info","message":"HTTP GET /","label":"Wetty","timestamp":"2022-01-23T16:15:49.262Z"}
```

The log is filling rather quickly because of this.

This is my command/script to start the container:

```
docker run -d \
  --name wetty2-terminal \
  -e SSHHOST=10.10.2.2 \
  -e SSHPORT=22 \
  -e SSHUSER=am \
  -p 8400:3000 \
  --restart unless-stopped \
  wettyoss/wetty:latest --base=/
```

**Screenshot**
![Wetty_Docker_log](https://user-images.githubusercontent.com/434479/150688680-2dfb866b-b185-445c-94f8-dbf46fd0dd56.jpg)

**System info**
 - OS: Ubuntu 20.04.3
-  Docker: 20.10.12

**Comment by butlerx** [comment]
Do you have a healthcheck? this http log means something is hitting the route of the server

**Comment by ameinild** [comment]
Right.. I have prometheus blackbox exporter probing the address. Can this logging somehow be disabled? I think it's rather excessive.

**Comment by butlerx** [comment]
ok in version 2.3.0 ive added the ability to set the log level in config or via the cli, Ive also moved the http logs to a dedicated log level called `http` which is below info and above debug. this is the default level now but if you which to remove the logs you can set the log level to info or above.

**Comment by ameinild** [comment]
Thanks, much appreciated. 👍 So am I right that if I include the parameter `--log-level=info`, then this particular line will not be logged?

**Comment by butlerx** [comment]
Yep

**Comment by ameinild** [comment]
Thanks, I really appreciate the work you're doing on this. 😎 Just tested with `--log-level=info`, and it's working perfectly. 👍

Maybe include the log-level option in the readme on the front page?
