### ISSUE TITLE
--allow-remote-hosts feature on the Containerized image?

### ISSUE THREAD

**Issue by jewscojacquez** [butlerx/wetty#385]
**Is your feature request related to a problem? Please describe.**
Hello,

I'm using butlerx/wetty container image and I tried to pass a target ssh host  as part of the URL  /wetty?host={target_ssh_server}  and it shows can not get /wetty. 
Hence i'm thinking it couldn't be part of the container image yet. Can anyone confirm this? If not can we include this feature in the container Image?

**Describe the solution you'd like**
Add --allow-remote-hosts feature on the Containerized image so I could call  /wetty?host={target_ssh_server} as part of URL.

**Describe alternatives you've considered**

**Additional context**

**Comment by butlerx** [comment]
Can you try the image `wettyoss/wetty`

**Comment by jewscojacquez** [comment]
thanks Cian, I tried passing the /wetty?host={hostname} in the URI but it didn't forward the request to the hostname.

**Comment by jewscojacquez** [comment]
I'm using the latest wettyoss/wetty

Digest: sha256:af56c3cc94ec4d19433e611b1b90c8b41395a7bef35f2c49b5953d47053f1038
Status: Downloaded newer image for wettyoss/wetty:latest
docker.io/wettyoss/wetty:latest

**Comment by jewscojacquez** [comment]
Hello, any news on this? Is it possible to add the allow remote host on butlerx/wetty?

thanks,
Jewsco

**Comment by Gwindalmir** [comment]
> Hello, any news on this? Is it possible to add the allow remote host on butlerx/wetty?
> 
> thanks, Jewsco

I just added it to the docker command and it worked.

I use portainer, so this is what I set:
![image](https://user-images.githubusercontent.com/1127170/184466159-f4b01ee3-891f-4643-80cb-cafdbd4557ee.png)

If you user docker-compose, you just add it to the `command:` section

**Comment by jewscojacquez** [comment]
Gwindalmir, thanks!
I"m just an end-user, it would be nice if someone can bake this feature on the code so the next time I run "docker run --rm -p 3000:3000 wettyoss/wetty " it will be there.

**Comment by butlerx** [comment]
Thats not possible @jewscojacquez as wetty defaults to secure. 
Passing command line flags, the configuration or env variable are all supported ways for users to configure wetty to their individual systems
