### ISSUE TITLE
special characters in login

### ISSUE THREAD

**Issue by paulierco** [butlerx/wetty#387]
Looks like if I have some special chacters in the login username, is not working.
For example my username is: uid@subdomain.domain.com or COM\username.

Is there a workaround for this ?

**Comment by revarcline** [comment]
Similarly, could not log in with a username `firstname.lastname`, it stripped the period out. Is this a validation issue of some kind?

**Comment by revarcline** [comment]
so it looks like this is happening in `src/server/shared/shell.ts`:
```typescript
export const escapeShell = (username: string): string =>
  username.replace(/^-|[^a-zA-Z0-9_-]/g, '');
 ```
 changed it to
 ```ts
   username.replace(/^-|[^a-zA-Z0-9_\\\-\.\@-]/g, '');
  ```
  made a branch here https://github.com/revarcline/wetty/tree/escape-more-characters
  i'll make a pr if it works, though it looks like there may be a security reason for it. Maybe we can make an "--insecure-characters" flag if that's the issue at hand?
