### ISSUE TITLE
Disconnect signal as soon as user is provided during login

### ISSUE THREAD

**Issue by carrieganote** [butlerx/wetty#396]
It seems wetty sends a disconnect signal when I enter a username to login.

1. yarn global add wetty
2. start wetty server on localhost (with/without nginx)
3. navigate to localhost:3000/wetty
4. type in username and hit enter (tried different names)
5. nothing happens from the web side

Expect response - ask for password, or say bad username, but it appears to disconnect on back end but does not end connection. If I stop the server the web side says transport close.

wetty -c /bin/bash -p 3000
{"base":"/wetty/","label":"Wetty","level":"info","message":"Starting server","port":3000,"timestamp":"2022-04-12T23:40:42.651Z","title":"WeTTY - The Web Terminal Emulator"}
{"connection":"http","label":"Wetty","level":"info","message":"Server started","port":3000,"timestamp":"2022-04-12T23:40:42.663Z"}
{"label":"Wetty","level":"http","message":"GET /wetty 200 8ms","meta":{"req":{"headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.5","authorization":"Basic bmdpbng6ZGV3","connection":"upgrade","host":"localhost:38000","sec-fetch-dest":"document","sec-fetch-mode":"navigate","sec-fetch-site":"none","sec-fetch-user":"?1","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0","x-forwarded-for":"127.0.0.1","x-real-ip":"127.0.0.1"},"httpVersion":"1.1","method":"GET","originalUrl":"/wetty","query":{},"url":"/wetty"},"res":{"statusCode":200},"responseTime":8},"timestamp":"2022-04-12T23:41:23.287Z"}
{"label":"Wetty","level":"info","message":"Connection accepted.","timestamp":"2022-04-12T23:41:23.464Z"}
{"label":"Wetty","level":"info","message":"Authentication Type: password","timestamp":"2022-04-12T23:41:23.465Z"}
{"label":"Wetty","level":"http","message":"GET /wetty/favicon.ico 200 20ms","meta":{"req":{"headers":{"accept":"image/avif,image/webp,*/*","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.5","authorization":"Basic bmdpbng6ZGV3","connection":"upgrade","host":"localhost:38000","referer":"https://localhost:38000/wetty","sec-fetch-dest":"image","sec-fetch-mode":"no-cors","sec-fetch-site":"same-origin","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0","x-forwarded-for":"127.0.0.1","x-real-ip":"127.0.0.1"},"httpVersion":"1.1","method":"GET","originalUrl":"/wetty/favicon.ico","query":{},"url":"/wetty/favicon.ico"},"res":{"statusCode":200},"responseTime":20},"timestamp":"2022-04-12T23:41:23.475Z"}
{"err":{},"label":"Wetty","level":"info","message":"Disconnect signal sent","timestamp":"2022-04-12T23:41:37.158Z"}

Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: chrome and firefox *tried both

**Comment by nogo10** [comment]
same issue on VPS running ubuntu 16.04 with docker.compose

**Comment by Andrew5194** [comment]
I've also gotten the same issue when trying to run `wetty` locally on my macbook (macOS).

**Comment by buchmann** [comment]
same problem on my macbook Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64 Browser : Chrome & Safari

**Comment by gaballard** [comment]
Same issue here on an M1 MacBookPro (18,1) running MacOS 12.3.1 (Darwin arm64).

**Comment by LucaMarconato** [comment]
Exactly the same problem here! macOS Monterey 12.5

**Comment by Warr1024** [comment]
In the log line:

```json
{"err":{},"label":"Wetty","level":"info","message":"Disconnect signal sent","timestamp":"2022-04-12T23:41:37.158Z"}
```

that `"err":{}` happens because JSON serialization does not work correctly on nodejs error objects.  I modified `build/server.js` in the distributed module, added `import { inspect } from 'util';` to the top, and then changed `logger.info('Disconnect signal sent', { err: error });` to `logger.info('Disconnect signal sent', { err: inspect(error) });`, and was able to get this error message:

```json
{"err":"Error: error getting env version: Command failed: /usr/bin/env --version\nenv: unknown option -- v\nusage: env [-i] [name=value ...] [utility [argument ...]]\n\n    at file:///home/wetty/node_modules/wetty/build/server/spawn/env.js:5:27\n    at ChildProcess.exithandler (node:child_process:406:5)\n    at ChildProcess.emit (node:events:526:28)\n    at maybeClose (node:internal/child_process:1092:16)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)","label":"Wetty","level":"info","message":"Disconnect signal sent","timestamp":"2022-09-11T16:21:12.007Z"}
```

It looks like WeTTY is invoking the env util with a GNU-specific command line option.  Not surprising that there are a lot of reports of this specific problem with OSX/Darwin, and (in my case) OpenBSD.
