### ISSUE TITLE
docker build . failes with error /app/node_modules/pty.js: Command failed. 

### ISSUE THREAD

**Issue by Strubbl** [butlerx/wetty#4]
i run the command `docker build -t strubbl_wetty .` but that fails with the following error message. Does anybody have an idea why? As @butlerx already told me per mail, it builds successfully on docker hub. But why not on my local machine?

The yarn command fails:

```
…
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Processing triggers for ca-certificates (20141019+deb8u3) ...
Updating certificates in /etc/ssl/certs... 0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
yarn install v0.23.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /app/node_modules/pty.js: Command failed.
Exit code: 127
Command: sh
Arguments: -c node-gyp rebuild
Directory: /app/node_modules/pty.js
Output:
sh: 1: node-gyp: not found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c apt-get update && apt-get upgrade -y && yarn' returned a non-zero code: 1
```

**Comment by Strubbl** [comment]
I found this issue https://github.com/yarnpkg/yarn/issues/2266
And it took me to think about what i did in past. In April i already built this container. And now i just pulled your recent wetty changes. Since we use node:boron, i was installing the docker container back in May. unfortunately the line "from node:boron" does not pull the latest node:boron release. Thus i still have the node:boron release from may where the above mentioned bug is still in.
So i updated it manually:

`docker pull node:boron`

Now it is using yarn version v0.24.6 instead of v0.23.4 before. Afterwards docker build went fine.

Do you know how one can ensure that the latest node:boron image is always fetched on docker build?

**Comment by butlerx** [comment]
A good catch 
For future building with `--no-cache` will pull the latest image
