### ISSUE TITLE
Numerous zombie processes after logging out of wetty terminal

### ISSUE THREAD

**Issue by terryschen** [butlerx/wetty#4]
I am noticing that there are quite a few linux zombie processes after normal login and out through wetty. All the linux zombie process are [ssh] <defunct> so I suspect that the ssh is never closed properly by wetty. Unfortunately, aside from restarting the node server, I don't quite know how to fix this. Any ideas?

**Comment by krishnasrinivas** [comment]
Can you the latest code? Also added new package 'waitpid' dependency.

**Comment by terryschen** [comment]
Hi krishnasrinivas,

Pulled the new code and looks like it works. No more SSH defunct no matter how I login / logout of wetty.

Thanks!
Terry
