### ISSUE TITLE
Unable to use wetty Docker container to connect to an ssh Docker container

### ISSUE THREAD

**Issue by Andrew5194** [butlerx/wetty#400]
**Describe the bug**
I'm unable to use the wetty web shell to connect to another Docker container that I've spun up to serve as an SSH server. I've confirmed that I can connect to the Docker container via SSH using my host, but I'm unable to access it via the wetty Docker container/web shell.

**To Reproduce**
1. I have the following `Dockerfile`:

```
FROM ubuntu:latest
RUN apt update && apt install  openssh-server sudo -y
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 test
RUN  echo 'test:test' | chpasswd
RUN service ssh start
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]
```

2. Build the ssh Docker container with `docker build -f Dockerfile -t ssh-test .` and run using `docker run -it -p 22:22 ssh-test `

3. Verify that you can connect to the container via ssh (by trying to connect via ssh from the host to the container):

```
(base) andrew@Andrews-MacBook-Pro webshell % ssh test@localhost
test@localhost's password: 
Welcome to Ubuntu 22.04 LTS (GNU/Linux 5.10.76-linuxkit x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, you can run the 'unminimize' command.

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

test@d6858280da2a:~$ 
```

4. Now spin up the wetty container `docker run --rm -p 3000:3000 wettyoss/wetty --ssh-host=127.0.0.1 --ssh-port=22`

5. Now access the wetty terminal at `localhost:3000`, and insert the `test` username and `test` password.

6. I get an incorrect login via wetty but I've confirmed that I'm able to ssh into the `ssh-test` Docker container from my host.

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/20665775/166829395-19aa8581-973c-48b4-a730-d77133133a0d.png">
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/20665775/166829653-edcf1f54-0fec-4e25-a11c-1cf9b1a76e5e.png">

**Expected behavior**
I would expect that I can access the `ssh-test` container via SSH using the wetty web shell.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 100.0.4896.127

**Comment by thaJeztah** [comment]
The wetty shell is the equivalent to running a `docker exec` into a container; the shell is running inside that container, and if you try to connect to `localhost`, that will be localhost of the container itself (in which no ssh server is running). To connect to the port 22 that is mapped for the other container, you can try using the special `host.docker.internal` hostname that's available on docker desktop; https://docs.docker.com/desktop/mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host


Alternatively, have both containers connected to the same internal docker network, in which case you can connect with the other container using its own IP address  or hostname.

**Comment by Andrew5194** [comment]
Ahhhh okay that makes sense, thank you I'll try your advice and report back. Thanks for the prompt response! 🙏

**Comment by Andrew5194** [comment]
This worked exactly as you said! Thank you so much, I was banging my head against the wall for a while.

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/20665775/166831051-54f0cd7b-96af-4f18-9021-e7ca8d3d44f5.png">

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/20665775/166830972-e8f08450-0b80-41d5-88b4-7fa1e160f897.png">

**Comment by thaJeztah** [comment]
Yes it can be confusing, as `localhost` is not always "localhost" 😂 (you're definitely not the first one getting confused!)

Glad this helped 👍

**Comment by Andrew5194** [comment]
🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏

**Comment by iwestlin** [comment]
I hope I can see this issue one hour ago😂
