### ISSUE TITLE
Latest Docker images are arm64 only

### ISSUE THREAD

**Issue by ameinild** [butlerx/wetty#420]
The latest Docker images are only for the arm64 architecture. Shouldn't it be possible that the "latest" tag is available for all supported architectures, and not only arm?

**Comment by butlerx** [comment]
Hmm it should be available for all architecture possibly it's been over written by one of slower arm builds latest is a weird tag in docker and usually means last thing pushed rather then most up to date

**Comment by butlerx** [comment]
Ah I see the issue is from splitting the build out into seperate jobs causing them to overwrite each other

**Comment by butlerx** [comment]
Ive fixed the logic in the docker workflow but I'm getting timeout again working on a fix

**Comment by ameinild** [comment]
Thanks - hope you can get it to work properly - built-in arm support is much appreciated. 👍

**Comment by butlerx** [comment]
The build takes nearly 30 minutes but given this only runs on main or tags I think that's alright  ![Screenshot_20220817-112529.png](https://user-images.githubusercontent.com/867930/185096666-be066742-b0ae-4d10-b4f7-0c2362853f9d.png)

**Comment by ameinild** [comment]
This looks much better - thanks!
