### ISSUE TITLE
Is inline image display a future possibility? 

### ISSUE THREAD

**Issue by kb1ooo** [butlerx/wetty#422]
We have downloads via the print escape sequence support, but it would be nice to also have inline image display support.  Is there any possibility of this as a feature for wetty?  

Thanks,  
Marc

**Comment by butlerx** [comment]
According to https://github.com/xtermjs/xterm.js/issues/614#issuecomment-1133899963 this should be possible

**Comment by jerch** [comment]
Here you go: #423 :smiley_cat:

**Comment by kb1ooo** [comment]
@jerch awesome, thanks!
