### ISSUE TITLE
config documentation

### ISSUE THREAD

**Issue by brightdroid** [butlerx/wetty#426]
**Is your feature request related to a problem? Please describe.**
I found no config file documentation or example with all options and comments. (--conf)

**Describe the solution you'd like**
Please add an example config file or documentation of all options. I'd like to change the default colors and some options.

**Comment by butlerx** [comment]
there is a default config in https://github.com/butlerx/wetty/blob/main/conf/config.json5

**Comment by brightdroid** [comment]
Thank you, maybe it should be added into the [docs](https://github.com/butlerx/wetty/tree/main/docs)
