### ISSUE TITLE
yarn global install fails

### ISSUE THREAD

**Issue by vomaksh** [butlerx/wetty#428]
**Describe the bug**
``yarn global install wetty`` fails

**To Reproduce**
Steps to reproduce the behaviour:
1. ``yarn global install wetty``

**Expected behaviour**
It should install successfully

**Node version**
``v16.17.0``

**Error log**
```
error /home/yorozuya/.config/yarn/global/node_modules/wetty: Command failed.
Exit code: 127
Command: yarn build
Arguments: 
Directory: /home/yorozuya/.config/yarn/global/node_modules/wetty
Output:
yarn run v1.22.19
warning ../../package.json: No license field
$ snowpack build
```

**Comment by headersalreadysent** [comment]
this bugs affects me too

**Comment by swampfox0866** [comment]
Having the same issue:

[root@mail-gw-01 ~]# yarn global add wetty
yarn global v1.22.19
[1/4] Resolving packages...
warning wetty > gc-stats > node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/6] ⠁ waiting...
[6/6] ⠁ wetty
[-/6] ⠁ waiting...
[-/6] ⠁ waiting...
error /usr/local/share/.config/yarn/global/node_modules/wetty: Command failed.
Exit code: 127
Command: yarn build
Arguments:
Directory: /usr/local/share/.config/yarn/global/node_modules/wetty
Output:
yarn run v1.22.19
$ snowpack build

**Comment by hengkp** [comment]
I also have the same error after run:

`$ yarn global add wetty`


> Having the same issue:
>
>[root@mail-gw-01 ~]# yarn global add wetty
yarn global v1.22.19
[1/4] Resolving packages... 
warning wetty > gc-stats > node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future 
[2/4] Fetching packages... 
[3/4] Linking dependencies... 
[4/4] Building fresh packages... 
[-/6] ⠁ waiting... 
[6/6] ⠁ wetty 
[-/6] ⠁ waiting... 
[-/6] ⠁ waiting... 
error /usr/local/share/.config/yarn/global/node_modules/wetty: Command failed. 
Exit code: 127 
Command: yarn build 
Arguments: 
Directory: /usr/local/share/.config/yarn/global/node_modules/wetty 
Output: yarn run v1.22.19 
$ snowpack build

**Comment by kenshin6x** [comment]
Still same issue on Macbook M1 2020, macOS 12.5.1

```
➜  ~ yarn global add wetty
yarn global v1.22.19
[1/4] 🔍  Resolving packages...
warning wetty > gc-stats > node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[-/6] ⠁ waiting...
[6/6] ⠁ wetty
[-/6] ⠁ waiting...
[-/6] ⠁ waiting...
error /Users/kenshin6x/.config/yarn/global/node_modules/wetty: Command failed.
Exit code: 127
Command: yarn build
Arguments: 
Directory: /Users/kenshin6x/.config/yarn/global/node_modules/wetty
Output:
yarn run v1.22.19
warning ../../package.json: No license field
$ snowpack build

```

node -v
```v18.9.1```

npm -v
```8.19.1```

yarn -v 
```1.22.19```

**Comment by butlerx** [comment]
looks like the postinstall added in #419 is only required for manual installs, E.g container build .
will remove and update docs
