### ISSUE TITLE
Installing Failed Pty.js

### ISSUE THREAD

**Issue by jaredbroad** [butlerx/wetty#43]
Hello, I've tried installing from a git clone and received the following error:

```
npm http GET https://registry.npmjs.org/argparse/-/argparse-0.1.16.tgz
npm http 200 https://registry.npmjs.org/esprima/-/esprima-1.0.4.tgz
npm http 200 https://registry.npmjs.org/argparse/-/argparse-0.1.16.tgz

> pty.js@0.3.0 install /root/wetty/node_modules/pty.js
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-57-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/wetty/node_modules/pty.js
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 1
npm ERR! Error: ENOENT, lstat '/root/tmp/npm-18900-1ajJ8_LR/1453153736493-0.21297033480368555/package/dist/lodash.underscore.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/wetty
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /root/tmp/npm-18900-1ajJ8_LR/1453153736493-0.21297033480368555/package/dist/lodash.underscore.js
npm ERR! fstream_path /root/tmp/npm-18900-1ajJ8_LR/1453153736493-0.21297033480368555/package/dist/lodash.underscore.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/root/tmp/npm-18900-1ajJ8_LR/1453153737388-0.06007509049959481/package/test/test.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/wetty
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /root/tmp/npm-18900-1ajJ8_LR/1453153737388-0.06007509049959481/package/test/test.js
npm ERR! fstream_path /root/tmp/npm-18900-1ajJ8_LR/1453153737388-0.06007509049959481/package/test/test.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! tar pack Error reading /root/tmp/npm-18900-1ajJ8_LR/1453153736534-0.860922196181491/package
npm ERR! addLocalDirectory Could not pack "/root/tmp/npm-18900-1ajJ8_LR/1453153736534-0.860922196181491/package" to "/root/.npm/underscore.string/2.                                                                                                                            3.3/package.tgz"
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/wetty/npm-debug.log
npm ERR! not ok code 0
```

**Comment by jarrettgilliam** [comment]
What commands did you run to produce this error? Also, where is node installed on your system?

**Comment by russellanam** [comment]
Hi, I have the same problem. I get the exact same error when I run the command "npm install". Get the same error when I try "sudo node-gyp rebuild".

`0: no version information available (required by nodejs)
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: gyp failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-36-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/wetty/wetty/node_modules/pty.js
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 1
npm ERR! not ok code 0`

**Comment by jarrettgilliam** [comment]
I see this warning here:
```
npm WARN This failure might be due to the use of legacy binary "node"
```

What version of node are you running? (`node -v`)

**Comment by russellanam** [comment]
Hi,
I am using the latest version of Node according to apt-get and it seems to be v.3.2-7.4. However when I type 'node -v' it shows blank.
Thanks
-M A

Date: Wed, 10 Feb 2016 12:40:22 -0800

**Comment by jarrettgilliam** [comment]
That's strange. You might need a compatibility symbolic link.

From [nodejs.org](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions):

> A Node.js package is also available in the official repo for Debian Sid (unstable), Jessie (testing) and Wheezy (wheezy-backports) as "nodejs". It only installs a nodejs binary, so you might want to `ln -s /usr/bin/nodejs /usr/bin/node` for many things to work.

How did you install nodejs on your system? Did you install the default package from your package manager or download one directly from https://nodejs.org/?

**Comment by russellanam** [comment]
Hi,
I just ran "ln -s /usr/bin/nodejs /usr/bin/node" and 'node -v' still shows blank. I installed node via "apt-get install node". I have tried installing and reinstalling node again and it's still blank. In case it matters, I am doing all these on the default AWS instance and all packages are updated.
Date: Wed, 10 Feb 2016 13:35:47 -0800

**Comment by jarrettgilliam** [comment]
What is the output of the following commands?

`ls -l "$(which node)"`
`ls -l "$(which nodejs)"`
`nodejs -v`

**Comment by russellanam** [comment]
Hi,
Here is the output:
ubuntu@ip-1-0-1-50:~$ ls -l "$(which node)"lrwxrwxrwx 1 root root 9 Oct 29  2012 /usr/sbin/node -> ax25-nodeubuntu@ip-1-0-1-50:~$ ls -l "$(which nodejs)"-rwxr-xr-x 1 root root 1462424 Mar 27  2014 /usr/bin/nodejsubuntu@ip-1-0-1-50:~$ nodejs -vnodejs: /usr/local/MATLAB/MATLAB_Compiler_Runtime/v83/bin/glnxa64/libcrypto.so.1.0.0: no version information available (required by nodejs)nodejs: /usr/local/MATLAB/MATLAB_Compiler_Runtime/v83/bin/glnxa64/libssl.so.1.0.0: no version information available (required by nodejs)nodejs: /usr/local/MATLAB/MATLAB_Compiler_Runtime/v83/bin/glnxa64/libssl.so.1.0.0: no version information available (required by nodejs)v0.10.25

Date: Wed, 10 Feb 2016 13:57:13 -0800

**Comment by jarrettgilliam** [comment]
It looks like you have a couple of options.
1. You can try installing `nodejs-legacy` as described [here](http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu#21171188). This is probably your best bet.
2. If that doesn't work you could try to [install a newer version of node](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions).
3. If none of the above works you could manually create a compatibility symbolic link. In your case specifically this should work:

```
rm /usr/sbin/node
ln -s /usr/bin/nodejs /usr/sbin/node
```

Hope that helps,
Jarrett

**Comment by russellanam** [comment]
Hi Jarrett,
Thank you so much for your help. I am very grateful and the problem has been finally solved. Wetty is running perfectly and works great. Just a quick question, is it possible to login to SSH with wetty using keys instead of user/pass? I mean just typing the username and it gets the SSH authentication key from a pre-specified file?
Thanks a lot again!
-M Anam.

Date: Wed, 10 Feb 2016 15:39:06 -0800

**Comment by jarrettgilliam** [comment]
Try `--sshauth publickey`. Closing.
