### ISSUE TITLE
Issue with Traefik when using Authelia

### ISSUE THREAD

**Issue by danricho** [butlerx/wetty#440]
Hi,

I'm having an issue where my Authelia username is pre-filled at the WeTTY login prompt (before the @) which means I'm unable to login as it differs from my user name on the Linux box. I have tried both environmental variable `SSHUSER` and the command --`ssh-user=` to over-ride this behaviour but to no avail.

I think it has something to do with `remote-user` propagation as described [here](https://github.com/butlerx/wetty/blob/e9866fa2f4f4fc36864f776d2d3a47a97794d51b/docs/apache.md#saml2-integration-to-auth-users).

I'm hoping someone more knowledgeable about Authelia and the sessions or WeTTY can give me a way to get WeTTY to ignore the Authelia user logged in.

Cheers!

**Comment by dl1ch** [comment]
As a workaround you can create an additional nginx container pointing to the wetty docker container with the following header:
`proxy_set_header remote-user "";`

This will remove the remote-user header before passing it to wetty, then you can use a custom URL path to login with the custom username:

httpx://wetty-fqdn/wetty/ssh/username

Hope this helps.
