### ISSUE TITLE
What browsers does Wetty support?

### ISSUE THREAD

**Issue by merlijn-sebrechts** [butlerx/wetty#45]
Hi

I can't seem to find any information on what browsers Wetty support. Is this Chrome only? Is it possible to add this information in the readme?

Kind regards
Merlijn

**Comment by jarrettgilliam** [comment]
Hi Merlijn,

Wetty supports all browsers that Google's hterm supports. As far as a complete list of supported browsers, I couldn't find one. From looking at the [changelog](https://chromium.googlesource.com/apps/libapps/+/master/hterm/doc/changelog.txt?autodive=0%2F#181), it appears Firefox and IE support was added in April of 2014. In [the code](https://github.com/krishnasrinivas/wetty/blob/master/public/wetty/hterm_all.js) I see a reference to Safari on line 91 but I'm not sure if it's officially supported. I have no idea about Opera.

I've personally used Wetty on IE 11, Chrome and Firefox and they all appear to work correctly. To get it to work on IE, I had to run the command described [here](http://stackoverflow.com/questions/13102116/access-denied-for-localstorage-in-ie10#20848924). Hopefully someone else can give you a better answer.

Jarrett

**Comment by merlijn-sebrechts** [comment]
Thanks Jarett!

I created pull request https://github.com/krishnasrinivas/wetty/compare/master...galgalesh:patch-1 to include this info in the `README.md`. Is this something you'd be open to merge? Maybe it is better to wait a bit to see if anyone can link a more official source..?

Kind regards
Merlijn

**Comment by jarrettgilliam** [comment]
I don't have the authority to merge pull requests. I'm just a lowly follower :). You would have to ask @krishnasrinivas.

**Comment by krishnasrinivas** [comment]
@jarrettgilliam would you have time to be a collaborator for wetty? If so I can add you as a [collaborator](https://help.github.com/articles/adding-collaborators-to-a-personal-repository/) and you can take decisions on what can be merged into wetty. I am a bit held up at work to dedicate time here.

**Comment by jarrettgilliam** [comment]
I think I have enough time to help out. That sounds great. I'm not really sure what your goals are for Wetty or if you have any sort of road map. That's something we should probably talk about so we're on the same page.

**Comment by krishnasrinivas** [comment]
OK great. The goal of wetty will be to remain simple and bug free. Let's not accept feature pull-requests unless it's really required. I will leave it to your discretion. I have added you as a collaborator.
There is no road map.

**Comment by merlijn-sebrechts** [comment]
https://github.com/krishnasrinivas/wetty/pull/48
