### ISSUE TITLE
Is wetty still buildable with only yarn (version > 1.10) ?

### ISSUE THREAD

**Issue by mirtouf** [butlerx/wetty#45]
Hi,

I upgraded yarn to version 1.10.1 and for some reason using the common process
``yarn
``
``yarn build
``
does not create the index.js file

As a dirty workaround I had to run
``
npm install
``
prior to using yarn.

Are there missing commands in the build instructions ?

**Comment by butlerx** [comment]
what file is missing?

**Comment by mirtouf** [comment]
I retried with only yarn and... all went fine.
I did not what happened the first time, I close this issue then.
