### ISSUE TITLE
yarn install fails

### ISSUE THREAD

**Issue by Retidurc** [butlerx/wetty#458]
Describe the bug;
yarn install fails

Node version
`v18.12.1`

> yarn install v1.22.19
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> [3/5] Fetching packages...
> [4/5] Linking dependencies...
> [5/5] Building fresh packages...
> [1/10] ⠂ @fortawesome/fontawesome-common-types
> [2/10] ⠂ gc-stats
> [3/10] ⠂ node-pty
> [4/10] ⠂ husky
> error /root/src/wetty/node_modules/node-pty: Command failed.
> Exit code: 1
> Command: node scripts/install.js
> Arguments:
> Directory: /root/src/wetty/node_modules/node-pty
> Output:
> node:events:491
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn node-gyp ENOENT
>     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
>     at onErrorNT (node:internal/child_process:476:16)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> Emitted 'error' event on ChildProcess instance at:
>     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
>     at onErrorNT (node:internal/child_process:476:16)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'spawn node-gyp',
>   path: 'node-gyp',
>   spawnargs: [ 'rebuild' ]

yarn global add wetty fails with the same error

**Comment by db-at-home** [comment]
I see exactly the same with linux (tumbleweed) node19 and yarn 1.22

        yarn-1.22.19-1.4.noarch
        nodejs19-19.9.0-1.1.x86_64
