### ISSUE TITLE
Expose --sshhost and --sshport as GET parameters

### ISSUE THREAD

**Issue by merlijn-sebrechts** [butlerx/wetty#46]
Hi

It would be great if Wetty would expose `--sshhost` and `--sshport` as GET parameters. This would make it very easy to integrate Wetty into web-based server management panels.

Kind regards
Merlijn Sebrechts

**Comment by jarrettgilliam** [comment]
Exposing `--sshhost` to the client interface is currently being discussed in pull request #40.

**Comment by butlerx** [comment]
this was implemented in v1.1
