### ISSUE TITLE
Neovim highlight color not appearing in blank spaces

### ISSUE THREAD

**Issue by Normanras** [butlerx/wetty#466]
**Is your feature request related to a problem? Please describe.**
Honestly, this might be more about how browsers and xterm render color than any specific feature request for this repo. What I'm doing for the time being is using Wetty to have a browser interface into a development environment on a VPS. I use neovim for this 90% of the time. 

However, when I load neovim, my color scheme "loads" but won't show the basic colors where these is whitespace. As I start typing, the highlight/background color shows up normally. It shows the xterm background color where there is no text. I've attached some screenshots at the bottom. 

**Describe the solution you'd like**
I want my neovim color scheme to show up as the background color in the terminal.

**Describe alternatives you've considered**
If I set my color scheme to one with a black background, it looks "normal" and clean. This is fine for the time being. 

**Additional context**
I'd love to learn more about how xterm renders the colors. Or what may be causing this. I've looked through all the settings and tried setting the "transparent background" boolean to checked, but that does nothing to change this appearance. 

Screenshots:
1. Wetty:
<img width="1254" alt="Screenshot 2023-04-02 at 12 04 30 PM" src="https://user-images.githubusercontent.com/44226464/229371578-862a2c38-d299-4220-8612-573411c06127.png">

2. Terminal, ssh'd into the wetty vm, with the same neovim start screen:
<img width="785" alt="Screenshot 2023-04-02 at 12 07 59 PM" src="https://user-images.githubusercontent.com/44226464/229371593-e85525ea-82bc-422e-9a65-a83b3185d9b0.png">

3. Both side-by-side. Wetty on the left, iTerm2 on the right.
<img width="1189" alt="Screenshot 2023-04-02 at 12 08 12 PM" src="https://user-images.githubusercontent.com/44226464/229371606-8f4f81b9-1958-4c92-a234-3f7bf1fd8f80.png">

**Comment by refracta** [comment]
![image](https://github.com/butlerx/wetty/assets/58779799/b8092d0a-6126-4d2e-9cd4-b76875e55cd1)

The same symptoms occur in the terminal-based game I'm trying to run.
