### ISSUE TITLE
Tmux copy and pasting not working

### ISSUE THREAD

**Issue by jdloft** [butlerx/wetty#47]
Tmux mouse selection and <kbd>CTRL</kbd>+<kbd>[</kbd> copy and paste flash the scissor icon but don't copy to the system clip board. Tested in Chrome on Windows and Linux and Firefox on Windows.

**Comment by jarrettgilliam** [comment]
The tmux copy and paste feature uses it's own clipboard (buffers), not system ones. Is this a feature you've seen before?

**Comment by jdloft** [comment]
The Secure Shell app (https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo?utm_source=chrome-app-launcher) also uses hterm and mirrors anything copied via tmux. And since the scissor icon displays it seems hterm may be receiving/detecting the paste.
