### ISSUE TITLE
Trying to expose the terminal of a Raspberry Pi

### ISSUE THREAD

**Issue by 9acca9** [butlerx/wetty#503]
Hi.
Maybe this is not how this is suppose to be used.
I want to expose the terminal of my raspberry pi.
In that way i just  go to a web browser from my CELLPHONE and access the terminal.
This is possible?

i try but im just getting a black screen in the web browser and dont say nothing about log in.
So.
Thanks!

![imagen](https://github.com/butlerx/wetty/assets/25393371/53e972c5-33ee-4daf-af44-53112ecfb194)

this screenshot is from my notebook, but i want to access from my cellphone, so i cant install wetty in my cellphone, that is way i want to "expose" the terminal.

**Comment by lv913** [comment]
I have the same issue.
@butlerx, do you have any ideas on how to troubleshoot the issue?
Thanks!

**Comment by lv913** [comment]
@9acca9: I have found a workaround. If you remove wetty 2.7.0 and install previous version 2.5.0, it works correctly.

`yarn global remove wetty`
`yarn global add wetty@2.5.0`

**Comment by 9acca9** [comment]
@lv913 Excellent!!!!! Thanks!

**Comment by ysy95109** [comment]
This seems to be fixed 3 months ago in the main branch, but no release was published.
So I cloned the repo and built from source using pnpm. Now wetty is running smooth on my server without any problem.

**Comment by zanhecht** [comment]
@butlerx Any plan to release a new version with these fixes included?

**Comment by lv913** [comment]
It seems that wetty has been abandoned since September 2023.

**Comment by ysy95109** [comment]
> It seems that wetty has been abandoned since September 2023.

It's still working well though... Is there any alternatives, in case Wetty gets broken someday?
