### ISSUE TITLE
Move away from snowpack?

### ISSUE THREAD

**Issue by rohitkot1** [butlerx/wetty#504]
**Describe the bug**
Snowpack is unmaintained (last commit in jun-2022)
Snowpack uses vm2

Vm2 is unmaintained and deprecated and a critical vulnerability
   https://github.com/patriksimek/vm2/issues/533

They recommend moving to isolated-vm

**Additional context**

Maybe migrate from snowpack to vite or something else?

**Comment by butlerx** [comment]
thats the plan but moving unfortunately isn't as straight forward as I had hoped as vite and snowpack are quite different to actually use
