### ISSUE TITLE
[Feature request] - ALTGR + key doesn't work

### ISSUE THREAD

**Issue by cr0ssmind** [butlerx/wetty#51]
Hello!
I don't know, whether it is a feature request or not, but combination of ALTGR + key doesn't work in wetty. Could you develop this feature please?

Thank you!

**Comment by imuli** [comment]
This looks like a hterm bug, notably `hterm.keyboard.prototype.encode` at hterm_all.js:5621 takes a utf8 encoded string and encodes as utf8 again. I just hacked around this [here](https://github.com/imuli/wetty/tree/utf8inputhack). A proper fix might be over at the [hterm](https://github.com/chromium/hterm) project somewhere?

**Comment by imuli** [comment]
Workaround would be to set the `characterEncoding` option to 'raw' or something.

**Comment by cr0ssmind** [comment]
I will test it soon, thank you!

**Comment by butlerx** [comment]
hterm is no longer used in favour of xterm.js
