### ISSUE TITLE
It doesn't work! fortawesome/fontawesome-svg-core is missing

### ISSUE THREAD

**Issue by adrhc** [butlerx/wetty#526]
**Describe the bug**
The page is black and contains nothing else!
Installed with `sudo npm -g i wetty`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://127.0.0.1:3000/wetty
2. I get an empty, black page
3. Open browser tools
4. I notice that all files/resources are downloaded (200 OK)
5. in the javascript tab I see the error:
> Uncaught TypeError: Failed to resolve module specifier "@fortawesome/fontawesome-svg-core". Relative references must start with either "/", "./", or "../".

**See in wetty.js:** 
`import {dom, library} from "@fortawesome/fontawesome-svg-core";`

**Expected behaviour**
I should see the login page.

**Screenshots**
![image](https://github.com/butlerx/wetty/assets/5136846/5db93cb8-0a2f-4eea-9e65-fae38ce73d97)
![image](https://github.com/butlerx/wetty/assets/5136846/8c3e7d5e-0537-421b-b244-ee99f040fd66)

**Desktop (please complete the following information):**
 - OS: Windows 10 or XUbuntu 23.10
 - Browser chrome, firefox, edge
 - Version latest

**Additional context**
The screenshots are from the wetty put on nginx because is the same as when accessed locally.

**Comment by adrhc** [comment]
some logs from `journalctl`:

> Sun 2024-03-31 10:39:02 EEST adrhc.go.ro wetty[179822]: {"label":"Wetty","level":"http","message":"GET /wetty 200 3ms","meta":{"req":{"headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","accept-encoding":"gzip, deflate, br, zstd","accept-language":"en-US,en;q=0.9,ro;q=0.8","cache-control":"no-cache","connection":"close","cookie":"currenthost=Default; skin=desktop; player_backend=mopidy; browser_id=1702893380482; sickchill_user=\"2|1:0|10:1710356871|14:sickchill_user|44:MTM0Y2RmMjBiMjgwOTYyMWMxYWZlZTU4YjA4MDU3NTc=|35cec405c65c3b2cbff8dc06ee2521ad07e29912e0382f5f5346e6beb77e08da\"; io=g2hP3QSVN349zgaeAABV; JSESSIONID=EEB72EF981BCB521506367246D8149E9; _ga=GA1.2.1050451663.1706442856; _ga_2RDVDG6732=GS1.1.1711714567.10.1.1711715061.0.0.0","host":"127.0.0.1:3000","pragma":"no-cache","sec-ch-ua":"\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","sec-fetch-dest":"document","sec-fetch-mode":"navigate","sec-fetch-site":"none","sec-fetch-user":"?1","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"},"httpVersion":"1.0","method":"GET","originalUrl":"/wetty","query":{},"url":"/wetty"},"res":{"statusCode":200},"responseTime":3},"timestamp":"2024-03-31T07:39:02.774Z"}
> Sun 2024-03-31 10:39:03 EEST adrhc.go.ro wetty[179822]: {"label":"Wetty","level":"http","message":"GET /wetty/favicon.ico 200 9ms","meta":{"req":{"headers":{"accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","accept-encoding":"gzip, deflate, br, zstd","accept-language":"en-US,en;q=0.9,ro;q=0.8","cache-control":"no-cache","connection":"close","cookie":"currenthost=Default; skin=desktop; player_backend=mopidy; browser_id=1702893380482; sickchill_user=\"2|1:0|10:1710356871|14:sickchill_user|44:MTM0Y2RmMjBiMjgwOTYyMWMxYWZlZTU4YjA4MDU3NTc=|35cec405c65c3b2cbff8dc06ee2521ad07e29912e0382f5f5346e6beb77e08da\"; io=g2hP3QSVN349zgaeAABV; JSESSIONID=EEB72EF981BCB521506367246D8149E9; _ga=GA1.2.1050451663.1706442856; _ga_2RDVDG6732=GS1.1.1711714567.10.1.1711715061.0.0.0","host":"127.0.0.1:3000","pragma":"no-cache","referer":"https://adrhc.go.ro/wetty","sec-ch-ua":"\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","sec-fetch-dest":"image","sec-fetch-mode":"no-cors","sec-fetch-site":"same-origin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"},"httpVersion":"1.0","method":"GET","originalUrl":"/wetty/favicon.ico","query":{},"url":"/wetty/favicon.ico"},"res":{"statusCode":200},"responseTime":9},"timestamp":"2024-03-31T07:39:03.083Z"}
> Sun 2024-03-31 10:46:34 EEST adrhc.go.ro wetty[179822]: {"label":"Wetty","level":"http","message":"GET /wetty 200 3ms","meta":{"req":{"headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","accept-encoding":"gzip, deflate, br, zstd","accept-language":"en-US,en;q=0.9,ro;q=0.8","cache-control":"no-cache","connection":"close","cookie":"currenthost=Default; skin=desktop; player_backend=mopidy; browser_id=1702893380482; sickchill_user=\"2|1:0|10:1710356871|14:sickchill_user|44:MTM0Y2RmMjBiMjgwOTYyMWMxYWZlZTU4YjA4MDU3NTc=|35cec405c65c3b2cbff8dc06ee2521ad07e29912e0382f5f5346e6beb77e08da\"; io=g2hP3QSVN349zgaeAABV; JSESSIONID=EEB72EF981BCB521506367246D8149E9; _ga=GA1.2.1050451663.1706442856; _ga_2RDVDG6732=GS1.1.1711714567.10.1.1711715061.0.0.0","host":"127.0.0.1:3000","pragma":"no-cache","sec-ch-ua":"\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","sec-fetch-dest":"document","sec-fetch-mode":"navigate","sec-fetch-site":"none","sec-fetch-user":"?1","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"},"httpVersion":"1.0","method":"GET","originalUrl":"/wetty","query":{},"url":"/wetty"},"res":{"statusCode":200},"responseTime":3},"timestamp":"2024-03-31T07:46:34.090Z"}
> Sun 2024-03-31 10:46:34 EEST adrhc.go.ro wetty[179822]: {"label":"Wetty","level":"http","message":"GET /wetty/favicon.ico 200 10ms","meta":{"req":{"headers":{"accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","accept-encoding":"gzip, deflate, br, zstd","accept-language":"en-US,en;q=0.9,ro;q=0.8","cache-control":"no-cache","connection":"close","cookie":"currenthost=Default; skin=desktop; player_backend=mopidy; browser_id=1702893380482; sickchill_user=\"2|1:0|10:1710356871|14:sickchill_user|44:MTM0Y2RmMjBiMjgwOTYyMWMxYWZlZTU4YjA4MDU3NTc=|35cec405c65c3b2cbff8dc06ee2521ad07e29912e0382f5f5346e6beb77e08da\"; io=g2hP3QSVN349zgaeAABV; JSESSIONID=EEB72EF981BCB521506367246D8149E9; _ga=GA1.2.1050451663.1706442856; _ga_2RDVDG6732=GS1.1.1711714567.10.1.1711715061.0.0.0","host":"127.0.0.1:3000","pragma":"no-cache","referer":"https://adrhc.go.ro/wetty","sec-ch-ua":"\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","sec-fetch-dest":"image","sec-fetch-mode":"no-cors","sec-fetch-site":"same-origin","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"},"httpVersion":"1.0","method":"GET","originalUrl":"/wetty/favicon.ico","query":{},"url":"/wetty/favicon.ico"},"res":{"statusCode":200},"responseTime":10},"timestamp":"2024-03-31T07:46:34.384Z"}

**Comment by adrhc** [comment]
When I git clone and run with dev I get 404 Not Found for:
https://adrhc.go.ro/wetty/web_modules/pkg/@fortawesome.fontawesome-svg-core.v6.5.1.js

```sh
$pwd
/home/gigi/compile/wetty
$find . -iname "*fontawesome-svg-core.v6.5.1*"
./build/web_modules/pkg/@fortawesome.fontawesome-svg-core.v6.5.1.js
$git remote -vv
origin  https://github.com/butlerx/wetty.git (fetch)
origin  https://github.com/butlerx/wetty.git (push)
$ll build/web_modules/pkg/
total 2.1M
-rw-rw-r-- 1 gigi gigi  47K Mar 31 11:06 engine.io-client.v6.5.3.js
-rw-rw-r-- 1 gigi gigi  12K Mar 31 11:06 engine.io-parser.v5.2.2.js
-rw-rw-r-- 1 gigi gigi  30K Mar 31 11:06 file-type.v12.4.2.js
-rw-rw-r-- 1 gigi gigi 544K Mar 31 11:06 lodash.v4.17.21.js
-rw-rw-r-- 1 gigi gigi  40K Mar 31 11:06 socket.io-client.v4.7.5.js
-rw-rw-r-- 1 gigi gigi  14K Mar 31 11:06 socket.io-parser.v4.2.4.js
-rw-rw-r-- 1 gigi gigi  16K Mar 31 11:06 toastify-js.v1.12.0.js
-rw-rw-r-- 1 gigi gigi 2.2K Mar 31 11:06 xterm-addon-fit.v0.7.0.js
-rw-rw-r-- 1 gigi gigi  55K Mar 31 11:06 xterm-addon-image.v0.5.0.js
-rw-rw-r-- 1 gigi gigi 3.6K Mar 31 11:06 xterm-addon-web-links.v0.8.0.js
-rw-rw-r-- 1 gigi gigi 279K Mar 31 11:06 xterm.v5.3.0.js
-rw-rw-r-- 1 gigi gigi 105K Mar 31 11:06 @fortawesome.fontawesome-svg-core.v6.5.1.js
-rw-rw-r-- 1 gigi gigi 967K Mar 31 11:06 @fortawesome.free-solid-svg-icons.v6.5.1.js
-rw-rw-r-- 1 gigi gigi 2.1K Mar 31 11:06 @socket.io.component-emitter.v3.1.0.js
```

**Comment by andriy-pankiv-lemberg** [comment]
@adrhc Hi, I am facing the same issue. I have downgraded to version 2.6.0 and it works from the box

**Comment by gardiol** [comment]
Downgrade with:

`npm -i wetty@2.6.0`

will fix the issue.

Overall wetty seems unmaintained.
