### ISSUE TITLE
Security - Please add Fail2ban support

### ISSUE THREAD

**Issue by brlin-tw** [butlerx/wetty#53]
Hi, I've tried Wetty lately and suspected that it may let the hacker to brute-force user's password by repeatedly guessing it.  Please implement Fail2ban configs to block repeated login failure users.

**Comment by plato79** [comment]
Maybe I'm wrong but I think it's up to your system to implement fail2ban. Wetty only provides a direct ssh connection to your server. Your server's ssh server should check if it should ban that IP for unsuccesful entries or not.

**Comment by butlerx** [comment]
@plato79 is right my only worry about that would be that youd fail2ban your web server from the server your ssh'ing to.
