### ISSUE TITLE
using under non-root (sub) urls

### ISSUE THREAD

**Issue by fethigurcan** [butlerx/wetty#56]
Hello, thanks for great work.

To work with sub urls.(for example https://blabla.com/wetty/) I have changed these lines.

Some changes are just non-important relative path things but as you notice that I had to remove socket.io's "wetty" name from both path and app code (//).

It is seems completely Ok now.
However I am not sure why I need to remove socket.io name and any side-effects of it or even don't know is it a kind of bug :/ 

Note: I have also another service that is running at root path. (managed by nginx https proxy)

_**index.html:**
    &lt;script src="wetty/hterm_all.js">&lt;/script>
    &lt;script src="socket.io/socket.io.js">&lt;/script>
    &lt;script src="wetty/wetty.js">&lt;/script>_

**app.js:**
_    var io = server(httpserv,{path: '//socket.io'});_

I use latest LTS version(4x) of nodejs and LTS(14.04) ubuntu server.
thanks :)

**Comment by butlerx** [comment]
this is now possible using the `--base` flag
