### ISSUE TITLE
make internal urls relative?

### ISSUE THREAD

**Issue by msx80** [butlerx/wetty#57]
I've set up wetty to work behind apache with modproxy. It should respond to: https://myserver/shell/
Unfortunately, it looks like urls are absolute, and indeed i get the following errors:

```
https://myserver/wetty/hterm_all.js Failed to load resource: the server responded with a status of 404 (Not Found)
https://myserver/wetty/socket.io/socket.io.js Failed to load resource: the server responded with a status of 404 (Not Found)
https://myserver/wetty/wetty.js Failed to load resource: the server responded with a status of 404 (Not Found)
```

With relative urls they should be https://myserver/shell/wetty/wetty.js

**Comment by jesinity** [comment]
yeah it would be great if the URL binding was configurable, at least at build time, so that there would be flexibility in the deployment of wetty.

**Comment by butlerx** [comment]
using the `--base` you can change the base path of the url so its not required to be at `/wetty`
