### ISSUE TITLE
Mouse clicks on wide terminal (mc, htop)

### ISSUE THREAD

**Issue by Lupul** [butlerx/wetty#59]
Has anyone noticed the issue described here:
On wide terminals mouse clicks over column 95 are ignored and the row char is printed out.
- tested on mc and htop with chrome, chromium, and firefox (Ubuntu 15.10 Desktop)

https://groups.google.com/a/chromium.org/forum/#!topic/chromium-hterm/IZTprebuJ_U/discussion

**Comment by butlerx** [comment]
Hterm is no longer used in favour of xterm.js
