### ISSUE TITLE
Support docker attach API?

### ISSUE THREAD

**Issue by lcjlcj** [butlerx/wetty#60]
I searched and didn't see an existing issue. Can you support docker attach API so that we can run a browser terminal for another docker container? See docker API https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#attach-to-a-container

**Comment by DerekTBrown** [comment]
This isn't really within the scope of this project.  There are a couple of things you can do-

1) Use the sshd image on docker, or enable sshd in your dockerfile.
2) Fork this repository, and change the command that is being spawned from ssh to docker

**Comment by butlerx** [comment]
as said above docker attach api is outside the scope of this project
