### ISSUE TITLE
About socket.io version

### ISSUE THREAD

**Issue by 2efPer** [butlerx/wetty#61]
Which version of socket.io does wetty support? 
When I use [Atmosphere extensions](https://github.com/Atmosphere/atmosphere-extensions) for socket.io to Integrate with wetty, everything else seems good ,except  a black screen on my  browser.
In my case , I used socket.io 0.98 in wetty ,so I wanna know is it about socke.io version?
thx

**Comment by jarrettgilliam** [comment]
Currently [`package.json`](https://github.com/krishnasrinivas/wetty/blob/master/package.json#L6) call for a minimum version of 1.3.7.

**Comment by butlerx** [comment]
we support socket.io version 2.2 currently
