### ISSUE TITLE
wetty on AIX

### ISSUE THREAD

**Issue by cqyanbo** [butlerx/wetty#62]
I'm trying to build wetty on AIX machine. I have python 2.7.6 installed on this machine. By following the build steps in README, I got this error:

ImportError:    0509-022 Cannot load module /opt/freeware/lib/python2.7/lib-dynl
oad/binascii.so.
        0509-150   Dependent module libz.so could not be loaded.
        0509-022 Cannot load module libz.so.
        0509-026 System error: A file or directory in the path name does not exi
st.
        0509-022 Cannot load module /opt/freeware/lib/python2.7/lib-dynload/bina
scii.so.
        0509-150   Dependent module /opt/freeware/lib/python2.7/lib-dynload/bina
scii.so could not be loaded.
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/ibm/node/lib/node_modules/npm/node
_modules/node-gyp/lib/configure.js:422:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System AIX 1
gyp ERR! command "/ibm/node/bin/node" "/ibm/node/lib/node_modules/npm/node_modul
es/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/smui-install/wetty/node_modules/pty.js
gyp ERR! node -v v4.4.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
npm ERR! AIX 1
npm ERR! argv "/ibm/node/bin/node" "/ibm/node/bin/npm" "install"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/smui-install/wetty/npm-debug.log

Anyone got this error before? Any ideas?

Thanks!

**Comment by DerekTBrown** [comment]
I believe this is a C++ compiler issue which is fixed in a future version of nan (https://github.com/krishnasrinivas/wetty/issues/64).  I have an outstanding pull request to fix this issue (https://github.com/chjj/pty.js/pull/167).  Could you try updating the version of nan in your installation to 2.3.3 to see if this resolves the problem?

**Comment by DerekTBrown** [comment]
Move to close
