### ISSUE TITLE
Nginx HTTPS protected but IP is not

### ISSUE THREAD

**Issue by Issam2204** [butlerx/wetty#63]
I've setup wetty to run behind NGINX with a Letsencrypt certificate. 

I can access https://terminal.myserver.net, which is  protected with password using a **.htpasswd** file.
However, when I access wetty with IP:PORT there is no password, which is normal because nginx is now left out.
Is there any way to protect the server by not allowing wetty to be reachable from IP:PORT but only on https://terminal.myserver.net ? I'm using SSH passwordless logins so I can't leave it like this. 

Thanks!

**Comment by krishnasrinivas** [comment]
`I've setup wetty to run behind NGINX with a Letsencrypt certificate.`

Can you paste the related config?

wetty uses ssh client with `PreferredAuthentications=password` by default so your passwordless logins can't be misued.

**Comment by Issam2204** [comment]
This is my Nginx config for wetty:

```
# Upstreams
upstream backend_wetty {
    server 127.0.0.1:8500;
}

server {
    listen 443;
    server_name terminal.myserver.net;

    access_log  /var/log/nginx/wetty.access.log;
    error_log   /var/log/nginx/wetty.error.log;

    ssl on;
    ssl_certificate /etc/nginx/certificate.crt;
    ssl_certificate_key /etc/nginx/certificate.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # don’t use SSLv3 ref: POODLE

location / {
        proxy_pass http://terminal.myserver.net:8500/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;

        auth_basic "Restricted Content";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }
}
```

I use wetty with the "--sshauth publickey,password" option.

Thanks for the reply.

**Comment by jarrettgilliam** [comment]
I think merging the rest of #41 would solve this issue. You could then specify `--host 127.0.0.1` to only listen for connections on the loopback device.

Also, without implementing any code changes, you could use a firewall (such as `ufw`) to block all but a few ports.

**Comment by butlerx** [comment]
this feature has now been merged
