### ISSUE TITLE
Reconnect vs. CTRL+W safe guard

### ISSUE THREAD

**Issue by Strubbl** [butlerx/wetty#7]
Use case:
- open wetty
- log in
- log out
- see the overlay with reconnect button
- hit the reconnect button

What i now get is an alert popup asking me if i really want to leave the page. What i expected to get was the login prompt without a confirmation popup before.

PR #1 and PR #3 seem to work against each other. Is it possible to supress the altert popup when using the reconnect button?

**Comment by butlerx** [comment]
this should be fixed in the last commit can you confirm @Strubbl

**Comment by Strubbl** [comment]
The dockerfile needs some love. I am going to fix that and test it.
Any reason why you switched to alpine?

**Comment by Strubbl** [comment]
No, it does not work. I get the prompt. Then i type my login user in and hit ENTER. Then the disconnect overlay appears instead of the password prompt

**Comment by Strubbl** [comment]
I have installed wetty to a subdir wetty/. You introduced a lot of different changes with your last one big commit. Maybe you can split that up a bit, so that i can identify the change, that causes the problem?

**Comment by butlerx** [comment]
didnt actually mean to switch, i accidentally commited file that id had on my local copy, going to be switching to branches and prs going forward i think.

**Comment by butlerx** [comment]
also what debugging did i remove? the console.log ?

**Comment by butlerx** [comment]
@Strubbl think i see the new problem, really shouldn't have committed that dockerfile big mistake on my part should be fixed in #11 

also to answer why i was playing with alpine, i had wanted to switch to make the container smaller and since i assume most people who would use the container would be using it to connect to a different host

**Comment by Strubbl** [comment]
> also what debugging did i remove? the console.log ?

yes. that was what i used to see in which function/block i was

**Comment by Strubbl** [comment]
I just tried the latest commit 6280719c70385e0c6b0cb7170661f17ccef8e37c and if i add openssh to this as a dependency, it works. This is issue is fixed then. Thank you.

So if #11 gets merged, i think this issue can be closed.

**Comment by butlerx** [comment]
#11 should have fixed this
