### ISSUE TITLE
any way to use this without ssh?

### ISSUE THREAD

**Issue by dbkaplun** [butlerx/wetty#71]

**Comment by DerekTBrown** [comment]
I am in the process of working on this as a feature for [RedRouter](https://github.com/DerekTBrown/redrouter), as we are adding a WS SSH feature ontop of the existing SSH Proxy option.  I will look at pushing this code upstream (https://github.com/krishnasrinivas/wetty/issues/72).

**Comment by butlerx** [comment]
if you run as root it will use the login binary for accessing the machine
