### ISSUE TITLE
Wetty with SSH2

### ISSUE THREAD

**Issue by DerekTBrown** [butlerx/wetty#72]
Hello- I am working on a project which relies on Wetty, however, we are looking to use the node SSH2 Module as opposed to using the native SSH Client.  Would you be interested in receiving this upstream?  If so, how do you think it would be best for me to integrate this feature?

**Comment by butlerx** [comment]
always open to a pr. you should look in the `term.ts` to have a shim for ssh. 
closing in favor of any future pr
