### ISSUE TITLE
Extreme slow connection with HTTPS

### ISSUE THREAD

**Issue by caoyangjiang** [butlerx/wetty#74]
Connecting externally using HTTPS is extremely slow and unusable . LAN connection works perfectly. I am new to HTTP and certificate stuff. What is the problem here and how can I fix it?

**Comment by srohit0** [comment]
I second that, it is poor usage of hterm code resulting in unpredictable response over the internet.

**Comment by somebody-somewhere-over-the-rainbow** [comment]
via a nginx reverse proxy appears to be fine performance wise...can not speak for the direct https implementation though.

**Comment by srohit0** [comment]
I'd be willing to look into it.

If you guys send me URL, videos and other help on how to debug http/ssh
with JavaScript.

**Comment by srohit0** [comment]
I get following error consistently when deployed internet.

> WebSocket connection to 'ws://
> guna.paripath.com/wetty/socket.io/?EIO=3&transport=websocket&sid=23WiB10dCgcGHvCKAAAY'
> failed: Error during WebSocket handshake: Unexpected response code: 400
>

Local connection works fine.

**Comment by butlerx** [comment]
if you are running behind a nginx proxy you need to ensure you proxy all traffic including the websocket connections
