### ISSUE TITLE
UTF and accentuated chars

### ISSUE THREAD

**Issue by freeeflyer** [butlerx/wetty#77]
Hello,

The accents are displaying wrong on my french ubuntu...

"é" = "Ã©"
"è" = "Ã¨"
"à" = "Ã "
..

like it's trying to display UTF in ISO mode or something like that..
Do you have an idea what it could be ?

Thanks
Nicolas

**Comment by jap1968** [comment]
Same problem here. That seems to be a problem inherited from hterm, according to this:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-hterm/E2A60Xo4OnI

So far, I have been unable to input chars with the right encoding even using luit:
http://askubuntu.com/a/133221/72238

**Comment by freeeflyer** [comment]
Oh shit I forgot to follow.
I found a solution to this problem.. 
Check here : 
https://github.com/freeeflyer/wetty/commit/a0355ef250e072ef76d5875c1030da47e281c505
Basicaly you dont use UTF16 but UTF8 and you communicate in raw mode between wetty and hterm..
I've not requested any merge because this repo seems dead.. 
You might want to check my fork..

**Comment by jap1968** [comment]
Excellent! That works like a charm and solved my problem. Thanks a lot for your help.
The author of the project seems very active and your changes are really worthy, so I would try to make a request to merge that contribution.

**Comment by freeeflyer** [comment]
done, let's see what happens.

**Comment by butlerx** [comment]
hterm is no longer used in favor xterm.js reopen if the issue continues
