### ISSUE TITLE
Won't install on Ubuntu 16.04

### ISSUE THREAD

**Issue by octopusknives** [butlerx/wetty#78]
There are issues with installing on Ubuntu 16.04. pty.js has node-gyp rebuild issues.

**Comment by lepazca** [comment]
I have the same issue.

**Comment by foxy82** [comment]
Same here I get this:

> pty.js@0.3.1 install /home/username/src/wetty/node_modules/pty.js
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-51-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/username/src/wetty/node_modules/pty.js
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "pty.js"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/username/src/wetty/npm-debug.log

**Comment by foxy82** [comment]
This fixed it for me:
`sudo apt-get install nodejs-legacy`

Details here: [http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu](http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu)

**Comment by octopusknives** [comment]
Didn't work for me. And I already had that installed when I first had the issue.

**Comment by duscha** [comment]
I get the same problem using Debian Jessie. I also installed npm nodejs-legacy, and still get the same error. Any solution?

**Comment by g666nz** [comment]
I too wasted alot of time on this. for future purposes. All you have to do is sudo apt-get install -y build-essential

**Comment by mferraci** [comment]
Update node to last version. Worked for me.
npm cache clean -f
npm install -g n
n stable

**Comment by aerophile** [comment]
thanks @mferraci ,  your solution worked for me

**Comment by Fransan** [comment]
I was getting the same error but in CentOS 6

After some searching I found that what I had to do was to update gcc  from version 4.4 (default in CentOs) to 4.8

I use this guide to update versions: https://edwards.sdsu.edu/research/c11-on-centos-6/

**Comment by syukronrm** [comment]
Same issue. Use `yarn install` instead, it works well.

**Comment by heyphat** [comment]
Hi all, any updates on this issue? none of above suggestions works for me.

**Comment by dallas-x** [comment]
> 
> 
> I too wasted alot of time on this. for future purposes. All you have to do is sudo apt-get install -y build-essential

Thanks mate

**Comment by butlerx** [comment]
as @g666nz pointed out you need build-essential for previously pty.js, now node-pty requires it to build the native modules
