### ISSUE TITLE
fedora 23,24 :: requires inherits@'~2.0.0' but will load undefined

### ISSUE THREAD

**Issue by adriansev** [butlerx/wetty#79]
Hi! I am trying the install of wetty globally with : 
npm install wetty -g (as root)
but in the end i get this : 
/usr/bin/wetty -> /usr/lib/node_modules/wetty/bin/wetty.js
npm WARN unmet dependency /usr/lib/node_modules/block-stream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream-ignore requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream-npm requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/glob requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/npmconf requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/tar requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
wetty@0.2.0 /usr/lib/node_modules/wetty
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── pty.js@0.3.1 (extend@1.2.1, nan@2.3.5)
├── socket.io@1.7.1 (object-assign@4.1.0, socket.io-adapter@0.5.0, has-binary@0.1.7, debug@2.3.3, socket.io-parser@2.3.1, engine.io@1.8.1, socket.io-client@1.7.1)
└── express@3.5.1 (methods@0.1.0, merge-descriptors@0.0.2, debug@0.8.1, cookie-signature@1.0.3, range-parser@1.0.0, fresh@0.2.2, buffer-crc32@0.2.1, cookie@0.1.1, mkdirp@0.3.5, commander@1.3.2, send@0.2.0, connect@2.14.1)

any idea about the problem?
Thank you!

**Comment by butlerx** [comment]
most of these dep have been replaced or upgraded if still an issue please re open
