### ISSUE TITLE
Running out of memory randomly

### ISSUE THREAD

**Issue by sagaramagi** [butlerx/wetty#80]
App crashes randomly with below error:

Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0

Any patch for this?

**Comment by butlerx** [comment]
this looks like a possible issue with either pty.js which has been replaced with node-pty or the node vm itself. given both of these have changed quite a bit since this issue was first open feel free to reopen the issue if its still present
