### ISSUE TITLE
ALT keys within irssi is broken.

### ISSUE THREAD

**Issue by weq** [butlerx/wetty#81]
After my last clone it seems that this function has been removed. CTRL+AD for disconnecting screens etc and CTRL keys works fine within other terminal applications.

Anyone else that can reproduce this? My main reason for using Wetty is so that I have access to my irc client through proxies etc. Until then I just have to live with the workaround I guess ( /windows N )

Thanks for making Wetty :)

**Comment by freeeflyer** [comment]
It actually works on my fork..  the only one not working (or too much working) is CTRL-W.. Guess why ;) 
are you using it on a docker or directly on a server ?
