### ISSUE TITLE
option to set default user and password

### ISSUE THREAD

**Issue by sainisunil05** [butlerx/wetty#84]
Hi, 

We want to open wetty terminal with default username and password. I do not see it is supported by wetty right now. Can someone please suggest how it can be achieved with wetty? 

Thanks
Sunil

**Comment by Bbertatum** [comment]
Hi,

I guess you could achieved this by running passwd once you are connected. At least in the dockerized version... You can use the same way to add user, connect as root adduser...

**Comment by josefernandez91** [comment]
useradd koushik
passwd koushik

New password: redhat
Retype new password: redhat

vi /etc/sudoers

koushik    ALL=(ALL)    NOPASSWD:ALL

**Comment by koushikmln** [comment]
I added an option for this in my wetty fork. You can specify the default username and password in the app.js file. 
you need to install sshpass on your machine for it to support this feature. 
Checkout from here [wetty autologin](https://github.com/koushikmln/wetty)

**Comment by butlerx** [comment]
ssh pass solution has been merged in to master
