### ISSUE TITLE
Rewrite as a module?

### ISSUE THREAD

**Issue by BradfordMedeiros** [butlerx/wetty#88]
This is really cool library, but my main concern with it is that it  seems like the application seems to be written as a command line tool instead of a more composable module form.  Not a horrible thing by any means, but in my case I want to simply run this as another node dependency.

Open to the idea of this being rewritten in module form, so you could start it via require('wetty').start(options) or something similar?  If so I can get to work on it.

**Comment by BradfordMedeiros** [comment]
See #89

**Comment by butlerx** [comment]
wetty.js can now be imported as of version 1
