### ISSUE TITLE
Got an error while trying to get a shell: "Cannot make/remove an entry for the specified session"

### ISSUE THREAD

**Issue by zoobab** [butlerx/wetty#9]
Got an error while trying to get a shell after the login/pwd: "Cannot make/remove an entry for the specified session".

See this screenshot:

http://www.zoobab.com/wetty-bug

Any idea why?

**Comment by krishnasrinivas** [comment]
I am using docker 1.2.0 and it works fine for me. Can you check with latest docker?

**Comment by krishnasrinivas** [comment]
@zoobab shall I close the bug?

**Comment by zoobab** [comment]
Will try on docker 1.2.0 and give you my feedback.

**Comment by j-bennet** [comment]
I still have this issue. Docker version 1.5.0, build a8a31ef, on Linux Mint 13.

**Comment by krishnasrinivas** [comment]
@nathanleclaire did you ever hit this problem?

**Comment by nathanleclaire** [comment]
I haven't- @j-bennet @zoobab which image(s) and commands are you running which give you get this result?  What is your host setup like?  Any VPN or firewall?  `nathanleclaire/wetty` with a similar command works for me.  Tested on Mac/Windows with a VM running boot2docker.

**Comment by j-bennet** [comment]
I am using the dockerized version and the following command:
  sudo docker run --rm --name term -p 3000 -it nathanleclaire/wetty

This is my Docker version:
  Docker version 1.5.0, build a8a31ef

I am on Linux Mint 13, using VPN. Here is my ifconfig output:

docker0   Link encap:Ethernet  HWaddr 56:84:7a:fe:97:99  
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::5484:7aff:fefe:9799/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:391 errors:0 dropped:0 overruns:0 frame:0
          TX packets:459 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1492059 (1.4 MB)  TX bytes:48292 (48.2 KB)

eth0      Link encap:Ethernet  HWaddr 5c:f9:dd:6e:8a:e4  
          inet addr:192.168.0.111  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::5ef9:ddff:fe6e:8ae4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:13651833 errors:0 dropped:0 overruns:0 frame:0
          TX packets:13156118 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:7790327375 (7.7 GB)  TX bytes:11043568767 (11.0 GB)
          Interrupt:20 Memory:dcb00000-dcb20000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:407257 errors:0 dropped:0 overruns:0 frame:0
          TX packets:407257 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:168320811 (168.3 MB)  TX bytes:168320811 (168.3 MB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:172.20.7.36  P-t-P:172.20.7.36  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1300  Metric:1
          RX packets:133 errors:0 dropped:0 overruns:0 frame:0
          TX packets:180 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:21762 (21.7 KB)  TX bytes:16048 (16.0 KB)

veth2850e0b Link encap:Ethernet  HWaddr 3a:d3:c6:bc:01:89  
          inet6 addr: fe80::38d3:c6ff:febc:189/64 Scope:Link
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:5 errors:0 dropped:0 overruns:0 frame:0
          TX packets:18 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:398 (398.0 B)  TX bytes:1632 (1.6 KB)

**Comment by nathanleclaire** [comment]
@j-bennet Hm... that command works for me on boot2docker VM.  If you run wetty natively with `node app.js -p 3000` from the source does it work?

Also, please try `docker rmi nathanleclaire/wetty` and run the docker command you mentioned again.

**Comment by j-bennet** [comment]
@nathanleclaire I tried and I can't run it natively. This is what I did:

```
git clone git@github.com:krishnasrinivas/wetty.git
cd ./wetty
npm install
openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 30000 -nodes
node app.js --sslkey key.pem --sslcert cert.pem -p 3000
```

And this is the error I get:
![wetty-ssh-error](https://cloud.githubusercontent.com/assets/637013/7028986/bfe643bc-dd0e-11e4-9a5b-e43c26a48186.png)

**Comment by krishnasrinivas** [comment]
@j-bennet it's giving 'connection refused' as you are not running ssh-server at port 22 on your localhost. Can you try @nathanleclaire's other suggestion of doing 'rmi' and re-running?

**Comment by j-bennet** [comment]
@krishnasrinivas Yes, I actually tried that suggestion first. I got the same "Cannot make/remove an entry..." error as before.

**Comment by krishnasrinivas** [comment]
@j-bennet still having this issue?

**Comment by j-bennet** [comment]
I just tried the docker image again, this time on Mac with docker-machine. I don't have the same error. However, when I browse to {docker container IP}:3000, Firefox says "Connecting...", never connects, then spits out a "The connection has timed out" page.

**Comment by tturbs** [comment]
Anyone have solution of this?
I got same error on it.

**Comment by dsaikiran** [comment]
Can anyone help me?

On Ubuntu, it's working fine, but in CentOs7 after proving credentials it displayed: "Cannot make/remove an entry for the specified session"

**Comment by heatmiser** [comment]
Not sure if applicable to present code base running on CentOS7, however, prior to Oct 22, 2017 when app.js was still present and executed by the node entry point, this issue could be resolved by modifying the following line in /etc/pam.d/login
session    required     pam_loginuid.so
to
session    optional     pam_loginuid.so

**Comment by butlerx** [comment]
closing issue due to lack of recent activity. 
if this is still an issue please reopen, and if @heatmiser suggestion works please feel free to open a pr documenting this
