### ISSUE TITLE
Public key authorization

### ISSUE THREAD

**Issue by plato79** [butlerx/wetty#91]
Hi,

Is there any way to setup public key authorization so we could login without user/password?

It stores known_servers somewhere in chrome profile it seems ( it remembers the server when I reconnect to server ) so I think in a similar way we could put our public key file to somewhere in chrome profile?

**Comment by yp6128** [comment]
That will be great !
+1

**Comment by butlerx** [comment]
this is possible with the `---sshkey` flag but should not be left on a public endpoint as youll leave yourself open to attack
