### ISSUE TITLE
Can I pass username and password with query string to access webconsole

### ISSUE THREAD

**Issue by rkkrishnaa** [butlerx/wetty#99]
Hello,

I am trying to access my remote session by passing the authentication info as query string. It is not working. 
Example: **http://192.168.1.10:3000/wetty/ssh/user=username&password=password**

I have checked the option that user can pass the username in addition to the login url. It again asks me to type login user name and password.
Example: **http://192.168.1.10:3000/wetty/ssh/username**

Is there any way to achieve the above two things.

Best Regards,
Radhakrishnan Rk

**Comment by koushikmln** [comment]
@rkkrishnaa you can check out my fork for the feature. You can pass the password as a query string and login automatically.

https://github.com/koushikmln/wetty

**Comment by butlerx** [comment]
@koushikmln fork has now been merged to master
